coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: 50%
        threshold: 5%
        informational: true

flags:
  unit:
    paths:
      - stellarsdk/stellarsdk/
    carryforward: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "stellarsdk/stellarsdkUnitTests/**/*"
  - "stellarsdk/stellarsdkIntegrationTests/**/*"
  - "stellarsdk/stellarsdkTests/**/*"
  - "stellarsdk/stellarsdk/constants/**/*"
  - "stellarsdk/stellarsdk/libs/**/*"
