// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum AccountFlags: Int32, XDRCodable, Equatable, Sendable {
  case requiredFlag = 1
  case revocableFlag = 2
  case immutableFlag = 4
  case clawbackEnabledFlag = 8
}
