// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct AccountEntryExtensionV1: XDRCodable, Sendable {
  public let liabilities: LiabilitiesXDR
  public let reserved: AccountEntryExtV1XDR

  public init(liabilities: LiabilitiesXDR, reserved: AccountEntryExtV1XDR) {
    self.liabilities = liabilities
    self.reserved = reserved
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    liabilities = try container.decode(LiabilitiesXDR.self)
    reserved = try container.decode(AccountEntryExtV1XDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(liabilities)
    try container.encode(reserved)
  }
}
