// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum AllowTrustOpAssetXDR: XDRCodable, Sendable {
  case alphanum4(WrappedData4)
  case alphanum12(WrappedData12)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case AssetType.ASSET_TYPE_CREDIT_ALPHANUM4:
      let val = try container.decode(WrappedData4.self)
      self = .alphanum4(val)
    case AssetType.ASSET_TYPE_CREDIT_ALPHANUM12:
      let val = try container.decode(WrappedData12.self)
      self = .alphanum12(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown AllowTrustOpAssetXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .alphanum4: return AssetType.ASSET_TYPE_CREDIT_ALPHANUM4
    case .alphanum12: return AssetType.ASSET_TYPE_CREDIT_ALPHANUM12
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .alphanum4(let val):
      try container.encode(val)
    case .alphanum12(let val):
      try container.encode(val)
    }
  }
}
