// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum AllowTrustOpAssetXDR: XDRCodable, Sendable {
  case alphanum4(AssetCode4XDR)
  case alphanum12(AssetCode12XDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case AssetType.creditAlphanum4.rawValue:
      let val = try container.decode(AssetCode4XDR.self)
      self = .alphanum4(val)
    case AssetType.creditAlphanum12.rawValue:
      let val = try container.decode(AssetCode12XDR.self)
      self = .alphanum12(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown AllowTrustOpAssetXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .alphanum4: return AssetType.creditAlphanum4.rawValue
    case .alphanum12: return AssetType.creditAlphanum12.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .alphanum4(let val):
      try container.encode(val)
    case .alphanum12(let val):
      try container.encode(val)
    }
  }
}
