// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct Alpha12XDR: XDRCodable, Sendable {
  public let assetCode: AssetCode12XDR
  public let issuer: PublicKey

  public init(assetCode: AssetCode12XDR, issuer: PublicKey) {
    self.assetCode = assetCode
    self.issuer = issuer
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    assetCode = try container.decode(AssetCode12XDR.self)
    issuer = try container.decode(PublicKey.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(assetCode)
    try container.encode(issuer)
  }
}

extension Alpha12XDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).assetCode: \(TxRepHelper.bytesToHex(self.assetCode.wrapped))")
    lines.append("\(prefix).issuer: \(TxRepHelper.formatAccountId(self.issuer))")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> Alpha12XDR {
    let assetCode: AssetCode12XDR = try TxRepHelper.requireWrappedData12(map, "\(prefix).assetCode")
    let issuer: PublicKey = try TxRepHelper.requireAccountId(map, "\(prefix).issuer")
    return Alpha12XDR(assetCode: assetCode, issuer: issuer)
  }
}

extension Alpha12XDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "asset_code", value: try AssetCode12XDRJsonCodec.toXdrJsonValue(self.assetCode, type: "Alpha12XDR", key: "asset_code")))
    members.append(XdrJsonMember(key: "issuer", value: try AccountIDXDRJsonCodec.toXdrJsonValue(self.issuer, type: "Alpha12XDR", key: "issuer")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> Alpha12XDR {
    let members = try XdrJson.object(value, type: "Alpha12XDR", keys: ["asset_code", "issuer"])
    let assetCode: AssetCode12XDR = try AssetCode12XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "asset_code", type: "Alpha12XDR"), type: "Alpha12XDR", key: "asset_code")
    let issuer: PublicKey = try AccountIDXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "issuer", type: "Alpha12XDR"), type: "Alpha12XDR", key: "issuer")
    return Alpha12XDR(assetCode: assetCode, issuer: issuer)
  }
}
