// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum AuthenticatedMessageXDR: XDRCodable, Sendable {
  case v0(AuthenticatedMessageXDRV0XDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case 0:
      let val = try container.decode(AuthenticatedMessageXDRV0XDR.self)
      self = .v0(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown AuthenticatedMessageXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .v0: return 0
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .v0(let val):
      try container.encode(val)
    }
  }
}

extension AuthenticatedMessageXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .v0(let payload):
      return .object([XdrJsonMember(key: "v0", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> AuthenticatedMessageXDR {
    if case .string(let name) = value {
      switch name {
      case "v0":
        throw XdrJsonError.invalidValue(type: "AuthenticatedMessageXDR", key: "v0",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "AuthenticatedMessageXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "AuthenticatedMessageXDR")
    switch member.key {
    case "v0":
      let v0: AuthenticatedMessageXDRV0XDR = try AuthenticatedMessageXDRV0XDR.fromXdrJsonValue(member.value)
      return .v0(v0)
    default:
      throw XdrJsonError.unknownUnionArm(type: "AuthenticatedMessageXDR", key: member.key)
    }
  }
}
