// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum BumpSequenceResultXDR: XDRCodable, Sendable {
  case success
  case badSeq

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case BumpSequenceResultCode.success.rawValue:
      self = .success
    case BumpSequenceResultCode.badSeq.rawValue:
      self = .badSeq
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown BumpSequenceResultXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .success: return BumpSequenceResultCode.success.rawValue
    case .badSeq: return BumpSequenceResultCode.badSeq.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .success:
      break
    case .badSeq:
      break
    }
  }
}
