// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ChangeTrustResultCode: Int32, XDRCodable, Equatable, Sendable {
  case success = 0
  case malformed = -1
  case noIssuer = -2
  case invalidLimit = -3
  case lowReserve = -4
  case selfNotAllowed = -5
  case trustLineMissing = -6
  case cannotDelete = -7
  case notAuthMaintainLiabilities = -8
}
