// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ChangeTrustAssetXDR: XDRCodable, Sendable {
  case native
  case alphanum4(Alpha4XDR)
  case alphanum12(Alpha12XDR)
  case poolShare(LiquidityPoolParametersXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case AssetType.native.rawValue:
      self = .native
    case AssetType.creditAlphanum4.rawValue:
      let val = try container.decode(Alpha4XDR.self)
      self = .alphanum4(val)
    case AssetType.creditAlphanum12.rawValue:
      let val = try container.decode(Alpha12XDR.self)
      self = .alphanum12(val)
    case AssetType.poolShare.rawValue:
      let val = try container.decode(LiquidityPoolParametersXDR.self)
      self = .poolShare(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ChangeTrustAssetXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .native: return AssetType.native.rawValue
    case .alphanum4: return AssetType.creditAlphanum4.rawValue
    case .alphanum12: return AssetType.creditAlphanum12.rawValue
    case .poolShare: return AssetType.poolShare.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .native:
      break
    case .alphanum4(let val):
      try container.encode(val)
    case .alphanum12(let val):
      try container.encode(val)
    case .poolShare(let val):
      try container.encode(val)
    }
  }
}
