// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ClaimantXDR: XDRCodable, Sendable {
  case claimantTypeV0(ClaimantV0XDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case ClaimantType.claimantTypeV0.rawValue:
      let val = try container.decode(ClaimantV0XDR.self)
      self = .claimantTypeV0(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ClaimantXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .claimantTypeV0: return ClaimantType.claimantTypeV0.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .claimantTypeV0(let val):
      try container.encode(val)
    }
  }
}
