// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ClaimableBalanceEntryExtXDR: XDRCodable, Sendable {
  case void
  case claimableBalanceEntryExtensionV1(ClaimableBalanceEntryExtensionV1)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case 0:
      self = .void
    case 1:
      let val = try container.decode(ClaimableBalanceEntryExtensionV1.self)
      self = .claimableBalanceEntryExtensionV1(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ClaimableBalanceEntryExtXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .void: return 0
    case .claimableBalanceEntryExtensionV1: return 1
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .void:
      break
    case .claimableBalanceEntryExtensionV1(let val):
      try container.encode(val)
    }
  }
}

extension ClaimableBalanceEntryExtXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .void: return .string("v0")
    case .claimableBalanceEntryExtensionV1(let payload):
      return .object([XdrJsonMember(key: "v1", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> ClaimableBalanceEntryExtXDR {
    if case .string(let name) = value {
      switch name {
      case "v0":
        return .void
      case "v1":
        throw XdrJsonError.invalidValue(type: "ClaimableBalanceEntryExtXDR", key: "v1",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "ClaimableBalanceEntryExtXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "ClaimableBalanceEntryExtXDR")
    switch member.key {
    case "v0":
      throw XdrJsonError.invalidValue(type: "ClaimableBalanceEntryExtXDR", key: "v0",
                                      message: "this arm carries no value, so it is written as a bare string")
    case "v1":
      let claimableBalanceEntryExtensionV1: ClaimableBalanceEntryExtensionV1 = try ClaimableBalanceEntryExtensionV1.fromXdrJsonValue(member.value)
      return .claimableBalanceEntryExtensionV1(claimableBalanceEntryExtensionV1)
    default:
      throw XdrJsonError.unknownUnionArm(type: "ClaimableBalanceEntryExtXDR", key: member.key)
    }
  }
}
