// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ClaimAtomType: Int32, XDRCodable, Equatable, Sendable {
  case v0 = 0
  case orderBook = 1
  case liquidityPool = 2
}
