// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ClaimableBalanceIDXDR: XDRCodable, Sendable {
  case claimableBalanceIDTypeV0(HashXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case ClaimableBalanceIDType.claimableBalanceIDTypeV0.rawValue:
      let val = try container.decode(HashXDR.self)
      self = .claimableBalanceIDTypeV0(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ClaimableBalanceIDXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .claimableBalanceIDTypeV0: return ClaimableBalanceIDType.claimableBalanceIDTypeV0.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .claimableBalanceIDTypeV0(let val):
      try container.encode(val)
    }
  }
}

extension ClaimableBalanceIDXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    switch self {
    case .claimableBalanceIDTypeV0(let val):
      lines.append("\(prefix).type: CLAIMABLE_BALANCE_ID_TYPE_V0")
      lines.append("\(prefix).v0: \(TxRepHelper.bytesToHex(val.wrapped))")
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> ClaimableBalanceIDXDR {
    let discKey = "\(prefix).type"
    guard let discName = TxRepHelper.getValue(map, discKey) else {
      throw TxRepError.missingValue(key: discKey)
    }
    switch discName {
    case "CLAIMABLE_BALANCE_ID_TYPE_V0":
      let val = try TxRepHelper.requireWrappedData32(map, "\(prefix).v0")
      return .claimableBalanceIDTypeV0(val)
    default:
      throw TxRepError.invalidValue(key: discKey)
    }
  }
}
