// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public indirect enum ClaimPredicateXDR: XDRCodable, Sendable {
  case claimPredicateUnconditional
  case claimPredicateAnd([ClaimPredicateXDR])
  case claimPredicateOr([ClaimPredicateXDR])
  case claimPredicateNot(ClaimPredicateXDR?)
  case claimPredicateBeforeAbsTime(Int64)
  case claimPredicateBeforeRelTime(Int64)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case ClaimPredicateType.claimPredicateUnconditional.rawValue:
      self = .claimPredicateUnconditional
    case ClaimPredicateType.claimPredicateAnd.rawValue:
      let val = try decodeArray(type: ClaimPredicateXDR.self, dec: decoder)
      self = .claimPredicateAnd(val)
    case ClaimPredicateType.claimPredicateOr.rawValue:
      let val = try decodeArray(type: ClaimPredicateXDR.self, dec: decoder)
      self = .claimPredicateOr(val)
    case ClaimPredicateType.claimPredicateNot.rawValue:
      let claimPredicateNotPresent = try container.decode(Int32.self)
      if claimPredicateNotPresent != 0 {
        self = .claimPredicateNot(try container.decode(ClaimPredicateXDR.self))
      } else {
        self = .claimPredicateNot(nil)
      }
    case ClaimPredicateType.claimPredicateBeforeAbsTime.rawValue:
      let val = try container.decode(Int64.self)
      self = .claimPredicateBeforeAbsTime(val)
    case ClaimPredicateType.claimPredicateBeforeRelTime.rawValue:
      let val = try container.decode(Int64.self)
      self = .claimPredicateBeforeRelTime(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ClaimPredicateXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .claimPredicateUnconditional: return ClaimPredicateType.claimPredicateUnconditional.rawValue
    case .claimPredicateAnd: return ClaimPredicateType.claimPredicateAnd.rawValue
    case .claimPredicateOr: return ClaimPredicateType.claimPredicateOr.rawValue
    case .claimPredicateNot: return ClaimPredicateType.claimPredicateNot.rawValue
    case .claimPredicateBeforeAbsTime: return ClaimPredicateType.claimPredicateBeforeAbsTime.rawValue
    case .claimPredicateBeforeRelTime: return ClaimPredicateType.claimPredicateBeforeRelTime.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .claimPredicateUnconditional:
      break
    case .claimPredicateAnd(let val):
      try container.encode(val)
    case .claimPredicateOr(let val):
      try container.encode(val)
    case .claimPredicateNot(let val):
      if let val = val {
        try container.encode(Int32(1))
        try container.encode(val)
      } else {
        try container.encode(Int32(0))
      }
    case .claimPredicateBeforeAbsTime(let val):
      try container.encode(val)
    case .claimPredicateBeforeRelTime(let val):
      try container.encode(val)
    }
  }
}
