// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ClaimAtomXDR: XDRCodable, Sendable {
  case v0(ClaimOfferAtomV0XDR)
  case orderBook(ClaimOfferAtomXDR)
  case liquidityPool(ClaimLiquidityAtomXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case ClaimAtomType.v0.rawValue:
      let val = try container.decode(ClaimOfferAtomV0XDR.self)
      self = .v0(val)
    case ClaimAtomType.orderBook.rawValue:
      let val = try container.decode(ClaimOfferAtomXDR.self)
      self = .orderBook(val)
    case ClaimAtomType.liquidityPool.rawValue:
      let val = try container.decode(ClaimLiquidityAtomXDR.self)
      self = .liquidityPool(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ClaimAtomXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .v0: return ClaimAtomType.v0.rawValue
    case .orderBook: return ClaimAtomType.orderBook.rawValue
    case .liquidityPool: return ClaimAtomType.liquidityPool.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .v0(let val):
      try container.encode(val)
    case .orderBook(let val):
      try container.encode(val)
    case .liquidityPool(let val):
      try container.encode(val)
    }
  }
}
