// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ClaimClaimableBalanceResultXDR: XDRCodable, Sendable {
  case success
  case doesNotExist
  case cannotClaim
  case lineFull
  case noTrust
  case notAuthorized

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case ClaimClaimableBalanceResultCode.success.rawValue:
      self = .success
    case ClaimClaimableBalanceResultCode.doesNotExist.rawValue:
      self = .doesNotExist
    case ClaimClaimableBalanceResultCode.cannotClaim.rawValue:
      self = .cannotClaim
    case ClaimClaimableBalanceResultCode.lineFull.rawValue:
      self = .lineFull
    case ClaimClaimableBalanceResultCode.noTrust.rawValue:
      self = .noTrust
    case ClaimClaimableBalanceResultCode.notAuthorized.rawValue:
      self = .notAuthorized
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ClaimClaimableBalanceResultXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .success: return ClaimClaimableBalanceResultCode.success.rawValue
    case .doesNotExist: return ClaimClaimableBalanceResultCode.doesNotExist.rawValue
    case .cannotClaim: return ClaimClaimableBalanceResultCode.cannotClaim.rawValue
    case .lineFull: return ClaimClaimableBalanceResultCode.lineFull.rawValue
    case .noTrust: return ClaimClaimableBalanceResultCode.noTrust.rawValue
    case .notAuthorized: return ClaimClaimableBalanceResultCode.notAuthorized.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .success:
      break
    case .doesNotExist:
      break
    case .cannotClaim:
      break
    case .lineFull:
      break
    case .noTrust:
      break
    case .notAuthorized:
      break
    }
  }
}
