// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ClawbackResultXDR: XDRCodable, Sendable {
  case success
  case malformed
  case notClawbackEnabled
  case noTrust
  case underfunded

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case ClawbackResultCode.success.rawValue:
      self = .success
    case ClawbackResultCode.malformed.rawValue:
      self = .malformed
    case ClawbackResultCode.notClawbackEnabled.rawValue:
      self = .notClawbackEnabled
    case ClawbackResultCode.noTrust.rawValue:
      self = .noTrust
    case ClawbackResultCode.underfunded.rawValue:
      self = .underfunded
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ClawbackResultXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .success: return ClawbackResultCode.success.rawValue
    case .malformed: return ClawbackResultCode.malformed.rawValue
    case .notClawbackEnabled: return ClawbackResultCode.notClawbackEnabled.rawValue
    case .noTrust: return ClawbackResultCode.noTrust.rawValue
    case .underfunded: return ClawbackResultCode.underfunded.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .success:
      break
    case .malformed:
      break
    case .notClawbackEnabled:
      break
    case .noTrust:
      break
    case .underfunded:
      break
    }
  }
}
