// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ClawbackOpXDR: XDRCodable, Sendable {
  public let asset: AssetXDR
  public let from: MuxedAccountXDR
  public let amount: Int64

  public init(
    asset: AssetXDR,
    from: MuxedAccountXDR,
    amount: Int64
  ) {
    self.asset = asset
    self.from = from
    self.amount = amount
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    asset = try container.decode(AssetXDR.self)
    from = try container.decode(MuxedAccountXDR.self)
    amount = try container.decode(Int64.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(asset)
    try container.encode(from)
    try container.encode(amount)
  }
}

extension ClawbackOpXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).asset: \(TxRepHelper.formatAsset(self.asset))")
    lines.append("\(prefix).from: \(try TxRepHelper.formatMuxedAccount(self.from))")
    lines.append("\(prefix).amount: \(self.amount)")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> ClawbackOpXDR {
    let asset: AssetXDR = try TxRepHelper.requireAsset(map, "\(prefix).asset")
    let from: MuxedAccountXDR = try TxRepHelper.requireMuxedAccount(map, "\(prefix).from")
    let amount: Int64 = try TxRepHelper.parseInt64(TxRepHelper.getValue(map, "\(prefix).amount") ?? "0")
    return ClawbackOpXDR(asset: asset, from: from, amount: amount)
  }
}

extension ClawbackOpXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "asset", value: try self.asset.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "from", value: try self.from.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "amount", value: try Int64XDRJsonCodec.toXdrJsonValue(self.amount, type: "ClawbackOpXDR", key: "amount")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> ClawbackOpXDR {
    let members = try XdrJson.object(value, type: "ClawbackOpXDR", keys: ["asset", "from", "amount"])
    let asset: AssetXDR = try AssetXDR.fromXdrJsonValue(try XdrJson.field(members, key: "asset", type: "ClawbackOpXDR"))
    let from: MuxedAccountXDR = try MuxedAccountXDR.fromXdrJsonValue(try XdrJson.field(members, key: "from", type: "ClawbackOpXDR"))
    let amount: Int64 = try Int64XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "amount", type: "ClawbackOpXDR"), type: "ClawbackOpXDR", key: "amount")
    return ClawbackOpXDR(
      asset: asset,
      from: from,
      amount: amount
    )
  }
}
