// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ClawbackClaimableBalanceResultXDR: XDRCodable, Sendable {
  case success
  case doesNotExist
  case notIssuer
  case notClawbackEnabled

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case ClawbackClaimableBalanceResultCode.success.rawValue:
      self = .success
    case ClawbackClaimableBalanceResultCode.doesNotExist.rawValue:
      self = .doesNotExist
    case ClawbackClaimableBalanceResultCode.notIssuer.rawValue:
      self = .notIssuer
    case ClawbackClaimableBalanceResultCode.notClawbackEnabled.rawValue:
      self = .notClawbackEnabled
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ClawbackClaimableBalanceResultXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .success: return ClawbackClaimableBalanceResultCode.success.rawValue
    case .doesNotExist: return ClawbackClaimableBalanceResultCode.doesNotExist.rawValue
    case .notIssuer: return ClawbackClaimableBalanceResultCode.notIssuer.rawValue
    case .notClawbackEnabled: return ClawbackClaimableBalanceResultCode.notClawbackEnabled.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .success:
      break
    case .doesNotExist:
      break
    case .notIssuer:
      break
    case .notClawbackEnabled:
      break
    }
  }
}

extension ClawbackClaimableBalanceResultXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .success: return .string("success")
    case .doesNotExist: return .string("does_not_exist")
    case .notIssuer: return .string("not_issuer")
    case .notClawbackEnabled: return .string("not_clawback_enabled")
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> ClawbackClaimableBalanceResultXDR {
    let name = try XdrJson.string(value, type: "ClawbackClaimableBalanceResultXDR")
    switch name {
    case "success":
      return .success
    case "does_not_exist":
      return .doesNotExist
    case "not_issuer":
      return .notIssuer
    case "not_clawback_enabled":
      return .notClawbackEnabled
    default:
      throw XdrJsonError.unknownUnionArm(type: "ClawbackClaimableBalanceResultXDR", key: name)
    }
  }
}
