// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ConfigUpgradeSetXDR: XDRCodable, Sendable {
  public var updatedEntry: [ConfigSettingEntryXDR]

  public init(updatedEntry: [ConfigSettingEntryXDR]) {
    self.updatedEntry = updatedEntry
  }

  public init(from decoder: Decoder) throws {
    updatedEntry = try decodeArray(type: ConfigSettingEntryXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(updatedEntry)
  }
}

extension ConfigUpgradeSetXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "updated_entry", value: try XdrJson.array(self.updatedEntry.map { element in try element.toXdrJsonValue() })))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> ConfigUpgradeSetXDR {
    let members = try XdrJson.object(value, type: "ConfigUpgradeSetXDR", keys: ["updated_entry"])
    let updatedEntryElements = try XdrJson.array(try XdrJson.field(members, key: "updated_entry", type: "ConfigUpgradeSetXDR"), type: "ConfigUpgradeSetXDR", key: "updated_entry")
    let updatedEntry: [ConfigSettingEntryXDR] = try updatedEntryElements.map { element in try ConfigSettingEntryXDR.fromXdrJsonValue(element) }
    return ConfigUpgradeSetXDR(updatedEntry: updatedEntry)
  }
}
