// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ConfigUpgradeSetKeyXDR: XDRCodable, Sendable {
  public var contractID: WrappedData32
  public var contentHash: WrappedData32

  public init(contractID: WrappedData32, contentHash: WrappedData32) {
    self.contractID = contractID
    self.contentHash = contentHash
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    contractID = try container.decode(WrappedData32.self)
    contentHash = try container.decode(WrappedData32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(contractID)
    try container.encode(contentHash)
  }
}
