// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ConfigSettingSCPTiming: XDRCodable, Sendable {
  public var ledgerTargetCloseTimeMilliseconds: UInt32
  public var nominationTimeoutInitialMilliseconds: UInt32
  public var nominationTimeoutIncrementMilliseconds: UInt32
  public var ballotTimeoutInitialMilliseconds: UInt32
  public var ballotTimeoutIncrementMilliseconds: UInt32

  public init(
    ledgerTargetCloseTimeMilliseconds: UInt32,
    nominationTimeoutInitialMilliseconds: UInt32,
    nominationTimeoutIncrementMilliseconds: UInt32,
    ballotTimeoutInitialMilliseconds: UInt32,
    ballotTimeoutIncrementMilliseconds: UInt32
  ) {
    self.ledgerTargetCloseTimeMilliseconds = ledgerTargetCloseTimeMilliseconds
    self.nominationTimeoutInitialMilliseconds = nominationTimeoutInitialMilliseconds
    self.nominationTimeoutIncrementMilliseconds = nominationTimeoutIncrementMilliseconds
    self.ballotTimeoutInitialMilliseconds = ballotTimeoutInitialMilliseconds
    self.ballotTimeoutIncrementMilliseconds = ballotTimeoutIncrementMilliseconds
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    ledgerTargetCloseTimeMilliseconds = try container.decode(UInt32.self)
    nominationTimeoutInitialMilliseconds = try container.decode(UInt32.self)
    nominationTimeoutIncrementMilliseconds = try container.decode(UInt32.self)
    ballotTimeoutInitialMilliseconds = try container.decode(UInt32.self)
    ballotTimeoutIncrementMilliseconds = try container.decode(UInt32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(ledgerTargetCloseTimeMilliseconds)
    try container.encode(nominationTimeoutInitialMilliseconds)
    try container.encode(nominationTimeoutIncrementMilliseconds)
    try container.encode(ballotTimeoutInitialMilliseconds)
    try container.encode(ballotTimeoutIncrementMilliseconds)
  }
}

extension ConfigSettingSCPTiming: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "ledger_target_close_time_milliseconds", value: try Uint32XDRJsonCodec.toXdrJsonValue(self.ledgerTargetCloseTimeMilliseconds, type: "ConfigSettingSCPTiming", key: "ledger_target_close_time_milliseconds")))
    members.append(XdrJsonMember(key: "nomination_timeout_initial_milliseconds", value: try Uint32XDRJsonCodec.toXdrJsonValue(self.nominationTimeoutInitialMilliseconds, type: "ConfigSettingSCPTiming", key: "nomination_timeout_initial_milliseconds")))
    members.append(XdrJsonMember(key: "nomination_timeout_increment_milliseconds", value: try Uint32XDRJsonCodec.toXdrJsonValue(self.nominationTimeoutIncrementMilliseconds, type: "ConfigSettingSCPTiming", key: "nomination_timeout_increment_milliseconds")))
    members.append(XdrJsonMember(key: "ballot_timeout_initial_milliseconds", value: try Uint32XDRJsonCodec.toXdrJsonValue(self.ballotTimeoutInitialMilliseconds, type: "ConfigSettingSCPTiming", key: "ballot_timeout_initial_milliseconds")))
    members.append(XdrJsonMember(key: "ballot_timeout_increment_milliseconds", value: try Uint32XDRJsonCodec.toXdrJsonValue(self.ballotTimeoutIncrementMilliseconds, type: "ConfigSettingSCPTiming", key: "ballot_timeout_increment_milliseconds")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> ConfigSettingSCPTiming {
    let members = try XdrJson.object(value, type: "ConfigSettingSCPTiming", keys: ["ledger_target_close_time_milliseconds", "nomination_timeout_initial_milliseconds", "nomination_timeout_increment_milliseconds", "ballot_timeout_initial_milliseconds", "ballot_timeout_increment_milliseconds"])
    let ledgerTargetCloseTimeMilliseconds: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "ledger_target_close_time_milliseconds", type: "ConfigSettingSCPTiming"), type: "ConfigSettingSCPTiming", key: "ledger_target_close_time_milliseconds")
    let nominationTimeoutInitialMilliseconds: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "nomination_timeout_initial_milliseconds", type: "ConfigSettingSCPTiming"), type: "ConfigSettingSCPTiming", key: "nomination_timeout_initial_milliseconds")
    let nominationTimeoutIncrementMilliseconds: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "nomination_timeout_increment_milliseconds", type: "ConfigSettingSCPTiming"), type: "ConfigSettingSCPTiming", key: "nomination_timeout_increment_milliseconds")
    let ballotTimeoutInitialMilliseconds: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "ballot_timeout_initial_milliseconds", type: "ConfigSettingSCPTiming"), type: "ConfigSettingSCPTiming", key: "ballot_timeout_initial_milliseconds")
    let ballotTimeoutIncrementMilliseconds: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "ballot_timeout_increment_milliseconds", type: "ConfigSettingSCPTiming"), type: "ConfigSettingSCPTiming", key: "ballot_timeout_increment_milliseconds")
    return ConfigSettingSCPTiming(
      ledgerTargetCloseTimeMilliseconds: ledgerTargetCloseTimeMilliseconds,
      nominationTimeoutInitialMilliseconds: nominationTimeoutInitialMilliseconds,
      nominationTimeoutIncrementMilliseconds: nominationTimeoutIncrementMilliseconds,
      ballotTimeoutInitialMilliseconds: ballotTimeoutInitialMilliseconds,
      ballotTimeoutIncrementMilliseconds: ballotTimeoutIncrementMilliseconds
    )
  }
}
