// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ConfigSettingContractComputeV0XDR: XDRCodable, Sendable {
  public var ledgerMaxInstructions: Int64
  public var txMaxInstructions: Int64
  public var feeRatePerInstructionsIncrement: Int64
  public var txMemoryLimit: UInt32

  public init(
    ledgerMaxInstructions: Int64,
    txMaxInstructions: Int64,
    feeRatePerInstructionsIncrement: Int64,
    txMemoryLimit: UInt32
  ) {
    self.ledgerMaxInstructions = ledgerMaxInstructions
    self.txMaxInstructions = txMaxInstructions
    self.feeRatePerInstructionsIncrement = feeRatePerInstructionsIncrement
    self.txMemoryLimit = txMemoryLimit
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    ledgerMaxInstructions = try container.decode(Int64.self)
    txMaxInstructions = try container.decode(Int64.self)
    feeRatePerInstructionsIncrement = try container.decode(Int64.self)
    txMemoryLimit = try container.decode(UInt32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(ledgerMaxInstructions)
    try container.encode(txMaxInstructions)
    try container.encode(feeRatePerInstructionsIncrement)
    try container.encode(txMemoryLimit)
  }
}
