// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ConstantProductXDR: XDRCodable, Sendable {
  public let params: LiquidityPoolConstantProductParametersXDR
  public let reserveA: Int64
  public let reserveB: Int64
  public let totalPoolShares: Int64
  public let poolSharesTrustLineCount: Int64

  public init(
    params: LiquidityPoolConstantProductParametersXDR,
    reserveA: Int64,
    reserveB: Int64,
    totalPoolShares: Int64,
    poolSharesTrustLineCount: Int64
  ) {
    self.params = params
    self.reserveA = reserveA
    self.reserveB = reserveB
    self.totalPoolShares = totalPoolShares
    self.poolSharesTrustLineCount = poolSharesTrustLineCount
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    params = try container.decode(LiquidityPoolConstantProductParametersXDR.self)
    reserveA = try container.decode(Int64.self)
    reserveB = try container.decode(Int64.self)
    totalPoolShares = try container.decode(Int64.self)
    poolSharesTrustLineCount = try container.decode(Int64.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(params)
    try container.encode(reserveA)
    try container.encode(reserveB)
    try container.encode(totalPoolShares)
    try container.encode(poolSharesTrustLineCount)
  }
}
