// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ContractCodeEntryXDR: XDRCodable, Sendable {
  public var ext: ContractCodeEntryExt
  public var hash: HashXDR
  public var code: Data

  public init(
    ext: ContractCodeEntryExt,
    hash: HashXDR,
    code: Data
  ) {
    self.ext = ext
    self.hash = hash
    self.code = code
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    ext = try container.decode(ContractCodeEntryExt.self)
    hash = try container.decode(HashXDR.self)
    code = try container.decode(Data.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(ext)
    try container.encode(hash)
    try container.encode(code)
  }
}

extension ContractCodeEntryXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "ext", value: try self.ext.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "hash", value: try HashXDRJsonCodec.toXdrJsonValue(self.hash, type: "ContractCodeEntryXDR", key: "hash")))
    members.append(XdrJsonMember(key: "code", value: XdrJson.hex(self.code)))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> ContractCodeEntryXDR {
    let members = try XdrJson.object(value, type: "ContractCodeEntryXDR", keys: ["ext", "hash", "code"])
    let ext: ContractCodeEntryExt = try ContractCodeEntryExt.fromXdrJsonValue(try XdrJson.field(members, key: "ext", type: "ContractCodeEntryXDR"))
    let hash: HashXDR = try HashXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "hash", type: "ContractCodeEntryXDR"), type: "ContractCodeEntryXDR", key: "hash")
    let code: Data = try XdrJson.hex(try XdrJson.field(members, key: "code", type: "ContractCodeEntryXDR"), type: "ContractCodeEntryXDR", key: "code")
    return ContractCodeEntryXDR(
      ext: ext,
      hash: hash,
      code: code
    )
  }
}
