// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ContractIDPreimageFromAddressXDR: XDRCodable, Sendable {
  public var address: SCAddressXDR
  public var salt: WrappedData32

  public init(address: SCAddressXDR, salt: WrappedData32) {
    self.address = address
    self.salt = salt
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    address = try container.decode(SCAddressXDR.self)
    salt = try container.decode(WrappedData32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(address)
    try container.encode(salt)
  }
}
