// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ContractExecutableXDR: XDRCodable, Sendable {
  case wasm(HashXDR)
  case token
  case externalRef(ContractExecutableExternalRefXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case ContractExecutableType.wasm.rawValue:
      let val = try container.decode(HashXDR.self)
      self = .wasm(val)
    case ContractExecutableType.stellarAsset.rawValue:
      self = .token
    case ContractExecutableType.externalRef.rawValue:
      let val = try container.decode(ContractExecutableExternalRefXDR.self)
      self = .externalRef(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ContractExecutableXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .wasm: return ContractExecutableType.wasm.rawValue
    case .token: return ContractExecutableType.stellarAsset.rawValue
    case .externalRef: return ContractExecutableType.externalRef.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .wasm(let val):
      try container.encode(val)
    case .token:
      break
    case .externalRef(let val):
      try container.encode(val)
    }
  }
}

extension ContractExecutableXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    switch self {
    case .wasm(let val):
      lines.append("\(prefix).type: CONTRACT_EXECUTABLE_WASM")
      lines.append("\(prefix).wasm_hash: \(TxRepHelper.bytesToHex(val.wrapped))")
    case .token:
      lines.append("\(prefix).type: CONTRACT_EXECUTABLE_STELLAR_ASSET")
    case .externalRef(let val):
      lines.append("\(prefix).type: CONTRACT_EXECUTABLE_EXTERNAL_REF")
      try val.toTxRep(prefix: "\(prefix).external_ref", lines: &lines)
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> ContractExecutableXDR {
    let discKey = "\(prefix).type"
    guard let discName = TxRepHelper.getValue(map, discKey) else {
      throw TxRepError.missingValue(key: discKey)
    }
    switch discName {
    case "CONTRACT_EXECUTABLE_WASM":
      let val = try TxRepHelper.requireWrappedData32(map, "\(prefix).wasm_hash")
      return .wasm(val)
    case "CONTRACT_EXECUTABLE_STELLAR_ASSET":
      return .token
    case "CONTRACT_EXECUTABLE_EXTERNAL_REF":
      let val = try ContractExecutableExternalRefXDR.fromTxRep(map, prefix: "\(prefix).external_ref")
      return .externalRef(val)
    default:
      throw TxRepError.invalidValue(key: discKey)
    }
  }
}
