// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ContractIDPreimageXDR: XDRCodable, Sendable {
  case fromAddress(ContractIDPreimageFromAddressXDR)
  case fromAsset(AssetXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case ContractIDPreimageType.fromAddress.rawValue:
      let val = try container.decode(ContractIDPreimageFromAddressXDR.self)
      self = .fromAddress(val)
    case ContractIDPreimageType.fromAsset.rawValue:
      let val = try container.decode(AssetXDR.self)
      self = .fromAsset(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ContractIDPreimageXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .fromAddress: return ContractIDPreimageType.fromAddress.rawValue
    case .fromAsset: return ContractIDPreimageType.fromAsset.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .fromAddress(let val):
      try container.encode(val)
    case .fromAsset(let val):
      try container.encode(val)
    }
  }
}
