// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum CreateClaimableBalanceResultCode: Int32, XDRCodable, Equatable, Sendable {
  case success = 0
  case malformed = -1
  case lowReserve = -2
  case noTrust = -3
  case notAuthorized = -4
  case underfunded = -5
}
