// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum CreateClaimableBalanceResultXDR: XDRCodable, Sendable {
  case balanceID(ClaimableBalanceIDXDR)
  case malformed
  case lowReserve
  case noTrust
  case notAuthorized
  case underfunded

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case CreateClaimableBalanceResultCode.success.rawValue:
      let val = try container.decode(ClaimableBalanceIDXDR.self)
      self = .balanceID(val)
    case CreateClaimableBalanceResultCode.malformed.rawValue:
      self = .malformed
    case CreateClaimableBalanceResultCode.lowReserve.rawValue:
      self = .lowReserve
    case CreateClaimableBalanceResultCode.noTrust.rawValue:
      self = .noTrust
    case CreateClaimableBalanceResultCode.notAuthorized.rawValue:
      self = .notAuthorized
    case CreateClaimableBalanceResultCode.underfunded.rawValue:
      self = .underfunded
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown CreateClaimableBalanceResultXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .balanceID: return CreateClaimableBalanceResultCode.success.rawValue
    case .malformed: return CreateClaimableBalanceResultCode.malformed.rawValue
    case .lowReserve: return CreateClaimableBalanceResultCode.lowReserve.rawValue
    case .noTrust: return CreateClaimableBalanceResultCode.noTrust.rawValue
    case .notAuthorized: return CreateClaimableBalanceResultCode.notAuthorized.rawValue
    case .underfunded: return CreateClaimableBalanceResultCode.underfunded.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .balanceID(let val):
      try container.encode(val)
    case .malformed:
      break
    case .lowReserve:
      break
    case .noTrust:
      break
    case .notAuthorized:
      break
    case .underfunded:
      break
    }
  }
}
