// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct Curve25519PublicXDR: XDRCodable, Sendable {
  public var key: WrappedData32

  public init(key: WrappedData32) {
    self.key = key
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    key = try container.decode(WrappedData32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(key)
  }
}

extension Curve25519PublicXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "key", value: try XdrJson.hex(self.key.wrapped, expectedLength: 32, type: "Curve25519PublicXDR", key: "key")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> Curve25519PublicXDR {
    let members = try XdrJson.object(value, type: "Curve25519PublicXDR", keys: ["key"])
    let key: WrappedData32 = WrappedData32(try XdrJson.hex(try XdrJson.field(members, key: "key", type: "Curve25519PublicXDR"), expectedLength: 32, type: "Curve25519PublicXDR", key: "key"))
    return Curve25519PublicXDR(key: key)
  }
}
