// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct DecoratedSignatureXDR: XDRCodable, Sendable {
  public let hint: SignatureHintXDR
  public let signature: SignatureXDR

  public init(hint: SignatureHintXDR, signature: SignatureXDR) {
    self.hint = hint
    self.signature = signature
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    hint = try container.decode(SignatureHintXDR.self)
    signature = try container.decode(SignatureXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(hint)
    try container.encode(signature)
  }
}

extension DecoratedSignatureXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).hint: \(TxRepHelper.bytesToHex(self.hint.wrapped))")
    lines.append("\(prefix).signature: \(TxRepHelper.bytesToHex(self.signature))")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> DecoratedSignatureXDR {
    let hint: SignatureHintXDR = try TxRepHelper.requireWrappedData4(map, "\(prefix).hint")
    let signature: SignatureXDR = try TxRepHelper.requireHex(map, "\(prefix).signature")
    return DecoratedSignatureXDR(hint: hint, signature: signature)
  }
}
