// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct DiagnosticEventXDR: XDRCodable, Sendable {
  public let inSuccessfulContractCall: Bool
  public let event: ContractEventXDR

  public init(inSuccessfulContractCall: Bool, event: ContractEventXDR) {
    self.inSuccessfulContractCall = inSuccessfulContractCall
    self.event = event
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    inSuccessfulContractCall = try container.decode(Bool.self)
    event = try container.decode(ContractEventXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(inSuccessfulContractCall)
    try container.encode(event)
  }
}
