// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct DiagnosticEventXDR: XDRCodable, Sendable {
  public let inSuccessfulContractCall: Bool
  public let event: ContractEventXDR

  public init(inSuccessfulContractCall: Bool, event: ContractEventXDR) {
    self.inSuccessfulContractCall = inSuccessfulContractCall
    self.event = event
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    inSuccessfulContractCall = try container.decode(Bool.self)
    event = try container.decode(ContractEventXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(inSuccessfulContractCall)
    try container.encode(event)
  }
}

extension DiagnosticEventXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "in_successful_contract_call", value: XdrJson.bool(self.inSuccessfulContractCall)))
    members.append(XdrJsonMember(key: "event", value: try self.event.toXdrJsonValue()))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> DiagnosticEventXDR {
    let members = try XdrJson.object(value, type: "DiagnosticEventXDR", keys: ["in_successful_contract_call", "event"])
    let inSuccessfulContractCall: Bool = try XdrJson.bool(try XdrJson.field(members, key: "in_successful_contract_call", type: "DiagnosticEventXDR"), type: "DiagnosticEventXDR", key: "in_successful_contract_call")
    let event: ContractEventXDR = try ContractEventXDR.fromXdrJsonValue(try XdrJson.field(members, key: "event", type: "DiagnosticEventXDR"))
    return DiagnosticEventXDR(inSuccessfulContractCall: inSuccessfulContractCall, event: event)
  }
}
