// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct DontHaveXDR: XDRCodable, Sendable {
  public var type: MessageTypeXDR
  public var reqHash: WrappedData32

  public init(type: MessageTypeXDR, reqHash: WrappedData32) {
    self.type = type
    self.reqHash = reqHash
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    type = try container.decode(MessageTypeXDR.self)
    reqHash = try container.decode(WrappedData32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type)
    try container.encode(reqHash)
  }
}
