// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ErrorXDR: XDRCodable, Sendable {
  public var code: ErrorCodeXDR
  public var msg: String

  public init(code: ErrorCodeXDR, msg: String) {
    self.code = code
    self.msg = msg
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    code = try container.decode(ErrorCodeXDR.self)
    msg = try container.decode(String.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(code)
    try container.encode(msg)
  }
}

extension ErrorXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "code", value: try self.code.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "msg", value: XdrJson.escapedString(self.msg)))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> ErrorXDR {
    let members = try XdrJson.object(value, type: "ErrorXDR", keys: ["code", "msg"])
    let code: ErrorCodeXDR = try ErrorCodeXDR.fromXdrJsonValue(try XdrJson.field(members, key: "code", type: "ErrorXDR"))
    let msg: String = try XdrJson.unescapedText(try XdrJson.field(members, key: "msg", type: "ErrorXDR"), type: "ErrorXDR", key: "msg")
    return ErrorXDR(code: code, msg: msg)
  }
}
