// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ExtendFootprintTTLResultCode: Int32, XDRCodable, Equatable, Sendable {
  case success = 0
  case malformed = -1
  case resourceLimitExceeded = -2
  case insufficientRefundableFee = -3
}
