// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct FloodDemandXDR: XDRCodable, Sendable {
  public var txHashes: TxDemandVectorXDR

  public init(txHashes: TxDemandVectorXDR) {
    self.txHashes = txHashes
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    txHashes = try container.decode(TxDemandVectorXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(txHashes)
  }
}
