// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct FreezeBypassTxsXDR: XDRCodable, Sendable {
  public var txHashes: [HashXDR]

  public init(txHashes: [HashXDR]) {
    self.txHashes = txHashes
  }

  public init(from decoder: Decoder) throws {
    txHashes = try decodeArray(type: HashXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(txHashes)
  }
}

extension FreezeBypassTxsXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "tx_hashes", value: try XdrJson.array(self.txHashes.map { element in try HashXDRJsonCodec.toXdrJsonValue(element, type: "FreezeBypassTxsXDR", key: "tx_hashes") })))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> FreezeBypassTxsXDR {
    let members = try XdrJson.object(value, type: "FreezeBypassTxsXDR", keys: ["tx_hashes"])
    let txHashesElements = try XdrJson.array(try XdrJson.field(members, key: "tx_hashes", type: "FreezeBypassTxsXDR"), type: "FreezeBypassTxsXDR", key: "tx_hashes")
    let txHashes: [HashXDR] = try txHashesElements.map { element in try HashXDRJsonCodec.fromXdrJsonValue(element, type: "FreezeBypassTxsXDR", key: "tx_hashes") }
    return FreezeBypassTxsXDR(txHashes: txHashes)
  }
}
