// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum GeneralizedTransactionSetXDR: XDRCodable, Sendable {
  case v1TxSet(TransactionSetV1XDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case 1:
      let val = try container.decode(TransactionSetV1XDR.self)
      self = .v1TxSet(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown GeneralizedTransactionSetXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .v1TxSet: return 1
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .v1TxSet(let val):
      try container.encode(val)
    }
  }
}
