// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct HashIDPreimageContractIDXDR: XDRCodable, Sendable {
  public var networkID: HashXDR
  public var contractIDPreimage: ContractIDPreimageXDR

  public init(networkID: HashXDR, contractIDPreimage: ContractIDPreimageXDR) {
    self.networkID = networkID
    self.contractIDPreimage = contractIDPreimage
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    networkID = try container.decode(HashXDR.self)
    contractIDPreimage = try container.decode(ContractIDPreimageXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(networkID)
    try container.encode(contractIDPreimage)
  }
}
