// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum HashIDPreimageXDR: XDRCodable, Sendable {
  case operationId(OperationID)
  case revokeId(RevokeID)
  case contractID(HashIDPreimageContractIDXDR)
  case sorobanAuthorization(HashIDPreimageSorobanAuthorizationXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case EnvelopeType.opId.rawValue:
      let val = try container.decode(OperationID.self)
      self = .operationId(val)
    case EnvelopeType.poolRevokeOpId.rawValue:
      let val = try container.decode(RevokeID.self)
      self = .revokeId(val)
    case EnvelopeType.contractId.rawValue:
      let val = try container.decode(HashIDPreimageContractIDXDR.self)
      self = .contractID(val)
    case EnvelopeType.sorobanAuthorization.rawValue:
      let val = try container.decode(HashIDPreimageSorobanAuthorizationXDR.self)
      self = .sorobanAuthorization(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown HashIDPreimageXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .operationId: return EnvelopeType.opId.rawValue
    case .revokeId: return EnvelopeType.poolRevokeOpId.rawValue
    case .contractID: return EnvelopeType.contractId.rawValue
    case .sorobanAuthorization: return EnvelopeType.sorobanAuthorization.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .operationId(let val):
      try container.encode(val)
    case .revokeId(let val):
      try container.encode(val)
    case .contractID(let val):
      try container.encode(val)
    case .sorobanAuthorization(let val):
      try container.encode(val)
    }
  }
}
