// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct HashIDPreimageSorobanAuthorizationXDR: XDRCodable, Sendable {
  public var networkID: HashXDR
  public var nonce: Int64
  public var signatureExpirationLedger: UInt32
  public var invocation: SorobanAuthorizedInvocationXDR

  public init(
    networkID: HashXDR,
    nonce: Int64,
    signatureExpirationLedger: UInt32,
    invocation: SorobanAuthorizedInvocationXDR
  ) {
    self.networkID = networkID
    self.nonce = nonce
    self.signatureExpirationLedger = signatureExpirationLedger
    self.invocation = invocation
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    networkID = try container.decode(HashXDR.self)
    nonce = try container.decode(Int64.self)
    signatureExpirationLedger = try container.decode(UInt32.self)
    invocation = try container.decode(SorobanAuthorizedInvocationXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(networkID)
    try container.encode(nonce)
    try container.encode(signatureExpirationLedger)
    try container.encode(invocation)
  }
}
