// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum HotArchiveBucketEntryXDR: XDRCodable, Sendable {
  case archivedEntry(LedgerEntryXDR)
  case key(LedgerKeyXDR)
  case metaEntry(BucketMetadataXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case HotArchiveBucketEntryTypeXDR.archived.rawValue:
      let val = try container.decode(LedgerEntryXDR.self)
      self = .archivedEntry(val)
    case HotArchiveBucketEntryTypeXDR.live.rawValue:
      let val = try container.decode(LedgerKeyXDR.self)
      self = .key(val)
    case HotArchiveBucketEntryTypeXDR.metaentry.rawValue:
      let val = try container.decode(BucketMetadataXDR.self)
      self = .metaEntry(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown HotArchiveBucketEntryXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .archivedEntry: return HotArchiveBucketEntryTypeXDR.archived.rawValue
    case .key: return HotArchiveBucketEntryTypeXDR.live.rawValue
    case .metaEntry: return HotArchiveBucketEntryTypeXDR.metaentry.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .archivedEntry(let val):
      try container.encode(val)
    case .key(let val):
      try container.encode(val)
    case .metaEntry(let val):
      try container.encode(val)
    }
  }
}
