// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum InflationResultCode: Int32, XDRCodable, Equatable, Sendable {
  case success = 0
  case notTime = -1
}
