// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct InnerTransactionResultPair: XDRCodable, Sendable {
  public var hash: HashXDR
  public var result: InnerTransactionResultXDR

  public init(hash: HashXDR, result: InnerTransactionResultXDR) {
    self.hash = hash
    self.result = result
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    hash = try container.decode(HashXDR.self)
    result = try container.decode(InnerTransactionResultXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(hash)
    try container.encode(result)
  }
}

extension InnerTransactionResultPair: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "transaction_hash", value: try HashXDRJsonCodec.toXdrJsonValue(self.hash, type: "InnerTransactionResultPair", key: "transaction_hash")))
    members.append(XdrJsonMember(key: "result", value: try self.result.toXdrJsonValue()))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> InnerTransactionResultPair {
    let members = try XdrJson.object(value, type: "InnerTransactionResultPair", keys: ["transaction_hash", "result"])
    let hash: HashXDR = try HashXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "transaction_hash", type: "InnerTransactionResultPair"), type: "InnerTransactionResultPair", key: "transaction_hash")
    let result: InnerTransactionResultXDR = try InnerTransactionResultXDR.fromXdrJsonValue(try XdrJson.field(members, key: "result", type: "InnerTransactionResultPair"))
    return InnerTransactionResultPair(hash: hash, result: result)
  }
}
