// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct InvokeHostFunctionOpXDR: XDRCodable, Sendable {
  public var hostFunction: HostFunctionXDR
  public var auth: [SorobanAuthorizationEntryXDR]

  public init(hostFunction: HostFunctionXDR, auth: [SorobanAuthorizationEntryXDR]) {
    self.hostFunction = hostFunction
    self.auth = auth
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    hostFunction = try container.decode(HostFunctionXDR.self)
    auth = try decodeArray(type: SorobanAuthorizationEntryXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(hostFunction)
    try container.encode(auth)
  }
}
