// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LedgerKeyLiquidityPoolXDR: XDRCodable, Sendable {
  public var liquidityPoolID: WrappedData32

  public init(liquidityPoolID: WrappedData32) {
    self.liquidityPoolID = liquidityPoolID
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    liquidityPoolID = try container.decode(WrappedData32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(liquidityPoolID)
  }
}

extension LedgerKeyLiquidityPoolXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).liquidityPoolID: \(TxRepHelper.bytesToHex(self.liquidityPoolID.wrapped))")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> LedgerKeyLiquidityPoolXDR {
    let liquidityPoolID: WrappedData32 = try TxRepHelper.requireLiquidityPoolId(map, "\(prefix).liquidityPoolID")
    return LedgerKeyLiquidityPoolXDR(liquidityPoolID: liquidityPoolID)
  }
}

extension LedgerKeyLiquidityPoolXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "liquidity_pool_id", value: try PoolIDXDRJsonCodec.toXdrJsonValue(self.liquidityPoolID, type: "LedgerKeyLiquidityPoolXDR", key: "liquidity_pool_id")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> LedgerKeyLiquidityPoolXDR {
    let members = try XdrJson.object(value, type: "LedgerKeyLiquidityPoolXDR", keys: ["liquidity_pool_id"])
    let liquidityPoolID: WrappedData32 = try PoolIDXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "liquidity_pool_id", type: "LedgerKeyLiquidityPoolXDR"), type: "LedgerKeyLiquidityPoolXDR", key: "liquidity_pool_id")
    return LedgerKeyLiquidityPoolXDR(liquidityPoolID: liquidityPoolID)
  }
}
