// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LedgerKeyClaimableBalanceXDR: XDRCodable, Sendable {
  public var balanceID: ClaimableBalanceIDXDR

  public init(balanceID: ClaimableBalanceIDXDR) {
    self.balanceID = balanceID
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    balanceID = try container.decode(ClaimableBalanceIDXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(balanceID)
  }
}
