// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LedgerCloseValueSignatureXDR: XDRCodable, Sendable {
  public var nodeID: NodeIDXDR
  public var signature: SignatureXDR

  public init(nodeID: NodeIDXDR, signature: SignatureXDR) {
    self.nodeID = nodeID
    self.signature = signature
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    nodeID = try container.decode(NodeIDXDR.self)
    signature = try container.decode(SignatureXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(nodeID)
    try container.encode(signature)
  }
}

extension LedgerCloseValueSignatureXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "node_id", value: try NodeIDXDRJsonCodec.toXdrJsonValue(self.nodeID, type: "LedgerCloseValueSignatureXDR", key: "node_id")))
    members.append(XdrJsonMember(key: "signature", value: try SignatureXDRJsonCodec.toXdrJsonValue(self.signature, type: "LedgerCloseValueSignatureXDR", key: "signature")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> LedgerCloseValueSignatureXDR {
    let members = try XdrJson.object(value, type: "LedgerCloseValueSignatureXDR", keys: ["node_id", "signature"])
    let nodeID: NodeIDXDR = try NodeIDXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "node_id", type: "LedgerCloseValueSignatureXDR"), type: "LedgerCloseValueSignatureXDR", key: "node_id")
    let signature: SignatureXDR = try SignatureXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "signature", type: "LedgerCloseValueSignatureXDR"), type: "LedgerCloseValueSignatureXDR", key: "signature")
    return LedgerCloseValueSignatureXDR(nodeID: nodeID, signature: signature)
  }
}
