// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LedgerKeyContractDataXDR: XDRCodable, Sendable {
  public var contract: SCAddressXDR
  public var key: SCValXDR
  public var durability: ContractDataDurability

  public init(
    contract: SCAddressXDR,
    key: SCValXDR,
    durability: ContractDataDurability
  ) {
    self.contract = contract
    self.key = key
    self.durability = durability
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    contract = try container.decode(SCAddressXDR.self)
    key = try container.decode(SCValXDR.self)
    durability = try container.decode(ContractDataDurability.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(contract)
    try container.encode(key)
    try container.encode(durability)
  }
}

extension LedgerKeyContractDataXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    try self.contract.toTxRep(prefix: "\(prefix).contract", lines: &lines)
    try self.key.toTxRep(prefix: "\(prefix).key", lines: &lines)
    try self.durability.toTxRep(prefix: "\(prefix).durability", lines: &lines)
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> LedgerKeyContractDataXDR {
    let contract: SCAddressXDR = try SCAddressXDR.fromTxRep(map, prefix: "\(prefix).contract")
    let key: SCValXDR = try SCValXDR.fromTxRep(map, prefix: "\(prefix).key")
    let durability: ContractDataDurability = try ContractDataDurability.fromTxRep(map, prefix: "\(prefix).durability")
    return LedgerKeyContractDataXDR(contract: contract, key: key, durability: durability)
  }
}

extension LedgerKeyContractDataXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "contract", value: try self.contract.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "key", value: try self.key.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "durability", value: try self.durability.toXdrJsonValue()))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> LedgerKeyContractDataXDR {
    let members = try XdrJson.object(value, type: "LedgerKeyContractDataXDR", keys: ["contract", "key", "durability"])
    let contract: SCAddressXDR = try SCAddressXDR.fromXdrJsonValue(try XdrJson.field(members, key: "contract", type: "LedgerKeyContractDataXDR"))
    let key: SCValXDR = try SCValXDR.fromXdrJsonValue(try XdrJson.field(members, key: "key", type: "LedgerKeyContractDataXDR"))
    let durability: ContractDataDurability = try ContractDataDurability.fromXdrJsonValue(try XdrJson.field(members, key: "durability", type: "LedgerKeyContractDataXDR"))
    return LedgerKeyContractDataXDR(
      contract: contract,
      key: key,
      durability: durability
    )
  }
}
