// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum LedgerEntryType: Int32, XDRCodable, Equatable, Sendable {
  case account = 0
  case trustline = 1
  case offer = 2
  case data = 3
  case claimableBalance = 4
  case liquidityPool = 5
  case contractData = 6
  case contractCode = 7
  case configSetting = 8
  case ttl = 9
}

extension LedgerEntryType {
  public func enumName() -> String {
    switch self {
    case .account: return "ACCOUNT"
    case .trustline: return "TRUSTLINE"
    case .offer: return "OFFER"
    case .data: return "DATA"
    case .claimableBalance: return "CLAIMABLE_BALANCE"
    case .liquidityPool: return "LIQUIDITY_POOL"
    case .contractData: return "CONTRACT_DATA"
    case .contractCode: return "CONTRACT_CODE"
    case .configSetting: return "CONFIG_SETTING"
    case .ttl: return "TTL"
    }
  }

  public static func fromTxRepName(_ name: String) throws -> LedgerEntryType {
    switch name {
    case "ACCOUNT": return .account
    case "TRUSTLINE": return .trustline
    case "OFFER": return .offer
    case "DATA": return .data
    case "CLAIMABLE_BALANCE": return .claimableBalance
    case "LIQUIDITY_POOL": return .liquidityPool
    case "CONTRACT_DATA": return .contractData
    case "CONTRACT_CODE": return .contractCode
    case "CONFIG_SETTING": return .configSetting
    case "TTL": return .ttl
    default:
      let prefix = "LedgerEntryType#"
      if name.hasPrefix(prefix), let v = Int32(name.dropFirst(prefix.count)), let parsed = LedgerEntryType(rawValue: v) {
        return parsed
      }
      throw TxRepError.invalidValue(key: name)
    }
  }

  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix): \(enumName())")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> LedgerEntryType {
    guard let raw = TxRepHelper.getValue(map, prefix) else {
      throw TxRepError.missingValue(key: prefix)
    }
    return try fromTxRepName(raw)
  }
}

extension LedgerEntryType: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .account: return .string("account")
    case .trustline: return .string("trustline")
    case .offer: return .string("offer")
    case .data: return .string("data")
    case .claimableBalance: return .string("claimable_balance")
    case .liquidityPool: return .string("liquidity_pool")
    case .contractData: return .string("contract_data")
    case .contractCode: return .string("contract_code")
    case .configSetting: return .string("config_setting")
    case .ttl: return .string("ttl")
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> LedgerEntryType {
    let name = try XdrJson.string(value, type: "LedgerEntryType")
    switch name {
    case "account": return .account
    case "trustline": return .trustline
    case "offer": return .offer
    case "data": return .data
    case "claimable_balance": return .claimableBalance
    case "liquidity_pool": return .liquidityPool
    case "contract_data": return .contractData
    case "contract_code": return .contractCode
    case "config_setting": return .configSetting
    case "ttl": return .ttl
    default:
      throw XdrJsonError.unknownEnumValue(type: "LedgerEntryType", value: name)
    }
  }
}
