// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LedgerKeyContractCodeXDR: XDRCodable, Sendable {
  public var hash: WrappedData32

  public init(hash: WrappedData32) {
    self.hash = hash
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    hash = try container.decode(WrappedData32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(hash)
  }
}
