// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LedgerKeyTTLXDR: XDRCodable, Sendable {
  public var keyHash: HashXDR

  public init(keyHash: HashXDR) {
    self.keyHash = keyHash
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    keyHash = try container.decode(HashXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(keyHash)
  }
}
