// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LedgerHeaderHistoryEntryXDR: XDRCodable, Sendable {
  public var hash: HashXDR
  public var header: LedgerHeaderXDR
  public var ext: LedgerHeaderHistoryEntryXDRExtXDR

  public init(
    hash: HashXDR,
    header: LedgerHeaderXDR,
    ext: LedgerHeaderHistoryEntryXDRExtXDR
  ) {
    self.hash = hash
    self.header = header
    self.ext = ext
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    hash = try container.decode(HashXDR.self)
    header = try container.decode(LedgerHeaderXDR.self)
    ext = try container.decode(LedgerHeaderHistoryEntryXDRExtXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(hash)
    try container.encode(header)
    try container.encode(ext)
  }
}

extension LedgerHeaderHistoryEntryXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "hash", value: try HashXDRJsonCodec.toXdrJsonValue(self.hash, type: "LedgerHeaderHistoryEntryXDR", key: "hash")))
    members.append(XdrJsonMember(key: "header", value: try self.header.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "ext", value: try self.ext.toXdrJsonValue()))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> LedgerHeaderHistoryEntryXDR {
    let members = try XdrJson.object(value, type: "LedgerHeaderHistoryEntryXDR", keys: ["hash", "header", "ext"])
    let hash: HashXDR = try HashXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "hash", type: "LedgerHeaderHistoryEntryXDR"), type: "LedgerHeaderHistoryEntryXDR", key: "hash")
    let header: LedgerHeaderXDR = try LedgerHeaderXDR.fromXdrJsonValue(try XdrJson.field(members, key: "header", type: "LedgerHeaderHistoryEntryXDR"))
    let ext: LedgerHeaderHistoryEntryXDRExtXDR = try LedgerHeaderHistoryEntryXDRExtXDR.fromXdrJsonValue(try XdrJson.field(members, key: "ext", type: "LedgerHeaderHistoryEntryXDR"))
    return LedgerHeaderHistoryEntryXDR(
      hash: hash,
      header: header,
      ext: ext
    )
  }
}
