// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum LedgerEntryChangeXDR: XDRCodable, Sendable {
  case created(LedgerEntryXDR)
  case updated(LedgerEntryXDR)
  case removed(LedgerKeyXDR)
  case state(LedgerEntryXDR)
  case restored(LedgerEntryXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case LedgerEntryChangeType.ledgerEntryCreated.rawValue:
      let val = try container.decode(LedgerEntryXDR.self)
      self = .created(val)
    case LedgerEntryChangeType.ledgerEntryUpdated.rawValue:
      let val = try container.decode(LedgerEntryXDR.self)
      self = .updated(val)
    case LedgerEntryChangeType.ledgerEntryRemoved.rawValue:
      let val = try container.decode(LedgerKeyXDR.self)
      self = .removed(val)
    case LedgerEntryChangeType.ledgerEntryState.rawValue:
      let val = try container.decode(LedgerEntryXDR.self)
      self = .state(val)
    case LedgerEntryChangeType.ledgerEntryRestore.rawValue:
      let val = try container.decode(LedgerEntryXDR.self)
      self = .restored(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown LedgerEntryChangeXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .created: return LedgerEntryChangeType.ledgerEntryCreated.rawValue
    case .updated: return LedgerEntryChangeType.ledgerEntryUpdated.rawValue
    case .removed: return LedgerEntryChangeType.ledgerEntryRemoved.rawValue
    case .state: return LedgerEntryChangeType.ledgerEntryState.rawValue
    case .restored: return LedgerEntryChangeType.ledgerEntryRestore.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .created(let val):
      try container.encode(val)
    case .updated(let val):
      try container.encode(val)
    case .removed(let val):
      try container.encode(val)
    case .state(let val):
      try container.encode(val)
    case .restored(let val):
      try container.encode(val)
    }
  }
}
