// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum LedgerEntryChangeXDR: XDRCodable, Sendable {
  case created(LedgerEntryXDR)
  case updated(LedgerEntryXDR)
  case removed(LedgerKeyXDR)
  case state(LedgerEntryXDR)
  case restored(LedgerEntryXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case LedgerEntryChangeType.ledgerEntryCreated.rawValue:
      let val = try container.decode(LedgerEntryXDR.self)
      self = .created(val)
    case LedgerEntryChangeType.ledgerEntryUpdated.rawValue:
      let val = try container.decode(LedgerEntryXDR.self)
      self = .updated(val)
    case LedgerEntryChangeType.ledgerEntryRemoved.rawValue:
      let val = try container.decode(LedgerKeyXDR.self)
      self = .removed(val)
    case LedgerEntryChangeType.ledgerEntryState.rawValue:
      let val = try container.decode(LedgerEntryXDR.self)
      self = .state(val)
    case LedgerEntryChangeType.ledgerEntryRestore.rawValue:
      let val = try container.decode(LedgerEntryXDR.self)
      self = .restored(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown LedgerEntryChangeXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .created: return LedgerEntryChangeType.ledgerEntryCreated.rawValue
    case .updated: return LedgerEntryChangeType.ledgerEntryUpdated.rawValue
    case .removed: return LedgerEntryChangeType.ledgerEntryRemoved.rawValue
    case .state: return LedgerEntryChangeType.ledgerEntryState.rawValue
    case .restored: return LedgerEntryChangeType.ledgerEntryRestore.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .created(let val):
      try container.encode(val)
    case .updated(let val):
      try container.encode(val)
    case .removed(let val):
      try container.encode(val)
    case .state(let val):
      try container.encode(val)
    case .restored(let val):
      try container.encode(val)
    }
  }
}

extension LedgerEntryChangeXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .created(let payload):
      return .object([XdrJsonMember(key: "created", value: try payload.toXdrJsonValue())])
    case .updated(let payload):
      return .object([XdrJsonMember(key: "updated", value: try payload.toXdrJsonValue())])
    case .removed(let payload):
      return .object([XdrJsonMember(key: "removed", value: try payload.toXdrJsonValue())])
    case .state(let payload):
      return .object([XdrJsonMember(key: "state", value: try payload.toXdrJsonValue())])
    case .restored(let payload):
      return .object([XdrJsonMember(key: "restored", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> LedgerEntryChangeXDR {
    if case .string(let name) = value {
      switch name {
      case "created":
        throw XdrJsonError.invalidValue(type: "LedgerEntryChangeXDR", key: "created",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "updated":
        throw XdrJsonError.invalidValue(type: "LedgerEntryChangeXDR", key: "updated",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "removed":
        throw XdrJsonError.invalidValue(type: "LedgerEntryChangeXDR", key: "removed",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "state":
        throw XdrJsonError.invalidValue(type: "LedgerEntryChangeXDR", key: "state",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "restored":
        throw XdrJsonError.invalidValue(type: "LedgerEntryChangeXDR", key: "restored",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "LedgerEntryChangeXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "LedgerEntryChangeXDR")
    switch member.key {
    case "created":
      let created: LedgerEntryXDR = try LedgerEntryXDR.fromXdrJsonValue(member.value)
      return .created(created)
    case "updated":
      let updated: LedgerEntryXDR = try LedgerEntryXDR.fromXdrJsonValue(member.value)
      return .updated(updated)
    case "removed":
      let removed: LedgerKeyXDR = try LedgerKeyXDR.fromXdrJsonValue(member.value)
      return .removed(removed)
    case "state":
      let state: LedgerEntryXDR = try LedgerEntryXDR.fromXdrJsonValue(member.value)
      return .state(state)
    case "restored":
      let restored: LedgerEntryXDR = try LedgerEntryXDR.fromXdrJsonValue(member.value)
      return .restored(restored)
    default:
      throw XdrJsonError.unknownUnionArm(type: "LedgerEntryChangeXDR", key: member.key)
    }
  }
}
