// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum LedgerEntryExtensionV1ExtXDR: XDRCodable, Sendable {
  case void

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case 0:
      self = .void
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown LedgerEntryExtensionV1ExtXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .void: return 0
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .void:
      break
    }
  }
}

extension LedgerEntryExtensionV1ExtXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .void: return .string("v0")
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> LedgerEntryExtensionV1ExtXDR {
    let name = try XdrJson.string(value, type: "LedgerEntryExtensionV1ExtXDR")
    switch name {
    case "v0":
      return .void
    default:
      throw XdrJsonError.unknownUnionArm(type: "LedgerEntryExtensionV1ExtXDR", key: name)
    }
  }
}
