// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LedgerHeaderHistoryEntryXDR: XDRCodable, Sendable {
  public var hash: HashXDR
  public var header: LedgerHeaderXDR
  public var ext: LedgerHeaderHistoryEntryXDRExtXDR

  public init(
    hash: HashXDR,
    header: LedgerHeaderXDR,
    ext: LedgerHeaderHistoryEntryXDRExtXDR
  ) {
    self.hash = hash
    self.header = header
    self.ext = ext
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    hash = try container.decode(HashXDR.self)
    header = try container.decode(LedgerHeaderXDR.self)
    ext = try container.decode(LedgerHeaderHistoryEntryXDRExtXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(hash)
    try container.encode(header)
    try container.encode(ext)
  }
}
