// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LedgerKeyDataXDR: XDRCodable, Sendable {
  public var accountID: PublicKey
  public var dataName: String

  public init(accountID: PublicKey, dataName: String) {
    self.accountID = accountID
    self.dataName = dataName
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    accountID = try container.decode(PublicKey.self)
    dataName = try container.decode(String.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(accountID)
    try container.encode(dataName)
  }
}

extension LedgerKeyDataXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).accountID: \(TxRepHelper.formatAccountId(self.accountID))")
    lines.append("\(prefix).dataName: \(TxRepHelper.escapeString(self.dataName))")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> LedgerKeyDataXDR {
    let accountID: PublicKey = try TxRepHelper.requireAccountId(map, "\(prefix).accountID")
    let dataName: String = try TxRepHelper.requireString(map, "\(prefix).dataName")
    return LedgerKeyDataXDR(accountID: accountID, dataName: dataName)
  }
}

extension LedgerKeyDataXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "account_id", value: try AccountIDXDRJsonCodec.toXdrJsonValue(self.accountID, type: "LedgerKeyDataXDR", key: "account_id")))
    members.append(XdrJsonMember(key: "data_name", value: try String64XDRJsonCodec.toXdrJsonValue(self.dataName, type: "LedgerKeyDataXDR", key: "data_name")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> LedgerKeyDataXDR {
    let members = try XdrJson.object(value, type: "LedgerKeyDataXDR", keys: ["account_id", "data_name"])
    let accountID: PublicKey = try AccountIDXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "account_id", type: "LedgerKeyDataXDR"), type: "LedgerKeyDataXDR", key: "account_id")
    let dataName: String = try String64XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "data_name", type: "LedgerKeyDataXDR"), type: "LedgerKeyDataXDR", key: "data_name")
    return LedgerKeyDataXDR(accountID: accountID, dataName: dataName)
  }
}
