// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LedgerKeyOfferXDR: XDRCodable, Sendable {
  public var sellerID: PublicKey
  public var offerID: Int64

  public init(sellerID: PublicKey, offerID: Int64) {
    self.sellerID = sellerID
    self.offerID = offerID
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    sellerID = try container.decode(PublicKey.self)
    offerID = try container.decode(Int64.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(sellerID)
    try container.encode(offerID)
  }
}

extension LedgerKeyOfferXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).sellerID: \(try TxRepHelper.formatAccountId(self.sellerID))")
    lines.append("\(prefix).offerID: \(self.offerID)")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> LedgerKeyOfferXDR {
    let sellerID: PublicKey = try TxRepHelper.requireAccountId(map, "\(prefix).sellerID")
    let offerID: Int64 = try TxRepHelper.parseInt64(TxRepHelper.getValue(map, "\(prefix).offerID") ?? "0")
    return LedgerKeyOfferXDR(sellerID: sellerID, offerID: offerID)
  }
}
