// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum LiquidityPoolWithdrawResultXDR: XDRCodable, Sendable {
  case success
  case malformed
  case noTrust
  case underfunded
  case lineFull
  case underMinimum

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case LiquidityPoolWithdrawResulCode.success.rawValue:
      self = .success
    case LiquidityPoolWithdrawResulCode.malformed.rawValue:
      self = .malformed
    case LiquidityPoolWithdrawResulCode.noTrust.rawValue:
      self = .noTrust
    case LiquidityPoolWithdrawResulCode.underfunded.rawValue:
      self = .underfunded
    case LiquidityPoolWithdrawResulCode.lineFull.rawValue:
      self = .lineFull
    case LiquidityPoolWithdrawResulCode.underMinimum.rawValue:
      self = .underMinimum
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown LiquidityPoolWithdrawResultXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .success: return LiquidityPoolWithdrawResulCode.success.rawValue
    case .malformed: return LiquidityPoolWithdrawResulCode.malformed.rawValue
    case .noTrust: return LiquidityPoolWithdrawResulCode.noTrust.rawValue
    case .underfunded: return LiquidityPoolWithdrawResulCode.underfunded.rawValue
    case .lineFull: return LiquidityPoolWithdrawResulCode.lineFull.rawValue
    case .underMinimum: return LiquidityPoolWithdrawResulCode.underMinimum.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .success:
      break
    case .malformed:
      break
    case .noTrust:
      break
    case .underfunded:
      break
    case .lineFull:
      break
    case .underMinimum:
      break
    }
  }
}
