// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum LiquidityPoolBodyXDR: XDRCodable, Sendable {
  case constantProduct(ConstantProductXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case LiquidityPoolType.constantProduct.rawValue:
      let val = try container.decode(ConstantProductXDR.self)
      self = .constantProduct(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown LiquidityPoolBodyXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .constantProduct: return LiquidityPoolType.constantProduct.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .constantProduct(let val):
      try container.encode(val)
    }
  }
}

extension LiquidityPoolBodyXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .constantProduct(let payload):
      return .object([XdrJsonMember(key: "liquidity_pool_constant_product", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> LiquidityPoolBodyXDR {
    if case .string(let name) = value {
      switch name {
      case "liquidity_pool_constant_product":
        throw XdrJsonError.invalidValue(type: "LiquidityPoolBodyXDR", key: "liquidity_pool_constant_product",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "LiquidityPoolBodyXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "LiquidityPoolBodyXDR")
    switch member.key {
    case "liquidity_pool_constant_product":
      let constantProduct: ConstantProductXDR = try ConstantProductXDR.fromXdrJsonValue(member.value)
      return .constantProduct(constantProduct)
    default:
      throw XdrJsonError.unknownUnionArm(type: "LiquidityPoolBodyXDR", key: member.key)
    }
  }
}
