// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LiquidityPoolEntryXDR: XDRCodable, Sendable {
  public let liquidityPoolID: WrappedData32
  public let body: LiquidityPoolBodyXDR

  public init(liquidityPoolID: WrappedData32, body: LiquidityPoolBodyXDR) {
    self.liquidityPoolID = liquidityPoolID
    self.body = body
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    liquidityPoolID = try container.decode(WrappedData32.self)
    body = try container.decode(LiquidityPoolBodyXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(liquidityPoolID)
    try container.encode(body)
  }
}

extension LiquidityPoolEntryXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "liquidity_pool_id", value: try PoolIDXDRJsonCodec.toXdrJsonValue(self.liquidityPoolID, type: "LiquidityPoolEntryXDR", key: "liquidity_pool_id")))
    members.append(XdrJsonMember(key: "body", value: try self.body.toXdrJsonValue()))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> LiquidityPoolEntryXDR {
    let members = try XdrJson.object(value, type: "LiquidityPoolEntryXDR", keys: ["liquidity_pool_id", "body"])
    let liquidityPoolID: WrappedData32 = try PoolIDXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "liquidity_pool_id", type: "LiquidityPoolEntryXDR"), type: "LiquidityPoolEntryXDR", key: "liquidity_pool_id")
    let body: LiquidityPoolBodyXDR = try LiquidityPoolBodyXDR.fromXdrJsonValue(try XdrJson.field(members, key: "body", type: "LiquidityPoolEntryXDR"))
    return LiquidityPoolEntryXDR(liquidityPoolID: liquidityPoolID, body: body)
  }
}
