// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct LiquidityPoolConstantProductParametersXDR: XDRCodable, Sendable {
  public let assetA: AssetXDR
  public let assetB: AssetXDR
  public let fee: Int32

  public init(
    assetA: AssetXDR,
    assetB: AssetXDR,
    fee: Int32
  ) {
    self.assetA = assetA
    self.assetB = assetB
    self.fee = fee
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    assetA = try container.decode(AssetXDR.self)
    assetB = try container.decode(AssetXDR.self)
    fee = try container.decode(Int32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(assetA)
    try container.encode(assetB)
    try container.encode(fee)
  }
}

extension LiquidityPoolConstantProductParametersXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).assetA: \(try TxRepHelper.formatAsset(self.assetA))")
    lines.append("\(prefix).assetB: \(try TxRepHelper.formatAsset(self.assetB))")
    lines.append("\(prefix).fee: \(self.fee)")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> LiquidityPoolConstantProductParametersXDR {
    let assetA: AssetXDR = try TxRepHelper.requireAsset(map, "\(prefix).assetA")
    let assetB: AssetXDR = try TxRepHelper.requireAsset(map, "\(prefix).assetB")
    let fee: Int32 = try TxRepHelper.parseInt(TxRepHelper.getValue(map, "\(prefix).fee") ?? "0")
    return LiquidityPoolConstantProductParametersXDR(assetA: assetA, assetB: assetB, fee: fee)
  }
}
