// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ManageOfferResultXDR: XDRCodable, Sendable {
  case success(ManageOfferSuccessResultXDR)
  case malformed
  case sellNoTrust
  case buyNoTrust
  case sellNotAuthorized
  case buyNotAuthorized
  case lineFull
  case underfunded
  case crossSelf
  case sellNoIssuer
  case buyNoIssuer
  case notFound
  case lowReserve

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case ManageOfferResultCode.success.rawValue:
      let val = try container.decode(ManageOfferSuccessResultXDR.self)
      self = .success(val)
    case ManageOfferResultCode.malformed.rawValue:
      self = .malformed
    case ManageOfferResultCode.sellNoTrust.rawValue:
      self = .sellNoTrust
    case ManageOfferResultCode.buyNoTrust.rawValue:
      self = .buyNoTrust
    case ManageOfferResultCode.sellNotAuthorized.rawValue:
      self = .sellNotAuthorized
    case ManageOfferResultCode.buyNotAuthorized.rawValue:
      self = .buyNotAuthorized
    case ManageOfferResultCode.lineFull.rawValue:
      self = .lineFull
    case ManageOfferResultCode.underfunded.rawValue:
      self = .underfunded
    case ManageOfferResultCode.crossSelf.rawValue:
      self = .crossSelf
    case ManageOfferResultCode.sellNoIssuer.rawValue:
      self = .sellNoIssuer
    case ManageOfferResultCode.buyNoIssuer.rawValue:
      self = .buyNoIssuer
    case ManageOfferResultCode.notFound.rawValue:
      self = .notFound
    case ManageOfferResultCode.lowReserve.rawValue:
      self = .lowReserve
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ManageOfferResultXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .success: return ManageOfferResultCode.success.rawValue
    case .malformed: return ManageOfferResultCode.malformed.rawValue
    case .sellNoTrust: return ManageOfferResultCode.sellNoTrust.rawValue
    case .buyNoTrust: return ManageOfferResultCode.buyNoTrust.rawValue
    case .sellNotAuthorized: return ManageOfferResultCode.sellNotAuthorized.rawValue
    case .buyNotAuthorized: return ManageOfferResultCode.buyNotAuthorized.rawValue
    case .lineFull: return ManageOfferResultCode.lineFull.rawValue
    case .underfunded: return ManageOfferResultCode.underfunded.rawValue
    case .crossSelf: return ManageOfferResultCode.crossSelf.rawValue
    case .sellNoIssuer: return ManageOfferResultCode.sellNoIssuer.rawValue
    case .buyNoIssuer: return ManageOfferResultCode.buyNoIssuer.rawValue
    case .notFound: return ManageOfferResultCode.notFound.rawValue
    case .lowReserve: return ManageOfferResultCode.lowReserve.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .success(let val):
      try container.encode(val)
    case .malformed:
      break
    case .sellNoTrust:
      break
    case .buyNoTrust:
      break
    case .sellNotAuthorized:
      break
    case .buyNotAuthorized:
      break
    case .lineFull:
      break
    case .underfunded:
      break
    case .crossSelf:
      break
    case .sellNoIssuer:
      break
    case .buyNoIssuer:
      break
    case .notFound:
      break
    case .lowReserve:
      break
    }
  }
}
