// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum ManageDataResultXDR: XDRCodable, Sendable {
  case success
  case notSupportedYet
  case nameNotFound
  case lowReserve
  case invalidName

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case ManageDataResultCode.success.rawValue:
      self = .success
    case ManageDataResultCode.notSupportedYet.rawValue:
      self = .notSupportedYet
    case ManageDataResultCode.nameNotFound.rawValue:
      self = .nameNotFound
    case ManageDataResultCode.lowReserve.rawValue:
      self = .lowReserve
    case ManageDataResultCode.invalidName.rawValue:
      self = .invalidName
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown ManageDataResultXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .success: return ManageDataResultCode.success.rawValue
    case .notSupportedYet: return ManageDataResultCode.notSupportedYet.rawValue
    case .nameNotFound: return ManageDataResultCode.nameNotFound.rawValue
    case .lowReserve: return ManageDataResultCode.lowReserve.rawValue
    case .invalidName: return ManageDataResultCode.invalidName.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .success:
      break
    case .notSupportedYet:
      break
    case .nameNotFound:
      break
    case .lowReserve:
      break
    case .invalidName:
      break
    }
  }
}
