// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ManageOfferOperationXDR: XDRCodable, Sendable {
  public let selling: AssetXDR
  public let buying: AssetXDR
  public let amount: Int64
  public let price: PriceXDR
  public let offerID: Int64

  public init(
    selling: AssetXDR,
    buying: AssetXDR,
    amount: Int64,
    price: PriceXDR,
    offerID: Int64
  ) {
    self.selling = selling
    self.buying = buying
    self.amount = amount
    self.price = price
    self.offerID = offerID
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    selling = try container.decode(AssetXDR.self)
    buying = try container.decode(AssetXDR.self)
    amount = try container.decode(Int64.self)
    price = try container.decode(PriceXDR.self)
    offerID = try container.decode(Int64.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(selling)
    try container.encode(buying)
    try container.encode(amount)
    try container.encode(price)
    try container.encode(offerID)
  }
}

extension ManageOfferOperationXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).selling: \(TxRepHelper.formatAsset(self.selling))")
    lines.append("\(prefix).buying: \(TxRepHelper.formatAsset(self.buying))")
    lines.append("\(prefix).amount: \(self.amount)")
    try self.price.toTxRep(prefix: "\(prefix).price", lines: &lines)
    lines.append("\(prefix).offerID: \(self.offerID)")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> ManageOfferOperationXDR {
    let selling: AssetXDR = try TxRepHelper.requireAsset(map, "\(prefix).selling")
    let buying: AssetXDR = try TxRepHelper.requireAsset(map, "\(prefix).buying")
    let amount: Int64 = try TxRepHelper.parseInt64(TxRepHelper.getValue(map, "\(prefix).amount") ?? "0")
    let price: PriceXDR = try PriceXDR.fromTxRep(map, prefix: "\(prefix).price")
    let offerID: Int64 = try TxRepHelper.parseInt64(TxRepHelper.getValue(map, "\(prefix).offerID") ?? "0")
    return ManageOfferOperationXDR(selling: selling, buying: buying, amount: amount, price: price, offerID: offerID)
  }
}

// ManageOfferOperationXDR is the Swift form of both ManageSellOfferOp and ManageBuyOfferOp.
// SEP-0051 renders them under different names, so no single rendering is correct for
// this type and it carries no XDR-JSON members. The conversions live on
// the union arm that selects each of them, under that definition's own names.
