// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ManageDataOperationXDR: XDRCodable, Sendable {
  public let dataName: String
  public let dataValue: DataValueXDR?

  public init(dataName: String, dataValue: DataValueXDR? = nil) {
    self.dataName = dataName
    self.dataValue = dataValue
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    dataName = try container.decode(String.self)
    let dataValuePresent = try container.decode(Int32.self)
    if dataValuePresent != 0 {
      dataValue = try container.decode(DataValueXDR.self)
    } else {
      dataValue = nil
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(dataName)
    if let val = dataValue {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
  }
}

extension ManageDataOperationXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).dataName: \(TxRepHelper.escapeString(self.dataName))")
    if let val = self.dataValue {
      lines.append("\(prefix).dataValue._present: true")
      lines.append("\(prefix).dataValue: \(TxRepHelper.bytesToHex(val))")
    } else {
      lines.append("\(prefix).dataValue._present: false")
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> ManageDataOperationXDR {
    let dataName: String = try TxRepHelper.requireString(map, "\(prefix).dataName")
    let dataValue: DataValueXDR?
    if TxRepHelper.getValue(map, "\(prefix).dataValue._present") == "true" {
      dataValue = try TxRepHelper.hexToBytes(TxRepHelper.getValue(map, "\(prefix).dataValue") ?? "")
    } else {
      dataValue = nil
    }
    return ManageDataOperationXDR(dataName: dataName, dataValue: dataValue)
  }
}
