// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct MuxedAccountXDRMed25519XDR: XDRCodable, Sendable {
  public var id: UInt64
  public var ed25519: Uint256XDR

  public init(id: UInt64, ed25519: Uint256XDR) {
    self.id = id
    self.ed25519 = ed25519
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    id = try container.decode(UInt64.self)
    ed25519 = try container.decode(Uint256XDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(id)
    try container.encode(ed25519)
  }
}

extension MuxedAccountXDRMed25519XDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    guard self.ed25519.wrapped.count == 32 else {
      throw XdrJsonError.invalidValue(
        type: "MuxedAccountXDRMed25519XDR", key: "ed25519",
        message: "expected 32 bytes, got \(self.ed25519.wrapped.count)")
    }
    let inverted = MuxedAccountMed25519XDRInverted(
      id: self.id, sourceAccountEd25519: [UInt8](self.ed25519.wrapped))
    let encoded = Data(try XDREncoder.encode(inverted))
    return .string(try XdrJson.strKey(encoded, expectedLength: 40,
                                      type: "MuxedAccountXDRMed25519XDR", key: nil) { try $0.encodeMEd25519AccountId() })
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> MuxedAccountXDRMed25519XDR {
    let text = try XdrJson.string(value, type: "MuxedAccountXDRMed25519XDR")
    let raw = try XdrJson.strKeyBytes(text, expectedLength: 40,
                                      type: "MuxedAccountXDRMed25519XDR", key: nil) { try $0.decodeMed25519PublicKey() }
    let inverted = try XDRDecoder.decode(MuxedAccountMed25519XDRInverted.self, data: [UInt8](raw))
    return MuxedAccountXDRMed25519XDR(
      id: inverted.id, ed25519: Uint256XDR(Data(inverted.sourceAccountEd25519)))
  }
}
