// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct MuxedContractXDR: XDRCodable, Sendable {
  public var id: UInt64
  public var contractId: WrappedData32

  public init(id: UInt64, contractId: WrappedData32) {
    self.id = id
    self.contractId = contractId
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    id = try container.decode(UInt64.self)
    contractId = try container.decode(WrappedData32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(id)
    try container.encode(contractId)
  }
}

extension MuxedContractXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    return .string(try XdrJson.strKey(self.strKeyPayload, expectedLength: 40,
                                      type: "MuxedContractXDR", key: nil) { try $0.encodeMuxedContractId() })
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> MuxedContractXDR {
    let text = try XdrJson.string(value, type: "MuxedContractXDR")
    return MuxedContractXDR(strKeyPayload: try XdrJson.strKeyBytes(text, expectedLength: 40,
                                                                   type: "MuxedContractXDR", key: nil) { try $0.decodeMuxedContractId() })
  }
}
