// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum OperationResultXDR: XDRCodable, Sendable {
  case tr(OperationResultXDRTrXDR)
  case badAuth
  case noAccount
  case notSupported
  case tooManySubentries
  case exceededWorkLimit
  case tooManySponsoring

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case OperationResultCode.inner.rawValue:
      let val = try container.decode(OperationResultXDRTrXDR.self)
      self = .tr(val)
    case OperationResultCode.badAuth.rawValue:
      self = .badAuth
    case OperationResultCode.noAccount.rawValue:
      self = .noAccount
    case OperationResultCode.notSupported.rawValue:
      self = .notSupported
    case OperationResultCode.tooManySubentries.rawValue:
      self = .tooManySubentries
    case OperationResultCode.exceededWorkLimit.rawValue:
      self = .exceededWorkLimit
    case OperationResultCode.tooManySponsoring.rawValue:
      self = .tooManySponsoring
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown OperationResultXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .tr: return OperationResultCode.inner.rawValue
    case .badAuth: return OperationResultCode.badAuth.rawValue
    case .noAccount: return OperationResultCode.noAccount.rawValue
    case .notSupported: return OperationResultCode.notSupported.rawValue
    case .tooManySubentries: return OperationResultCode.tooManySubentries.rawValue
    case .exceededWorkLimit: return OperationResultCode.exceededWorkLimit.rawValue
    case .tooManySponsoring: return OperationResultCode.tooManySponsoring.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .tr(let val):
      try container.encode(val)
    case .badAuth:
      break
    case .noAccount:
      break
    case .notSupported:
      break
    case .tooManySubentries:
      break
    case .exceededWorkLimit:
      break
    case .tooManySponsoring:
      break
    }
  }
}
