// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct OperationID: XDRCodable, Sendable {
  public var sourceAccount: PublicKey
  public var seqNum: Int64
  public var opNum: UInt32

  public init(
    sourceAccount: PublicKey,
    seqNum: Int64,
    opNum: UInt32
  ) {
    self.sourceAccount = sourceAccount
    self.seqNum = seqNum
    self.opNum = opNum
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    sourceAccount = try container.decode(PublicKey.self)
    seqNum = try container.decode(Int64.self)
    opNum = try container.decode(UInt32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(sourceAccount)
    try container.encode(seqNum)
    try container.encode(opNum)
  }
}

extension OperationID: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "source_account", value: try AccountIDXDRJsonCodec.toXdrJsonValue(self.sourceAccount, type: "OperationID", key: "source_account")))
    members.append(XdrJsonMember(key: "seq_num", value: try SequenceNumberXDRJsonCodec.toXdrJsonValue(self.seqNum, type: "OperationID", key: "seq_num")))
    members.append(XdrJsonMember(key: "op_num", value: try Uint32XDRJsonCodec.toXdrJsonValue(self.opNum, type: "OperationID", key: "op_num")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> OperationID {
    let members = try XdrJson.object(value, type: "OperationID", keys: ["source_account", "seq_num", "op_num"])
    let sourceAccount: PublicKey = try AccountIDXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "source_account", type: "OperationID"), type: "OperationID", key: "source_account")
    let seqNum: Int64 = try SequenceNumberXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "seq_num", type: "OperationID"), type: "OperationID", key: "seq_num")
    let opNum: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "op_num", type: "OperationID"), type: "OperationID", key: "op_num")
    return OperationID(
      sourceAccount: sourceAccount,
      seqNum: seqNum,
      opNum: opNum
    )
  }
}
