// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct OperationID: XDRCodable, Sendable {
  public var sourceAccount: PublicKey
  public var seqNum: Int64
  public var opNum: UInt32

  public init(
    sourceAccount: PublicKey,
    seqNum: Int64,
    opNum: UInt32
  ) {
    self.sourceAccount = sourceAccount
    self.seqNum = seqNum
    self.opNum = opNum
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    sourceAccount = try container.decode(PublicKey.self)
    seqNum = try container.decode(Int64.self)
    opNum = try container.decode(UInt32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(sourceAccount)
    try container.encode(seqNum)
    try container.encode(opNum)
  }
}
