// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct OperationMetaXDR: XDRCodable, Sendable {
  public let changes: LedgerEntryChangesXDR

  public init(changes: LedgerEntryChangesXDR) {
    self.changes = changes
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    changes = try container.decode(LedgerEntryChangesXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(changes)
  }
}

extension OperationMetaXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "changes", value: try self.changes.toXdrJsonValue()))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> OperationMetaXDR {
    let members = try XdrJson.object(value, type: "OperationMetaXDR", keys: ["changes"])
    let changes: LedgerEntryChangesXDR = try LedgerEntryChangesXDR.fromXdrJsonValue(try XdrJson.field(members, key: "changes", type: "OperationMetaXDR"))
    return OperationMetaXDR(changes: changes)
  }
}
