// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ParallelTxsComponentXDR: XDRCodable, Sendable {
  public var baseFee: Int64?
  public var executionStages: [ParallelTxExecutionStageXDR]

  public init(baseFee: Int64? = nil, executionStages: [ParallelTxExecutionStageXDR]) {
    self.baseFee = baseFee
    self.executionStages = executionStages
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let baseFeePresent = try container.decode(Int32.self)
    if baseFeePresent != 0 {
      baseFee = try container.decode(Int64.self)
    } else {
      baseFee = nil
    }
    executionStages = try decodeArray(type: ParallelTxExecutionStageXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    if let val = baseFee {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    try container.encode(executionStages)
  }
}

extension ParallelTxsComponentXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "base_fee", value: try XdrJson.optional(self.baseFee.map { element in try Int64XDRJsonCodec.toXdrJsonValue(element, type: "ParallelTxsComponentXDR", key: "base_fee") })))
    members.append(XdrJsonMember(key: "execution_stages", value: try XdrJson.array(self.executionStages.map { element in try element.toXdrJsonValue() })))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> ParallelTxsComponentXDR {
    let members = try XdrJson.object(value, type: "ParallelTxsComponentXDR", keys: ["base_fee", "execution_stages"])
    let baseFeeValue = try XdrJson.field(members, key: "base_fee", type: "ParallelTxsComponentXDR")
    let baseFee: Int64?
    if baseFeeValue.isNull {
      baseFee = nil
    } else {
      baseFee = try Int64XDRJsonCodec.fromXdrJsonValue(baseFeeValue, type: "ParallelTxsComponentXDR", key: "base_fee")
    }
    let executionStagesElements = try XdrJson.array(try XdrJson.field(members, key: "execution_stages", type: "ParallelTxsComponentXDR"), type: "ParallelTxsComponentXDR", key: "execution_stages")
    let executionStages: [ParallelTxExecutionStageXDR] = try executionStagesElements.map { element in try ParallelTxExecutionStageXDR.fromXdrJsonValue(element) }
    return ParallelTxsComponentXDR(baseFee: baseFee, executionStages: executionStages)
  }
}
