// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum PathPaymentResultCode: Int32, XDRCodable, Equatable, Sendable {
  case success = 0
  case malformed = -1
  case underfunded = -2
  case srcNoTrust = -3
  case srcNotAuthorized = -4
  case noDestination = -5
  case noTrust = -6
  case notAuthorized = -7
  case lineFull = -8
  case noIssuer = -9
  case tooFewOffers = -10
  case offerCrossSelf = -11
  case overSendmax = -12
}

// PathPaymentResultCode is the Swift form of both PathPaymentStrictReceiveResultCode and PathPaymentStrictSendResultCode.
// SEP-0051 renders them under different names, so no single rendering is correct for
// this type and it carries no XDR-JSON members. The conversions live on
// the union each of them discriminates, under that definition's own names.
