// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct PeerAddressXDR: XDRCodable, Sendable {
  public var ip: PeerAddressXDRIpXDR
  public var port: UInt32
  public var numFailures: UInt32

  public init(
    ip: PeerAddressXDRIpXDR,
    port: UInt32,
    numFailures: UInt32
  ) {
    self.ip = ip
    self.port = port
    self.numFailures = numFailures
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    ip = try container.decode(PeerAddressXDRIpXDR.self)
    port = try container.decode(UInt32.self)
    numFailures = try container.decode(UInt32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(ip)
    try container.encode(port)
    try container.encode(numFailures)
  }
}

extension PeerAddressXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "ip", value: try self.ip.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "port", value: try Uint32XDRJsonCodec.toXdrJsonValue(self.port, type: "PeerAddressXDR", key: "port")))
    members.append(XdrJsonMember(key: "num_failures", value: try Uint32XDRJsonCodec.toXdrJsonValue(self.numFailures, type: "PeerAddressXDR", key: "num_failures")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> PeerAddressXDR {
    let members = try XdrJson.object(value, type: "PeerAddressXDR", keys: ["ip", "port", "num_failures"])
    let ip: PeerAddressXDRIpXDR = try PeerAddressXDRIpXDR.fromXdrJsonValue(try XdrJson.field(members, key: "ip", type: "PeerAddressXDR"))
    let port: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "port", type: "PeerAddressXDR"), type: "PeerAddressXDR", key: "port")
    let numFailures: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "num_failures", type: "PeerAddressXDR"), type: "PeerAddressXDR", key: "num_failures")
    return PeerAddressXDR(
      ip: ip,
      port: port,
      numFailures: numFailures
    )
  }
}
