// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum PersistedSCPStateXDR: XDRCodable, Sendable {
  case v0(PersistedSCPStateV0XDR)
  case v1(PersistedSCPStateV1XDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case 0:
      let val = try container.decode(PersistedSCPStateV0XDR.self)
      self = .v0(val)
    case 1:
      let val = try container.decode(PersistedSCPStateV1XDR.self)
      self = .v1(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown PersistedSCPStateXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .v0: return 0
    case .v1: return 1
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .v0(let val):
      try container.encode(val)
    case .v1(let val):
      try container.encode(val)
    }
  }
}

extension PersistedSCPStateXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .v0(let payload):
      return .object([XdrJsonMember(key: "v0", value: try payload.toXdrJsonValue())])
    case .v1(let payload):
      return .object([XdrJsonMember(key: "v1", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> PersistedSCPStateXDR {
    if case .string(let name) = value {
      switch name {
      case "v0":
        throw XdrJsonError.invalidValue(type: "PersistedSCPStateXDR", key: "v0",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "v1":
        throw XdrJsonError.invalidValue(type: "PersistedSCPStateXDR", key: "v1",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "PersistedSCPStateXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "PersistedSCPStateXDR")
    switch member.key {
    case "v0":
      let v0: PersistedSCPStateV0XDR = try PersistedSCPStateV0XDR.fromXdrJsonValue(member.value)
      return .v0(v0)
    case "v1":
      let v1: PersistedSCPStateV1XDR = try PersistedSCPStateV1XDR.fromXdrJsonValue(member.value)
      return .v1(v1)
    default:
      throw XdrJsonError.unknownUnionArm(type: "PersistedSCPStateXDR", key: member.key)
    }
  }
}
