// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct PersistedSCPStateV1XDR: XDRCodable, Sendable {
  public var scpEnvelopes: [SCPEnvelopeXDR]
  public var quorumSets: [SCPQuorumSetXDR]

  public init(scpEnvelopes: [SCPEnvelopeXDR], quorumSets: [SCPQuorumSetXDR]) {
    self.scpEnvelopes = scpEnvelopes
    self.quorumSets = quorumSets
  }

  public init(from decoder: Decoder) throws {
    scpEnvelopes = try decodeArray(type: SCPEnvelopeXDR.self, dec: decoder)
    quorumSets = try decodeArray(type: SCPQuorumSetXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(scpEnvelopes)
    try container.encode(quorumSets)
  }
}
