// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct PreconditionsV2XDR: XDRCodable, Sendable {
  public let timeBounds: TimeBoundsXDR?
  public let ledgerBounds: LedgerBoundsXDR?
  public let sequenceNumber: Int64?
  public let minSeqAge: UInt64
  public let minSeqLedgerGap: UInt32
  public let extraSigners: [SignerKeyXDR]

  public init(
    timeBounds: TimeBoundsXDR? = nil,
    ledgerBounds: LedgerBoundsXDR? = nil,
    sequenceNumber: Int64? = nil,
    minSeqAge: UInt64,
    minSeqLedgerGap: UInt32,
    extraSigners: [SignerKeyXDR]
  ) {
    self.timeBounds = timeBounds
    self.ledgerBounds = ledgerBounds
    self.sequenceNumber = sequenceNumber
    self.minSeqAge = minSeqAge
    self.minSeqLedgerGap = minSeqLedgerGap
    self.extraSigners = extraSigners
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let timeBoundsPresent = try container.decode(Int32.self)
    if timeBoundsPresent != 0 {
      timeBounds = try container.decode(TimeBoundsXDR.self)
    } else {
      timeBounds = nil
    }
    let ledgerBoundsPresent = try container.decode(Int32.self)
    if ledgerBoundsPresent != 0 {
      ledgerBounds = try container.decode(LedgerBoundsXDR.self)
    } else {
      ledgerBounds = nil
    }
    let sequenceNumberPresent = try container.decode(Int32.self)
    if sequenceNumberPresent != 0 {
      sequenceNumber = try container.decode(Int64.self)
    } else {
      sequenceNumber = nil
    }
    minSeqAge = try container.decode(UInt64.self)
    minSeqLedgerGap = try container.decode(UInt32.self)
    extraSigners = try decodeArray(type: SignerKeyXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    if let val = timeBounds {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = ledgerBounds {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = sequenceNumber {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    try container.encode(minSeqAge)
    try container.encode(minSeqLedgerGap)
    try container.encode(extraSigners)
  }
}
