// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum PreconditionsXDR: XDRCodable, Sendable {
  case none
  case time(TimeBoundsXDR)
  case v2(PreconditionsV2XDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case PreconditionType.none.rawValue:
      self = .none
    case PreconditionType.time.rawValue:
      let val = try container.decode(TimeBoundsXDR.self)
      self = .time(val)
    case PreconditionType.v2.rawValue:
      let val = try container.decode(PreconditionsV2XDR.self)
      self = .v2(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown PreconditionsXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .none: return PreconditionType.none.rawValue
    case .time: return PreconditionType.time.rawValue
    case .v2: return PreconditionType.v2.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .none:
      break
    case .time(let val):
      try container.encode(val)
    case .v2(let val):
      try container.encode(val)
    }
  }
}

extension PreconditionsXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    switch self {
    case .none:
      lines.append("\(prefix).type: PRECOND_NONE")
    case .time(let val):
      lines.append("\(prefix).type: PRECOND_TIME")
      try val.toTxRep(prefix: "\(prefix).timeBounds", lines: &lines)
    case .v2(let val):
      lines.append("\(prefix).type: PRECOND_V2")
      try val.toTxRep(prefix: "\(prefix).v2", lines: &lines)
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> PreconditionsXDR {
    let discKey = "\(prefix).type"
    guard let discName = TxRepHelper.getValue(map, discKey) else {
      throw TxRepError.missingValue(key: discKey)
    }
    switch discName {
    case "PRECOND_NONE":
      return .none
    case "PRECOND_TIME":
      let val = try TimeBoundsXDR.fromTxRep(map, prefix: "\(prefix).timeBounds")
      return .time(val)
    case "PRECOND_V2":
      let val = try PreconditionsV2XDR.fromTxRep(map, prefix: "\(prefix).v2")
      return .v2(val)
    default:
      throw TxRepError.invalidValue(key: discKey)
    }
  }
}

extension PreconditionsXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .none: return .string("none")
    case .time(let payload):
      return .object([XdrJsonMember(key: "time", value: try payload.toXdrJsonValue())])
    case .v2(let payload):
      return .object([XdrJsonMember(key: "v2", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> PreconditionsXDR {
    if case .string(let name) = value {
      switch name {
      case "none":
        return .none
      case "time":
        throw XdrJsonError.invalidValue(type: "PreconditionsXDR", key: "time",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "v2":
        throw XdrJsonError.invalidValue(type: "PreconditionsXDR", key: "v2",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "PreconditionsXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "PreconditionsXDR")
    switch member.key {
    case "none":
      throw XdrJsonError.invalidValue(type: "PreconditionsXDR", key: "none",
                                      message: "this arm carries no value, so it is written as a bare string")
    case "time":
      let time: TimeBoundsXDR = try TimeBoundsXDR.fromXdrJsonValue(member.value)
      return .time(time)
    case "v2":
      let v2: PreconditionsV2XDR = try PreconditionsV2XDR.fromXdrJsonValue(member.value)
      return .v2(v2)
    default:
      throw XdrJsonError.unknownUnionArm(type: "PreconditionsXDR", key: member.key)
    }
  }
}
