// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum PreconditionType: Int32, XDRCodable, Equatable, Sendable {
  case none = 0
  case time = 1
  case v2 = 2
}
