// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum PublicKeyTypeXDR: Int32, XDRCodable, Equatable, Sendable {
  case publicKeyTypeEd25519 = 0
}
