// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum RevokeSponsorshipOpXDR: XDRCodable, Sendable {
  case revokeSponsorshipLedgerEntry(LedgerKeyXDR)
  case revokeSponsorshipSignerEntry(RevokeSponsorshipSignerXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case RevokeSponsorshipType.revokeSponsorshipLedgerEntry.rawValue:
      let val = try container.decode(LedgerKeyXDR.self)
      self = .revokeSponsorshipLedgerEntry(val)
    case RevokeSponsorshipType.revokeSponsorshipSignerEntry.rawValue:
      let val = try container.decode(RevokeSponsorshipSignerXDR.self)
      self = .revokeSponsorshipSignerEntry(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown RevokeSponsorshipOpXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .revokeSponsorshipLedgerEntry: return RevokeSponsorshipType.revokeSponsorshipLedgerEntry.rawValue
    case .revokeSponsorshipSignerEntry: return RevokeSponsorshipType.revokeSponsorshipSignerEntry.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .revokeSponsorshipLedgerEntry(let val):
      try container.encode(val)
    case .revokeSponsorshipSignerEntry(let val):
      try container.encode(val)
    }
  }
}

extension RevokeSponsorshipOpXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    switch self {
    case .revokeSponsorshipLedgerEntry(let val):
      lines.append("\(prefix).type: REVOKE_SPONSORSHIP_LEDGER_ENTRY")
      try val.toTxRep(prefix: "\(prefix).ledgerKey", lines: &lines)
    case .revokeSponsorshipSignerEntry(let val):
      lines.append("\(prefix).type: REVOKE_SPONSORSHIP_SIGNER")
      try val.toTxRep(prefix: "\(prefix).signer", lines: &lines)
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> RevokeSponsorshipOpXDR {
    let discKey = "\(prefix).type"
    guard let discName = TxRepHelper.getValue(map, discKey) else {
      throw TxRepError.missingValue(key: discKey)
    }
    switch discName {
    case "REVOKE_SPONSORSHIP_LEDGER_ENTRY":
      let val = try LedgerKeyXDR.fromTxRep(map, prefix: "\(prefix).ledgerKey")
      return .revokeSponsorshipLedgerEntry(val)
    case "REVOKE_SPONSORSHIP_SIGNER":
      let val = try RevokeSponsorshipSignerXDR.fromTxRep(map, prefix: "\(prefix).signer")
      return .revokeSponsorshipSignerEntry(val)
    default:
      throw TxRepError.invalidValue(key: discKey)
    }
  }
}

extension RevokeSponsorshipOpXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .revokeSponsorshipLedgerEntry(let payload):
      return .object([XdrJsonMember(key: "ledger_entry", value: try payload.toXdrJsonValue())])
    case .revokeSponsorshipSignerEntry(let payload):
      return .object([XdrJsonMember(key: "signer", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> RevokeSponsorshipOpXDR {
    if case .string(let name) = value {
      switch name {
      case "ledger_entry":
        throw XdrJsonError.invalidValue(type: "RevokeSponsorshipOpXDR", key: "ledger_entry",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "signer":
        throw XdrJsonError.invalidValue(type: "RevokeSponsorshipOpXDR", key: "signer",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "RevokeSponsorshipOpXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "RevokeSponsorshipOpXDR")
    switch member.key {
    case "ledger_entry":
      let revokeSponsorshipLedgerEntry: LedgerKeyXDR = try LedgerKeyXDR.fromXdrJsonValue(member.value)
      return .revokeSponsorshipLedgerEntry(revokeSponsorshipLedgerEntry)
    case "signer":
      let revokeSponsorshipSignerEntry: RevokeSponsorshipSignerXDR = try RevokeSponsorshipSignerXDR.fromXdrJsonValue(member.value)
      return .revokeSponsorshipSignerEntry(revokeSponsorshipSignerEntry)
    default:
      throw XdrJsonError.unknownUnionArm(type: "RevokeSponsorshipOpXDR", key: member.key)
    }
  }
}
