// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum RevokeSponsorshipType: Int32, XDRCodable, Equatable, Sendable {
  case revokeSponsorshipLedgerEntry = 0
  case revokeSponsorshipSignerEntry = 1
}
