// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum RevokeSponsorshipResultCode: Int32, XDRCodable, Equatable, Sendable {
  case success = 0
  case doesNotExist = -1
  case notSponsor = -2
  case lowReserve = -3
  case onlyTransferable = -4
  case malformed = -5
}
