// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCContractInstanceXDR: XDRCodable, Sendable {
  public var executable: ContractExecutableXDR
  public var storage: [SCMapEntryXDR]?

  public init(executable: ContractExecutableXDR, storage: [SCMapEntryXDR]? = nil) {
    self.executable = executable
    self.storage = storage
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    executable = try container.decode(ContractExecutableXDR.self)
    let storagePresent = try container.decode(Int32.self)
    if storagePresent != 0 {
      storage = try decodeArray(type: SCMapEntryXDR.self, dec: decoder)
    } else {
      storage = nil
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(executable)
    if let val = storage {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
  }
}

extension SCContractInstanceXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    try self.executable.toTxRep(prefix: "\(prefix).executable", lines: &lines)
    if let val = self.storage {
      lines.append("\(prefix).storage._present: true")
      lines.append("\(prefix).storage.len: \(val.count)")
      for (i, item) in val.enumerated() {
        try item.toTxRep(prefix: "\(prefix).storage[\(i)]", lines: &lines)
      }
    } else {
      lines.append("\(prefix).storage._present: false")
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> SCContractInstanceXDR {
    let executable: ContractExecutableXDR = try ContractExecutableXDR.fromTxRep(map, prefix: "\(prefix).executable")
    let storage: [SCMapEntryXDR]?
    if TxRepHelper.getValue(map, "\(prefix).storage._present") == "true" {
      let storageTmpLen = try TxRepHelper.parseInt(TxRepHelper.getValue(map, "\(prefix).storage.len") ?? "0")
      var storageTmp = [SCMapEntryXDR]()
      for i in 0..<Int(storageTmpLen) {
        let item: SCMapEntryXDR = try SCMapEntryXDR.fromTxRep(map, prefix: "\(prefix).storage[\(i)]")
        storageTmp.append(item)
      }
      storage = storageTmp
    } else {
      storage = nil
    }
    return SCContractInstanceXDR(executable: executable, storage: storage)
  }
}
