// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SCErrorCode: Int32, XDRCodable, Equatable, Sendable {
  case arithDomain = 0
  case indexBounds = 1
  case invalidInput = 2
  case missingValue = 3
  case existingValue = 4
  case exceededLimit = 5
  case invalidAction = 6
  case internalError = 7
  case unexpectedType = 8
  case unexpectedSize = 9
}
