// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCMapXDR: XDRCodable, Sendable {
  public var wrapped: [SCMapEntryXDR]

  public init(wrapped: [SCMapEntryXDR]) {
    self.wrapped = wrapped
  }

  public init(from decoder: Decoder) throws {
    wrapped = try decodeArray(type: SCMapEntryXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(wrapped)
  }
}

extension SCMapXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    return try XdrJson.array(self.wrapped.map { element in try element.toXdrJsonValue() })
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> SCMapXDR {
    let decodedElements = try XdrJson.array(value, type: "SCMapXDR")
    let decoded: [SCMapEntryXDR] = try decodedElements.map { element in try SCMapEntryXDR.fromXdrJsonValue(element) }
    return SCMapXDR(wrapped: decoded)
  }
}
