// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SCMetaKind: Int32, XDRCodable, Equatable, Sendable {
  case v0 = 0
}
