// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCMetaV0XDR: XDRCodable, Sendable {
  public var key: String
  public var value: String

  public init(key: String, value: String) {
    self.key = key
    self.value = value
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    key = try container.decode(String.self)
    value = try container.decode(String.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(key)
    try container.encode(value)
  }
}
