// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCNonceKeyXDR: XDRCodable, Sendable {
  public var nonce: Int64

  public init(nonce: Int64) {
    self.nonce = nonce
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    nonce = try container.decode(Int64.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(nonce)
  }
}
