// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCNonceKeyXDR: XDRCodable, Sendable {
  public var nonce: Int64

  public init(nonce: Int64) {
    self.nonce = nonce
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    nonce = try container.decode(Int64.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(nonce)
  }
}

extension SCNonceKeyXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).nonce: \(self.nonce)")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> SCNonceKeyXDR {
    let nonce: Int64 = try TxRepHelper.parseInt64(TxRepHelper.getValue(map, "\(prefix).nonce") ?? "0")
    return SCNonceKeyXDR(nonce: nonce)
  }
}

extension SCNonceKeyXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "nonce", value: try Int64XDRJsonCodec.toXdrJsonValue(self.nonce, type: "SCNonceKeyXDR", key: "nonce")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> SCNonceKeyXDR {
    let members = try XdrJson.object(value, type: "SCNonceKeyXDR", keys: ["nonce"])
    let nonce: Int64 = try Int64XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "nonce", type: "SCNonceKeyXDR"), type: "SCNonceKeyXDR", key: "nonce")
    return SCNonceKeyXDR(nonce: nonce)
  }
}
