// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCPEnvelopeXDR: XDRCodable, Sendable {
  public var statement: SCPStatementXDR
  public var signature: Data

  public init(statement: SCPStatementXDR, signature: Data) {
    self.statement = statement
    self.signature = signature
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    statement = try container.decode(SCPStatementXDR.self)
    signature = try container.decode(Data.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(statement)
    try container.encode(signature)
  }
}
