// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SCPHistoryEntryXDR: XDRCodable, Sendable {
  case v0(SCPHistoryEntryV0XDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case 0:
      let val = try container.decode(SCPHistoryEntryV0XDR.self)
      self = .v0(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown SCPHistoryEntryXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .v0: return 0
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .v0(let val):
      try container.encode(val)
    }
  }
}
