// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCPStatementXDRPrepareXDR: XDRCodable, Sendable {
  public var quorumSetHash: HashXDR
  public var ballot: SCPBallotXDR
  public var prepared: SCPBallotXDR?
  public var preparedPrime: SCPBallotXDR?
  public var nC: UInt32
  public var nH: UInt32

  public init(
    quorumSetHash: HashXDR,
    ballot: SCPBallotXDR,
    prepared: SCPBallotXDR? = nil,
    preparedPrime: SCPBallotXDR? = nil,
    nC: UInt32,
    nH: UInt32
  ) {
    self.quorumSetHash = quorumSetHash
    self.ballot = ballot
    self.prepared = prepared
    self.preparedPrime = preparedPrime
    self.nC = nC
    self.nH = nH
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    quorumSetHash = try container.decode(HashXDR.self)
    ballot = try container.decode(SCPBallotXDR.self)
    let preparedPresent = try container.decode(Int32.self)
    if preparedPresent != 0 {
      prepared = try container.decode(SCPBallotXDR.self)
    } else {
      prepared = nil
    }
    let preparedPrimePresent = try container.decode(Int32.self)
    if preparedPrimePresent != 0 {
      preparedPrime = try container.decode(SCPBallotXDR.self)
    } else {
      preparedPrime = nil
    }
    nC = try container.decode(UInt32.self)
    nH = try container.decode(UInt32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(quorumSetHash)
    try container.encode(ballot)
    if let val = prepared {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = preparedPrime {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    try container.encode(nC)
    try container.encode(nH)
  }
}

extension SCPStatementXDRPrepareXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "quorum_set_hash", value: try HashXDRJsonCodec.toXdrJsonValue(self.quorumSetHash, type: "SCPStatementXDRPrepareXDR", key: "quorum_set_hash")))
    members.append(XdrJsonMember(key: "ballot", value: try self.ballot.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "prepared", value: try XdrJson.optional(self.prepared.map { element in try element.toXdrJsonValue() })))
    members.append(XdrJsonMember(key: "prepared_prime", value: try XdrJson.optional(self.preparedPrime.map { element in try element.toXdrJsonValue() })))
    members.append(XdrJsonMember(key: "n_c", value: try Uint32XDRJsonCodec.toXdrJsonValue(self.nC, type: "SCPStatementXDRPrepareXDR", key: "n_c")))
    members.append(XdrJsonMember(key: "n_h", value: try Uint32XDRJsonCodec.toXdrJsonValue(self.nH, type: "SCPStatementXDRPrepareXDR", key: "n_h")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> SCPStatementXDRPrepareXDR {
    let members = try XdrJson.object(value, type: "SCPStatementXDRPrepareXDR", keys: ["quorum_set_hash", "ballot", "prepared", "prepared_prime", "n_c", "n_h"])
    let quorumSetHash: HashXDR = try HashXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "quorum_set_hash", type: "SCPStatementXDRPrepareXDR"), type: "SCPStatementXDRPrepareXDR", key: "quorum_set_hash")
    let ballot: SCPBallotXDR = try SCPBallotXDR.fromXdrJsonValue(try XdrJson.field(members, key: "ballot", type: "SCPStatementXDRPrepareXDR"))
    let preparedValue = try XdrJson.field(members, key: "prepared", type: "SCPStatementXDRPrepareXDR")
    let prepared: SCPBallotXDR?
    if preparedValue.isNull {
      prepared = nil
    } else {
      prepared = try SCPBallotXDR.fromXdrJsonValue(preparedValue)
    }
    let preparedPrimeValue = try XdrJson.field(members, key: "prepared_prime", type: "SCPStatementXDRPrepareXDR")
    let preparedPrime: SCPBallotXDR?
    if preparedPrimeValue.isNull {
      preparedPrime = nil
    } else {
      preparedPrime = try SCPBallotXDR.fromXdrJsonValue(preparedPrimeValue)
    }
    let nC: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "n_c", type: "SCPStatementXDRPrepareXDR"), type: "SCPStatementXDRPrepareXDR", key: "n_c")
    let nH: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "n_h", type: "SCPStatementXDRPrepareXDR"), type: "SCPStatementXDRPrepareXDR", key: "n_h")
    return SCPStatementXDRPrepareXDR(
      quorumSetHash: quorumSetHash,
      ballot: ballot,
      prepared: prepared,
      preparedPrime: preparedPrime,
      nC: nC,
      nH: nH
    )
  }
}
