// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCPStatementXDRPrepareXDR: XDRCodable, Sendable {
  public var quorumSetHash: HashXDR
  public var ballot: SCPBallotXDR
  public var prepared: SCPBallotXDR?
  public var preparedPrime: SCPBallotXDR?
  public var nC: UInt32
  public var nH: UInt32

  public init(
    quorumSetHash: HashXDR,
    ballot: SCPBallotXDR,
    prepared: SCPBallotXDR? = nil,
    preparedPrime: SCPBallotXDR? = nil,
    nC: UInt32,
    nH: UInt32
  ) {
    self.quorumSetHash = quorumSetHash
    self.ballot = ballot
    self.prepared = prepared
    self.preparedPrime = preparedPrime
    self.nC = nC
    self.nH = nH
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    quorumSetHash = try container.decode(HashXDR.self)
    ballot = try container.decode(SCPBallotXDR.self)
    let preparedPresent = try container.decode(Int32.self)
    if preparedPresent != 0 {
      prepared = try container.decode(SCPBallotXDR.self)
    } else {
      prepared = nil
    }
    let preparedPrimePresent = try container.decode(Int32.self)
    if preparedPrimePresent != 0 {
      preparedPrime = try container.decode(SCPBallotXDR.self)
    } else {
      preparedPrime = nil
    }
    nC = try container.decode(UInt32.self)
    nH = try container.decode(UInt32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(quorumSetHash)
    try container.encode(ballot)
    if let val = prepared {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = preparedPrime {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    try container.encode(nC)
    try container.encode(nH)
  }
}
