// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCSpecEventParamV0XDR: XDRCodable, Sendable {
  public var doc: String
  public var name: String
  public var type: SCSpecTypeDefXDR
  public var location: SCSpecEventParamLocationV0

  public init(
    doc: String,
    name: String,
    type: SCSpecTypeDefXDR,
    location: SCSpecEventParamLocationV0
  ) {
    self.doc = doc
    self.name = name
    self.type = type
    self.location = location
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    doc = try container.decode(String.self)
    name = try container.decode(String.self)
    type = try container.decode(SCSpecTypeDefXDR.self)
    location = try container.decode(SCSpecEventParamLocationV0.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(doc)
    try container.encode(name)
    try container.encode(type)
    try container.encode(location)
  }
}

extension SCSpecEventParamV0XDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "doc", value: XdrJson.escapedString(self.doc)))
    members.append(XdrJsonMember(key: "name", value: XdrJson.escapedString(self.name)))
    members.append(XdrJsonMember(key: "type", value: try self.type.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "location", value: try self.location.toXdrJsonValue()))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> SCSpecEventParamV0XDR {
    let members = try XdrJson.object(value, type: "SCSpecEventParamV0XDR", keys: ["doc", "name", XdrJson.DeclaredKey("type", alias: "type_"), "location"])
    let doc: String = try XdrJson.unescapedText(try XdrJson.field(members, key: "doc", type: "SCSpecEventParamV0XDR"), type: "SCSpecEventParamV0XDR", key: "doc")
    let name: String = try XdrJson.unescapedText(try XdrJson.field(members, key: "name", type: "SCSpecEventParamV0XDR"), type: "SCSpecEventParamV0XDR", key: "name")
    let type: SCSpecTypeDefXDR = try SCSpecTypeDefXDR.fromXdrJsonValue(try XdrJson.field(members, key: XdrJson.DeclaredKey("type", alias: "type_"), type: "SCSpecEventParamV0XDR"))
    let location: SCSpecEventParamLocationV0 = try SCSpecEventParamLocationV0.fromXdrJsonValue(try XdrJson.field(members, key: "location", type: "SCSpecEventParamV0XDR"))
    return SCSpecEventParamV0XDR(
      doc: doc,
      name: name,
      type: type,
      location: location
    )
  }
}
