// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCSpecUDTUnionCaseVoidV0XDR: XDRCodable, Sendable {
  public var doc: String
  public var name: String

  public init(doc: String, name: String) {
    self.doc = doc
    self.name = name
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    doc = try container.decode(String.self)
    name = try container.decode(String.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(doc)
    try container.encode(name)
  }
}
