// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SCSpecUDTUnionCaseV0XDR: XDRCodable, Sendable {
  case voidV0(SCSpecUDTUnionCaseVoidV0XDR)
  case tupleV0(SCSpecUDTUnionCaseTupleV0XDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case SCSpecUDTUnionCaseV0Kind.voidV0.rawValue:
      let val = try container.decode(SCSpecUDTUnionCaseVoidV0XDR.self)
      self = .voidV0(val)
    case SCSpecUDTUnionCaseV0Kind.tupleV0.rawValue:
      let val = try container.decode(SCSpecUDTUnionCaseTupleV0XDR.self)
      self = .tupleV0(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown SCSpecUDTUnionCaseV0XDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .voidV0: return SCSpecUDTUnionCaseV0Kind.voidV0.rawValue
    case .tupleV0: return SCSpecUDTUnionCaseV0Kind.tupleV0.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .voidV0(let val):
      try container.encode(val)
    case .tupleV0(let val):
      try container.encode(val)
    }
  }
}

extension SCSpecUDTUnionCaseV0XDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .voidV0(let payload):
      return .object([XdrJsonMember(key: "void_v0", value: try payload.toXdrJsonValue())])
    case .tupleV0(let payload):
      return .object([XdrJsonMember(key: "tuple_v0", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> SCSpecUDTUnionCaseV0XDR {
    if case .string(let name) = value {
      switch name {
      case "void_v0":
        throw XdrJsonError.invalidValue(type: "SCSpecUDTUnionCaseV0XDR", key: "void_v0",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "tuple_v0":
        throw XdrJsonError.invalidValue(type: "SCSpecUDTUnionCaseV0XDR", key: "tuple_v0",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "SCSpecUDTUnionCaseV0XDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "SCSpecUDTUnionCaseV0XDR")
    switch member.key {
    case "void_v0":
      let voidV0: SCSpecUDTUnionCaseVoidV0XDR = try SCSpecUDTUnionCaseVoidV0XDR.fromXdrJsonValue(member.value)
      return .voidV0(voidV0)
    case "tuple_v0":
      let tupleV0: SCSpecUDTUnionCaseTupleV0XDR = try SCSpecUDTUnionCaseTupleV0XDR.fromXdrJsonValue(member.value)
      return .tupleV0(tupleV0)
    default:
      throw XdrJsonError.unknownUnionArm(type: "SCSpecUDTUnionCaseV0XDR", key: member.key)
    }
  }
}
