// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SCSpecEntryKind: Int32, XDRCodable, Equatable, Sendable {
  case functionV0 = 0
  case structV0 = 1
  case unionV0 = 2
  case enumV0 = 3
  case errorEnumV0 = 4
  case entryEventV0 = 5
}
