// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCSpecTypeMapXDR: XDRCodable, Sendable {
  public var keyType: SCSpecTypeDefXDR
  public var valueType: SCSpecTypeDefXDR

  public init(keyType: SCSpecTypeDefXDR, valueType: SCSpecTypeDefXDR) {
    self.keyType = keyType
    self.valueType = valueType
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    keyType = try container.decode(SCSpecTypeDefXDR.self)
    valueType = try container.decode(SCSpecTypeDefXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(keyType)
    try container.encode(valueType)
  }
}
