// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SCSpecTypeVecXDR: XDRCodable, Sendable {
  public var elementType: SCSpecTypeDefXDR

  public init(elementType: SCSpecTypeDefXDR) {
    self.elementType = elementType
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    elementType = try container.decode(SCSpecTypeDefXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(elementType)
  }
}

extension SCSpecTypeVecXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "element_type", value: try self.elementType.toXdrJsonValue()))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> SCSpecTypeVecXDR {
    let members = try XdrJson.object(value, type: "SCSpecTypeVecXDR", keys: ["element_type"])
    let elementType: SCSpecTypeDefXDR = try SCSpecTypeDefXDR.fromXdrJsonValue(try XdrJson.field(members, key: "element_type", type: "SCSpecTypeVecXDR"))
    return SCSpecTypeVecXDR(elementType: elementType)
  }
}
