// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SCSpecUDTUnionCaseV0XDR: XDRCodable, Sendable {
  case voidV0(SCSpecUDTUnionCaseVoidV0XDR)
  case tupleV0(SCSpecUDTUnionCaseTupleV0XDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case SCSpecUDTUnionCaseV0Kind.voidV0.rawValue:
      let val = try container.decode(SCSpecUDTUnionCaseVoidV0XDR.self)
      self = .voidV0(val)
    case SCSpecUDTUnionCaseV0Kind.tupleV0.rawValue:
      let val = try container.decode(SCSpecUDTUnionCaseTupleV0XDR.self)
      self = .tupleV0(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown SCSpecUDTUnionCaseV0XDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .voidV0: return SCSpecUDTUnionCaseV0Kind.voidV0.rawValue
    case .tupleV0: return SCSpecUDTUnionCaseV0Kind.tupleV0.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .voidV0(let val):
      try container.encode(val)
    case .tupleV0(let val):
      try container.encode(val)
    }
  }
}
