// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SCSpecEventDataFormat: Int32, XDRCodable, Equatable, Sendable {
  case singleValue = 0
  case vec = 1
  case map = 2
}
