// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public indirect enum SCValXDR: XDRCodable, Sendable {
  case bool(Bool)
  case void
  case error(SCErrorXDR)
  case u32(UInt32)
  case i32(Int32)
  case u64(UInt64)
  case i64(Int64)
  case timepoint(UInt64)
  case duration(UInt64)
  case u128(UInt128PartsXDR)
  case i128(Int128PartsXDR)
  case u256(UInt256PartsXDR)
  case i256(Int256PartsXDR)
  case bytes(SCBytesXDR)
  case string(String)
  case symbol(String)
  case vec([SCValXDR]?)
  case map([SCMapEntryXDR]?)
  case address(SCAddressXDR)
  case contractInstance(SCContractInstanceXDR)
  case ledgerKeyContractInstance
  case ledgerKeyNonce(SCNonceKeyXDR)
  case executableTag(String)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case SCValType.bool.rawValue:
      let val = try container.decode(Bool.self)
      self = .bool(val)
    case SCValType.void.rawValue:
      self = .void
    case SCValType.error.rawValue:
      let val = try container.decode(SCErrorXDR.self)
      self = .error(val)
    case SCValType.u32.rawValue:
      let val = try container.decode(UInt32.self)
      self = .u32(val)
    case SCValType.i32.rawValue:
      let val = try container.decode(Int32.self)
      self = .i32(val)
    case SCValType.u64.rawValue:
      let val = try container.decode(UInt64.self)
      self = .u64(val)
    case SCValType.i64.rawValue:
      let val = try container.decode(Int64.self)
      self = .i64(val)
    case SCValType.timepoint.rawValue:
      let val = try container.decode(UInt64.self)
      self = .timepoint(val)
    case SCValType.duration.rawValue:
      let val = try container.decode(UInt64.self)
      self = .duration(val)
    case SCValType.u128.rawValue:
      let val = try container.decode(UInt128PartsXDR.self)
      self = .u128(val)
    case SCValType.i128.rawValue:
      let val = try container.decode(Int128PartsXDR.self)
      self = .i128(val)
    case SCValType.u256.rawValue:
      let val = try container.decode(UInt256PartsXDR.self)
      self = .u256(val)
    case SCValType.i256.rawValue:
      let val = try container.decode(Int256PartsXDR.self)
      self = .i256(val)
    case SCValType.bytes.rawValue:
      let val = try container.decode(SCBytesXDR.self)
      self = .bytes(val)
    case SCValType.string.rawValue:
      let val = try container.decode(String.self)
      self = .string(val)
    case SCValType.symbol.rawValue:
      let val = try container.decode(String.self)
      self = .symbol(val)
    case SCValType.vec.rawValue:
      let vecPresent = try container.decode(Int32.self)
      if vecPresent != 0 {
        self = .vec(try container.decode([SCValXDR].self))
      } else {
        self = .vec(nil)
      }
    case SCValType.map.rawValue:
      let mapPresent = try container.decode(Int32.self)
      if mapPresent != 0 {
        self = .map(try container.decode([SCMapEntryXDR].self))
      } else {
        self = .map(nil)
      }
    case SCValType.address.rawValue:
      let val = try container.decode(SCAddressXDR.self)
      self = .address(val)
    case SCValType.contractInstance.rawValue:
      let val = try container.decode(SCContractInstanceXDR.self)
      self = .contractInstance(val)
    case SCValType.ledgerKeyContractInstance.rawValue:
      self = .ledgerKeyContractInstance
    case SCValType.ledgerKeyNonce.rawValue:
      let val = try container.decode(SCNonceKeyXDR.self)
      self = .ledgerKeyNonce(val)
    case SCValType.executableTag.rawValue:
      let val = try container.decode(String.self)
      self = .executableTag(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown SCValXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .bool: return SCValType.bool.rawValue
    case .void: return SCValType.void.rawValue
    case .error: return SCValType.error.rawValue
    case .u32: return SCValType.u32.rawValue
    case .i32: return SCValType.i32.rawValue
    case .u64: return SCValType.u64.rawValue
    case .i64: return SCValType.i64.rawValue
    case .timepoint: return SCValType.timepoint.rawValue
    case .duration: return SCValType.duration.rawValue
    case .u128: return SCValType.u128.rawValue
    case .i128: return SCValType.i128.rawValue
    case .u256: return SCValType.u256.rawValue
    case .i256: return SCValType.i256.rawValue
    case .bytes: return SCValType.bytes.rawValue
    case .string: return SCValType.string.rawValue
    case .symbol: return SCValType.symbol.rawValue
    case .vec: return SCValType.vec.rawValue
    case .map: return SCValType.map.rawValue
    case .address: return SCValType.address.rawValue
    case .contractInstance: return SCValType.contractInstance.rawValue
    case .ledgerKeyContractInstance: return SCValType.ledgerKeyContractInstance.rawValue
    case .ledgerKeyNonce: return SCValType.ledgerKeyNonce.rawValue
    case .executableTag: return SCValType.executableTag.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .bool(let val):
      try container.encode(val)
    case .void:
      break
    case .error(let val):
      try container.encode(val)
    case .u32(let val):
      try container.encode(val)
    case .i32(let val):
      try container.encode(val)
    case .u64(let val):
      try container.encode(val)
    case .i64(let val):
      try container.encode(val)
    case .timepoint(let val):
      try container.encode(val)
    case .duration(let val):
      try container.encode(val)
    case .u128(let val):
      try container.encode(val)
    case .i128(let val):
      try container.encode(val)
    case .u256(let val):
      try container.encode(val)
    case .i256(let val):
      try container.encode(val)
    case .bytes(let val):
      try container.encode(val)
    case .string(let val):
      try container.encode(val)
    case .symbol(let val):
      try container.encode(val)
    case .vec(let val):
      if let val = val {
        try container.encode(Int32(1))
        try container.encode(val)
      } else {
        try container.encode(Int32(0))
      }
    case .map(let val):
      if let val = val {
        try container.encode(Int32(1))
        try container.encode(val)
      } else {
        try container.encode(Int32(0))
      }
    case .address(let val):
      try container.encode(val)
    case .contractInstance(let val):
      try container.encode(val)
    case .ledgerKeyContractInstance:
      break
    case .ledgerKeyNonce(let val):
      try container.encode(val)
    case .executableTag(let val):
      try container.encode(val)
    }
  }
}

extension SCValXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    switch self {
    case .bool(let val):
      lines.append("\(prefix).type: SCV_BOOL")
      lines.append("\(prefix).b: \(val)")
    case .void:
      lines.append("\(prefix).type: SCV_VOID")
    case .error(let val):
      lines.append("\(prefix).type: SCV_ERROR")
      try val.toTxRep(prefix: "\(prefix).error", lines: &lines)
    case .u32(let val):
      lines.append("\(prefix).type: SCV_U32")
      lines.append("\(prefix).u32: \(val)")
    case .i32(let val):
      lines.append("\(prefix).type: SCV_I32")
      lines.append("\(prefix).i32: \(val)")
    case .u64(let val):
      lines.append("\(prefix).type: SCV_U64")
      lines.append("\(prefix).u64: \(val)")
    case .i64(let val):
      lines.append("\(prefix).type: SCV_I64")
      lines.append("\(prefix).i64: \(val)")
    case .timepoint(let val):
      lines.append("\(prefix).type: SCV_TIMEPOINT")
      lines.append("\(prefix).timepoint: \(val)")
    case .duration(let val):
      lines.append("\(prefix).type: SCV_DURATION")
      lines.append("\(prefix).duration: \(val)")
    case .u128(let val):
      lines.append("\(prefix).type: SCV_U128")
      try val.toTxRep(prefix: "\(prefix).u128", lines: &lines)
    case .i128(let val):
      lines.append("\(prefix).type: SCV_I128")
      try val.toTxRep(prefix: "\(prefix).i128", lines: &lines)
    case .u256(let val):
      lines.append("\(prefix).type: SCV_U256")
      try val.toTxRep(prefix: "\(prefix).u256", lines: &lines)
    case .i256(let val):
      lines.append("\(prefix).type: SCV_I256")
      try val.toTxRep(prefix: "\(prefix).i256", lines: &lines)
    case .bytes(let val):
      lines.append("\(prefix).type: SCV_BYTES")
      lines.append("\(prefix).bytes: \(TxRepHelper.bytesToHex(val))")
    case .string(let val):
      lines.append("\(prefix).type: SCV_STRING")
      lines.append("\(prefix).str: \(TxRepHelper.escapeString(val))")
    case .symbol(let val):
      lines.append("\(prefix).type: SCV_SYMBOL")
      lines.append("\(prefix).sym: \(TxRepHelper.escapeString(val))")
    case .vec(let val):
      lines.append("\(prefix).type: SCV_VEC")
      if let inner = val {
        lines.append("\(prefix).vec._present: true")
        lines.append("\(prefix).vec.len: \(inner.count)")
        for (i, item) in inner.enumerated() {
          try item.toTxRep(prefix: "\(prefix).vec[\(i)]", lines: &lines)
        }
      } else {
        lines.append("\(prefix).vec._present: false")
      }
    case .map(let val):
      lines.append("\(prefix).type: SCV_MAP")
      if let inner = val {
        lines.append("\(prefix).map._present: true")
        lines.append("\(prefix).map.len: \(inner.count)")
        for (i, item) in inner.enumerated() {
          try item.toTxRep(prefix: "\(prefix).map[\(i)]", lines: &lines)
        }
      } else {
        lines.append("\(prefix).map._present: false")
      }
    case .address(let val):
      lines.append("\(prefix).type: SCV_ADDRESS")
      try val.toTxRep(prefix: "\(prefix).address", lines: &lines)
    case .contractInstance(let val):
      lines.append("\(prefix).type: SCV_CONTRACT_INSTANCE")
      try val.toTxRep(prefix: "\(prefix).instance", lines: &lines)
    case .ledgerKeyContractInstance:
      lines.append("\(prefix).type: SCV_LEDGER_KEY_CONTRACT_INSTANCE")
    case .ledgerKeyNonce(let val):
      lines.append("\(prefix).type: SCV_LEDGER_KEY_NONCE")
      try val.toTxRep(prefix: "\(prefix).nonce_key", lines: &lines)
    case .executableTag(let val):
      lines.append("\(prefix).type: SCV_EXECUTABLE_TAG")
      lines.append("\(prefix).executable_tag: \(TxRepHelper.escapeString(val))")
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> SCValXDR {
    let discKey = "\(prefix).type"
    guard let discName = TxRepHelper.getValue(map, discKey) else {
      throw TxRepError.missingValue(key: discKey)
    }
    switch discName {
    case "SCV_BOOL":
      let val = (TxRepHelper.getValue(map, "\(prefix).b") ?? "false") == "true"
      return .bool(val)
    case "SCV_VOID":
      return .void
    case "SCV_ERROR":
      let val = try SCErrorXDR.fromTxRep(map, prefix: "\(prefix).error")
      return .error(val)
    case "SCV_U32":
      let val = UInt32(try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).u32") ?? "0"))
      return .u32(val)
    case "SCV_I32":
      let val = try TxRepHelper.parseInt(TxRepHelper.getValue(map, "\(prefix).i32") ?? "0")
      return .i32(val)
    case "SCV_U64":
      let val = try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).u64") ?? "0")
      return .u64(val)
    case "SCV_I64":
      let val = try TxRepHelper.parseInt64(TxRepHelper.getValue(map, "\(prefix).i64") ?? "0")
      return .i64(val)
    case "SCV_TIMEPOINT":
      let val = try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).timepoint") ?? "0")
      return .timepoint(val)
    case "SCV_DURATION":
      let val = try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).duration") ?? "0")
      return .duration(val)
    case "SCV_U128":
      let val = try UInt128PartsXDR.fromTxRep(map, prefix: "\(prefix).u128")
      return .u128(val)
    case "SCV_I128":
      let val = try Int128PartsXDR.fromTxRep(map, prefix: "\(prefix).i128")
      return .i128(val)
    case "SCV_U256":
      let val = try UInt256PartsXDR.fromTxRep(map, prefix: "\(prefix).u256")
      return .u256(val)
    case "SCV_I256":
      let val = try Int256PartsXDR.fromTxRep(map, prefix: "\(prefix).i256")
      return .i256(val)
    case "SCV_BYTES":
      let val = try TxRepHelper.requireHex(map, "\(prefix).bytes")
      return .bytes(val)
    case "SCV_STRING":
      let val = try TxRepHelper.requireString(map, "\(prefix).str")
      return .string(val)
    case "SCV_SYMBOL":
      let val = try TxRepHelper.requireString(map, "\(prefix).sym")
      return .symbol(val)
    case "SCV_VEC":
      if TxRepHelper.getValue(map, "\(prefix).vec._present") == "true" {
        let valLen = try TxRepHelper.parseInt(TxRepHelper.getValue(map, "\(prefix).vec.len") ?? "0")
        var val = [SCValXDR]()
        for i in 0..<Int(valLen) {
          let item: SCValXDR = try SCValXDR.fromTxRep(map, prefix: "\(prefix).vec[\(i)]")
          val.append(item)
        }
        return .vec(val)
      } else {
        return .vec(nil)
      }
    case "SCV_MAP":
      if TxRepHelper.getValue(map, "\(prefix).map._present") == "true" {
        let valLen = try TxRepHelper.parseInt(TxRepHelper.getValue(map, "\(prefix).map.len") ?? "0")
        var val = [SCMapEntryXDR]()
        for i in 0..<Int(valLen) {
          let item: SCMapEntryXDR = try SCMapEntryXDR.fromTxRep(map, prefix: "\(prefix).map[\(i)]")
          val.append(item)
        }
        return .map(val)
      } else {
        return .map(nil)
      }
    case "SCV_ADDRESS":
      let val = try SCAddressXDR.fromTxRep(map, prefix: "\(prefix).address")
      return .address(val)
    case "SCV_CONTRACT_INSTANCE":
      let val = try SCContractInstanceXDR.fromTxRep(map, prefix: "\(prefix).instance")
      return .contractInstance(val)
    case "SCV_LEDGER_KEY_CONTRACT_INSTANCE":
      return .ledgerKeyContractInstance
    case "SCV_LEDGER_KEY_NONCE":
      let val = try SCNonceKeyXDR.fromTxRep(map, prefix: "\(prefix).nonce_key")
      return .ledgerKeyNonce(val)
    case "SCV_EXECUTABLE_TAG":
      let val = try TxRepHelper.requireString(map, "\(prefix).executable_tag")
      return .executableTag(val)
    default:
      throw TxRepError.invalidValue(key: discKey)
    }
  }
}

extension SCValXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .bool(let payload):
      return .object([XdrJsonMember(key: "bool", value: XdrJson.bool(payload))])
    case .void: return .string("void")
    case .error(let payload):
      return .object([XdrJsonMember(key: "error", value: try payload.toXdrJsonValue())])
    case .u32(let payload):
      return .object([XdrJsonMember(key: "u32", value: try Uint32XDRJsonCodec.toXdrJsonValue(payload, type: "SCValXDR", key: "u32"))])
    case .i32(let payload):
      return .object([XdrJsonMember(key: "i32", value: try Int32XDRJsonCodec.toXdrJsonValue(payload, type: "SCValXDR", key: "i32"))])
    case .u64(let payload):
      return .object([XdrJsonMember(key: "u64", value: try Uint64XDRJsonCodec.toXdrJsonValue(payload, type: "SCValXDR", key: "u64"))])
    case .i64(let payload):
      return .object([XdrJsonMember(key: "i64", value: try Int64XDRJsonCodec.toXdrJsonValue(payload, type: "SCValXDR", key: "i64"))])
    case .timepoint(let payload):
      return .object([XdrJsonMember(key: "timepoint", value: try TimePointXDRJsonCodec.toXdrJsonValue(payload, type: "SCValXDR", key: "timepoint"))])
    case .duration(let payload):
      return .object([XdrJsonMember(key: "duration", value: try DurationXDRJsonCodec.toXdrJsonValue(payload, type: "SCValXDR", key: "duration"))])
    case .u128(let payload):
      return .object([XdrJsonMember(key: "u128", value: try payload.toXdrJsonValue())])
    case .i128(let payload):
      return .object([XdrJsonMember(key: "i128", value: try payload.toXdrJsonValue())])
    case .u256(let payload):
      return .object([XdrJsonMember(key: "u256", value: try payload.toXdrJsonValue())])
    case .i256(let payload):
      return .object([XdrJsonMember(key: "i256", value: try payload.toXdrJsonValue())])
    case .bytes(let payload):
      return .object([XdrJsonMember(key: "bytes", value: try SCBytesXDRJsonCodec.toXdrJsonValue(payload, type: "SCValXDR", key: "bytes"))])
    case .string(let payload):
      return .object([XdrJsonMember(key: "string", value: try SCStringXDRJsonCodec.toXdrJsonValue(payload, type: "SCValXDR", key: "string"))])
    case .symbol(let payload):
      return .object([XdrJsonMember(key: "symbol", value: try SCSymbolXDRJsonCodec.toXdrJsonValue(payload, type: "SCValXDR", key: "symbol"))])
    case .vec(let payload):
      return .object([XdrJsonMember(key: "vec", value: try XdrJson.optional(payload.map { element in try XdrJson.array(element.map { element in try element.toXdrJsonValue() }) }))])
    case .map(let payload):
      return .object([XdrJsonMember(key: "map", value: try XdrJson.optional(payload.map { element in try XdrJson.array(element.map { element in try element.toXdrJsonValue() }) }))])
    case .address(let payload):
      return .object([XdrJsonMember(key: "address", value: try payload.toXdrJsonValue())])
    case .contractInstance(let payload):
      return .object([XdrJsonMember(key: "contract_instance", value: try payload.toXdrJsonValue())])
    case .ledgerKeyContractInstance: return .string("ledger_key_contract_instance")
    case .ledgerKeyNonce(let payload):
      return .object([XdrJsonMember(key: "ledger_key_nonce", value: try payload.toXdrJsonValue())])
    case .executableTag(let payload):
      return .object([XdrJsonMember(key: "executable_tag", value: try SCStringXDRJsonCodec.toXdrJsonValue(payload, type: "SCValXDR", key: "executable_tag"))])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> SCValXDR {
    if case .string(let name) = value {
      switch name {
      case "bool":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "bool",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "void":
        return .void
      case "error":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "error",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "u32":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "u32",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "i32":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "i32",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "u64":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "u64",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "i64":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "i64",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "timepoint":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "timepoint",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "duration":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "duration",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "u128":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "u128",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "i128":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "i128",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "u256":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "u256",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "i256":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "i256",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "bytes":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "bytes",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "string":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "string",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "symbol":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "symbol",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "vec":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "vec",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "map":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "map",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "address":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "address",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "contract_instance":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "contract_instance",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "ledger_key_contract_instance":
        return .ledgerKeyContractInstance
      case "ledger_key_nonce":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "ledger_key_nonce",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "executable_tag":
        throw XdrJsonError.invalidValue(type: "SCValXDR", key: "executable_tag",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "SCValXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "SCValXDR")
    switch member.key {
    case "bool":
      let bool: Bool = try XdrJson.bool(member.value, type: "SCValXDR", key: "bool")
      return .bool(bool)
    case "void":
      throw XdrJsonError.invalidValue(type: "SCValXDR", key: "void",
                                      message: "this arm carries no value, so it is written as a bare string")
    case "error":
      let error: SCErrorXDR = try SCErrorXDR.fromXdrJsonValue(member.value)
      return .error(error)
    case "u32":
      let u32: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(member.value, type: "SCValXDR", key: "u32")
      return .u32(u32)
    case "i32":
      let i32: Int32 = try Int32XDRJsonCodec.fromXdrJsonValue(member.value, type: "SCValXDR", key: "i32")
      return .i32(i32)
    case "u64":
      let u64: UInt64 = try Uint64XDRJsonCodec.fromXdrJsonValue(member.value, type: "SCValXDR", key: "u64")
      return .u64(u64)
    case "i64":
      let i64: Int64 = try Int64XDRJsonCodec.fromXdrJsonValue(member.value, type: "SCValXDR", key: "i64")
      return .i64(i64)
    case "timepoint":
      let timepoint: UInt64 = try TimePointXDRJsonCodec.fromXdrJsonValue(member.value, type: "SCValXDR", key: "timepoint")
      return .timepoint(timepoint)
    case "duration":
      let duration: UInt64 = try DurationXDRJsonCodec.fromXdrJsonValue(member.value, type: "SCValXDR", key: "duration")
      return .duration(duration)
    case "u128":
      let u128: UInt128PartsXDR = try UInt128PartsXDR.fromXdrJsonValue(member.value)
      return .u128(u128)
    case "i128":
      let i128: Int128PartsXDR = try Int128PartsXDR.fromXdrJsonValue(member.value)
      return .i128(i128)
    case "u256":
      let u256: UInt256PartsXDR = try UInt256PartsXDR.fromXdrJsonValue(member.value)
      return .u256(u256)
    case "i256":
      let i256: Int256PartsXDR = try Int256PartsXDR.fromXdrJsonValue(member.value)
      return .i256(i256)
    case "bytes":
      let bytes: SCBytesXDR = try SCBytesXDRJsonCodec.fromXdrJsonValue(member.value, type: "SCValXDR", key: "bytes")
      return .bytes(bytes)
    case "string":
      let string: String = try SCStringXDRJsonCodec.fromXdrJsonValue(member.value, type: "SCValXDR", key: "string")
      return .string(string)
    case "symbol":
      let symbol: String = try SCSymbolXDRJsonCodec.fromXdrJsonValue(member.value, type: "SCValXDR", key: "symbol")
      return .symbol(symbol)
    case "vec":
      let vecValue = member.value
      let vec: [SCValXDR]?
      if vecValue.isNull {
        vec = nil
      } else {
        let vecPresentElements = try XdrJson.array(vecValue, type: "SCValXDR", key: "vec")
        let vecPresent: [SCValXDR] = try vecPresentElements.map { element in try SCValXDR.fromXdrJsonValue(element) }
        vec = vecPresent
      }
      return .vec(vec)
    case "map":
      let mapValue = member.value
      let map: [SCMapEntryXDR]?
      if mapValue.isNull {
        map = nil
      } else {
        let mapPresentElements = try XdrJson.array(mapValue, type: "SCValXDR", key: "map")
        let mapPresent: [SCMapEntryXDR] = try mapPresentElements.map { element in try SCMapEntryXDR.fromXdrJsonValue(element) }
        map = mapPresent
      }
      return .map(map)
    case "address":
      let address: SCAddressXDR = try SCAddressXDR.fromXdrJsonValue(member.value)
      return .address(address)
    case "contract_instance":
      let contractInstance: SCContractInstanceXDR = try SCContractInstanceXDR.fromXdrJsonValue(member.value)
      return .contractInstance(contractInstance)
    case "ledger_key_contract_instance":
      throw XdrJsonError.invalidValue(type: "SCValXDR", key: "ledger_key_contract_instance",
                                      message: "this arm carries no value, so it is written as a bare string")
    case "ledger_key_nonce":
      let ledgerKeyNonce: SCNonceKeyXDR = try SCNonceKeyXDR.fromXdrJsonValue(member.value)
      return .ledgerKeyNonce(ledgerKeyNonce)
    case "executable_tag":
      let executableTag: String = try SCStringXDRJsonCodec.fromXdrJsonValue(member.value, type: "SCValXDR", key: "executable_tag")
      return .executableTag(executableTag)
    default:
      throw XdrJsonError.unknownUnionArm(type: "SCValXDR", key: member.key)
    }
  }
}
