// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SetOptionsResultXDR: XDRCodable, Sendable {
  case success
  case lowReserve
  case tooManySigners
  case badFlags
  case invalidInflation
  case cantChange
  case unknownFlag
  case thresholdOutOfRange
  case badSigner
  case invalidHomeDomain
  case authRevocableRequired

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case SetOptionsResultCode.success.rawValue:
      self = .success
    case SetOptionsResultCode.lowReserve.rawValue:
      self = .lowReserve
    case SetOptionsResultCode.tooManySigners.rawValue:
      self = .tooManySigners
    case SetOptionsResultCode.badFlags.rawValue:
      self = .badFlags
    case SetOptionsResultCode.invalidInflation.rawValue:
      self = .invalidInflation
    case SetOptionsResultCode.cantChange.rawValue:
      self = .cantChange
    case SetOptionsResultCode.unknownFlag.rawValue:
      self = .unknownFlag
    case SetOptionsResultCode.thresholdOutOfRange.rawValue:
      self = .thresholdOutOfRange
    case SetOptionsResultCode.badSigner.rawValue:
      self = .badSigner
    case SetOptionsResultCode.invalidHomeDomain.rawValue:
      self = .invalidHomeDomain
    case SetOptionsResultCode.authRevocableRequired.rawValue:
      self = .authRevocableRequired
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown SetOptionsResultXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .success: return SetOptionsResultCode.success.rawValue
    case .lowReserve: return SetOptionsResultCode.lowReserve.rawValue
    case .tooManySigners: return SetOptionsResultCode.tooManySigners.rawValue
    case .badFlags: return SetOptionsResultCode.badFlags.rawValue
    case .invalidInflation: return SetOptionsResultCode.invalidInflation.rawValue
    case .cantChange: return SetOptionsResultCode.cantChange.rawValue
    case .unknownFlag: return SetOptionsResultCode.unknownFlag.rawValue
    case .thresholdOutOfRange: return SetOptionsResultCode.thresholdOutOfRange.rawValue
    case .badSigner: return SetOptionsResultCode.badSigner.rawValue
    case .invalidHomeDomain: return SetOptionsResultCode.invalidHomeDomain.rawValue
    case .authRevocableRequired: return SetOptionsResultCode.authRevocableRequired.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .success:
      break
    case .lowReserve:
      break
    case .tooManySigners:
      break
    case .badFlags:
      break
    case .invalidInflation:
      break
    case .cantChange:
      break
    case .unknownFlag:
      break
    case .thresholdOutOfRange:
      break
    case .badSigner:
      break
    case .invalidHomeDomain:
      break
    case .authRevocableRequired:
      break
    }
  }
}
