// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SetOptionsResultCode: Int32, XDRCodable, Equatable, Sendable {
  case success = 0
  case lowReserve = -1
  case tooManySigners = -2
  case badFlags = -3
  case invalidInflation = -4
  case cantChange = -5
  case unknownFlag = -6
  case thresholdOutOfRange = -7
  case badSigner = -8
  case invalidHomeDomain = -9
  case authRevocableRequired = -10
}
