// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SetOptionsOperationXDR: XDRCodable, Sendable {
  public let inflationDestination: PublicKey?
  public let clearFlags: UInt32?
  public let setFlags: UInt32?
  public let masterWeight: UInt32?
  public let lowThreshold: UInt32?
  public let medThreshold: UInt32?
  public let highThreshold: UInt32?
  public let homeDomain: String?
  public let signer: SignerXDR?

  public init(
    inflationDestination: PublicKey? = nil,
    clearFlags: UInt32? = nil,
    setFlags: UInt32? = nil,
    masterWeight: UInt32? = nil,
    lowThreshold: UInt32? = nil,
    medThreshold: UInt32? = nil,
    highThreshold: UInt32? = nil,
    homeDomain: String? = nil,
    signer: SignerXDR? = nil
  ) {
    self.inflationDestination = inflationDestination
    self.clearFlags = clearFlags
    self.setFlags = setFlags
    self.masterWeight = masterWeight
    self.lowThreshold = lowThreshold
    self.medThreshold = medThreshold
    self.highThreshold = highThreshold
    self.homeDomain = homeDomain
    self.signer = signer
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let inflationDestinationPresent = try container.decode(Int32.self)
    if inflationDestinationPresent != 0 {
      inflationDestination = try container.decode(PublicKey.self)
    } else {
      inflationDestination = nil
    }
    let clearFlagsPresent = try container.decode(Int32.self)
    if clearFlagsPresent != 0 {
      clearFlags = try container.decode(UInt32.self)
    } else {
      clearFlags = nil
    }
    let setFlagsPresent = try container.decode(Int32.self)
    if setFlagsPresent != 0 {
      setFlags = try container.decode(UInt32.self)
    } else {
      setFlags = nil
    }
    let masterWeightPresent = try container.decode(Int32.self)
    if masterWeightPresent != 0 {
      masterWeight = try container.decode(UInt32.self)
    } else {
      masterWeight = nil
    }
    let lowThresholdPresent = try container.decode(Int32.self)
    if lowThresholdPresent != 0 {
      lowThreshold = try container.decode(UInt32.self)
    } else {
      lowThreshold = nil
    }
    let medThresholdPresent = try container.decode(Int32.self)
    if medThresholdPresent != 0 {
      medThreshold = try container.decode(UInt32.self)
    } else {
      medThreshold = nil
    }
    let highThresholdPresent = try container.decode(Int32.self)
    if highThresholdPresent != 0 {
      highThreshold = try container.decode(UInt32.self)
    } else {
      highThreshold = nil
    }
    let homeDomainPresent = try container.decode(Int32.self)
    if homeDomainPresent != 0 {
      homeDomain = try container.decode(String.self)
    } else {
      homeDomain = nil
    }
    let signerPresent = try container.decode(Int32.self)
    if signerPresent != 0 {
      signer = try container.decode(SignerXDR.self)
    } else {
      signer = nil
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    if let val = inflationDestination {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = clearFlags {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = setFlags {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = masterWeight {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = lowThreshold {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = medThreshold {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = highThreshold {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = homeDomain {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
    if let val = signer {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
  }
}

extension SetOptionsOperationXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    if let val = self.inflationDestination {
      lines.append("\(prefix).inflationDest._present: true")
      lines.append("\(prefix).inflationDest: \(TxRepHelper.formatAccountId(val))")
    } else {
      lines.append("\(prefix).inflationDest._present: false")
    }
    if let val = self.clearFlags {
      lines.append("\(prefix).clearFlags._present: true")
      lines.append("\(prefix).clearFlags: \(val)")
    } else {
      lines.append("\(prefix).clearFlags._present: false")
    }
    if let val = self.setFlags {
      lines.append("\(prefix).setFlags._present: true")
      lines.append("\(prefix).setFlags: \(val)")
    } else {
      lines.append("\(prefix).setFlags._present: false")
    }
    if let val = self.masterWeight {
      lines.append("\(prefix).masterWeight._present: true")
      lines.append("\(prefix).masterWeight: \(val)")
    } else {
      lines.append("\(prefix).masterWeight._present: false")
    }
    if let val = self.lowThreshold {
      lines.append("\(prefix).lowThreshold._present: true")
      lines.append("\(prefix).lowThreshold: \(val)")
    } else {
      lines.append("\(prefix).lowThreshold._present: false")
    }
    if let val = self.medThreshold {
      lines.append("\(prefix).medThreshold._present: true")
      lines.append("\(prefix).medThreshold: \(val)")
    } else {
      lines.append("\(prefix).medThreshold._present: false")
    }
    if let val = self.highThreshold {
      lines.append("\(prefix).highThreshold._present: true")
      lines.append("\(prefix).highThreshold: \(val)")
    } else {
      lines.append("\(prefix).highThreshold._present: false")
    }
    if let val = self.homeDomain {
      lines.append("\(prefix).homeDomain._present: true")
      lines.append("\(prefix).homeDomain: \(TxRepHelper.escapeString(val))")
    } else {
      lines.append("\(prefix).homeDomain._present: false")
    }
    if let val = self.signer {
      lines.append("\(prefix).signer._present: true")
      try val.toTxRep(prefix: "\(prefix).signer", lines: &lines)
    } else {
      lines.append("\(prefix).signer._present: false")
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> SetOptionsOperationXDR {
    let inflationDestination: PublicKey?
    if TxRepHelper.getValue(map, "\(prefix).inflationDest._present") == "true" {
      inflationDestination = try TxRepHelper.parseAccountId(TxRepHelper.getValue(map, "\(prefix).inflationDest") ?? "")
    } else {
      inflationDestination = nil
    }
    let clearFlags: UInt32?
    if TxRepHelper.getValue(map, "\(prefix).clearFlags._present") == "true" {
      clearFlags = UInt32(try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).clearFlags") ?? "0"))
    } else {
      clearFlags = nil
    }
    let setFlags: UInt32?
    if TxRepHelper.getValue(map, "\(prefix).setFlags._present") == "true" {
      setFlags = UInt32(try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).setFlags") ?? "0"))
    } else {
      setFlags = nil
    }
    let masterWeight: UInt32?
    if TxRepHelper.getValue(map, "\(prefix).masterWeight._present") == "true" {
      masterWeight = UInt32(try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).masterWeight") ?? "0"))
    } else {
      masterWeight = nil
    }
    let lowThreshold: UInt32?
    if TxRepHelper.getValue(map, "\(prefix).lowThreshold._present") == "true" {
      lowThreshold = UInt32(try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).lowThreshold") ?? "0"))
    } else {
      lowThreshold = nil
    }
    let medThreshold: UInt32?
    if TxRepHelper.getValue(map, "\(prefix).medThreshold._present") == "true" {
      medThreshold = UInt32(try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).medThreshold") ?? "0"))
    } else {
      medThreshold = nil
    }
    let highThreshold: UInt32?
    if TxRepHelper.getValue(map, "\(prefix).highThreshold._present") == "true" {
      highThreshold = UInt32(try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).highThreshold") ?? "0"))
    } else {
      highThreshold = nil
    }
    let homeDomain: String?
    if TxRepHelper.getValue(map, "\(prefix).homeDomain._present") == "true" {
      homeDomain = try TxRepHelper.unescapeString(TxRepHelper.getValue(map, "\(prefix).homeDomain") ?? "")
    } else {
      homeDomain = nil
    }
    let signer: SignerXDR?
    if TxRepHelper.getValue(map, "\(prefix).signer._present") == "true" {
      signer = try SignerXDR.fromTxRep(map, prefix: "\(prefix).signer")
    } else {
      signer = nil
    }
    return SetOptionsOperationXDR(inflationDestination: inflationDestination, clearFlags: clearFlags, setFlags: setFlags, masterWeight: masterWeight, lowThreshold: lowThreshold, medThreshold: medThreshold, highThreshold: highThreshold, homeDomain: homeDomain, signer: signer)
  }
}

extension SetOptionsOperationXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "inflation_dest", value: try XdrJson.optional(self.inflationDestination.map { element in try AccountIDXDRJsonCodec.toXdrJsonValue(element, type: "SetOptionsOperationXDR", key: "inflation_dest") })))
    members.append(XdrJsonMember(key: "clear_flags", value: try XdrJson.optional(self.clearFlags.map { element in try Uint32XDRJsonCodec.toXdrJsonValue(element, type: "SetOptionsOperationXDR", key: "clear_flags") })))
    members.append(XdrJsonMember(key: "set_flags", value: try XdrJson.optional(self.setFlags.map { element in try Uint32XDRJsonCodec.toXdrJsonValue(element, type: "SetOptionsOperationXDR", key: "set_flags") })))
    members.append(XdrJsonMember(key: "master_weight", value: try XdrJson.optional(self.masterWeight.map { element in try Uint32XDRJsonCodec.toXdrJsonValue(element, type: "SetOptionsOperationXDR", key: "master_weight") })))
    members.append(XdrJsonMember(key: "low_threshold", value: try XdrJson.optional(self.lowThreshold.map { element in try Uint32XDRJsonCodec.toXdrJsonValue(element, type: "SetOptionsOperationXDR", key: "low_threshold") })))
    members.append(XdrJsonMember(key: "med_threshold", value: try XdrJson.optional(self.medThreshold.map { element in try Uint32XDRJsonCodec.toXdrJsonValue(element, type: "SetOptionsOperationXDR", key: "med_threshold") })))
    members.append(XdrJsonMember(key: "high_threshold", value: try XdrJson.optional(self.highThreshold.map { element in try Uint32XDRJsonCodec.toXdrJsonValue(element, type: "SetOptionsOperationXDR", key: "high_threshold") })))
    members.append(XdrJsonMember(key: "home_domain", value: try XdrJson.optional(self.homeDomain.map { element in try String32XDRJsonCodec.toXdrJsonValue(element, type: "SetOptionsOperationXDR", key: "home_domain") })))
    members.append(XdrJsonMember(key: "signer", value: try XdrJson.optional(self.signer.map { element in try element.toXdrJsonValue() })))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> SetOptionsOperationXDR {
    let members = try XdrJson.object(value, type: "SetOptionsOperationXDR", keys: ["inflation_dest", "clear_flags", "set_flags", "master_weight", "low_threshold", "med_threshold", "high_threshold", "home_domain", "signer"])
    let inflationDestinationValue = try XdrJson.field(members, key: "inflation_dest", type: "SetOptionsOperationXDR")
    let inflationDestination: PublicKey?
    if inflationDestinationValue.isNull {
      inflationDestination = nil
    } else {
      inflationDestination = try AccountIDXDRJsonCodec.fromXdrJsonValue(inflationDestinationValue, type: "SetOptionsOperationXDR", key: "inflation_dest")
    }
    let clearFlagsValue = try XdrJson.field(members, key: "clear_flags", type: "SetOptionsOperationXDR")
    let clearFlags: UInt32?
    if clearFlagsValue.isNull {
      clearFlags = nil
    } else {
      clearFlags = try Uint32XDRJsonCodec.fromXdrJsonValue(clearFlagsValue, type: "SetOptionsOperationXDR", key: "clear_flags")
    }
    let setFlagsValue = try XdrJson.field(members, key: "set_flags", type: "SetOptionsOperationXDR")
    let setFlags: UInt32?
    if setFlagsValue.isNull {
      setFlags = nil
    } else {
      setFlags = try Uint32XDRJsonCodec.fromXdrJsonValue(setFlagsValue, type: "SetOptionsOperationXDR", key: "set_flags")
    }
    let masterWeightValue = try XdrJson.field(members, key: "master_weight", type: "SetOptionsOperationXDR")
    let masterWeight: UInt32?
    if masterWeightValue.isNull {
      masterWeight = nil
    } else {
      masterWeight = try Uint32XDRJsonCodec.fromXdrJsonValue(masterWeightValue, type: "SetOptionsOperationXDR", key: "master_weight")
    }
    let lowThresholdValue = try XdrJson.field(members, key: "low_threshold", type: "SetOptionsOperationXDR")
    let lowThreshold: UInt32?
    if lowThresholdValue.isNull {
      lowThreshold = nil
    } else {
      lowThreshold = try Uint32XDRJsonCodec.fromXdrJsonValue(lowThresholdValue, type: "SetOptionsOperationXDR", key: "low_threshold")
    }
    let medThresholdValue = try XdrJson.field(members, key: "med_threshold", type: "SetOptionsOperationXDR")
    let medThreshold: UInt32?
    if medThresholdValue.isNull {
      medThreshold = nil
    } else {
      medThreshold = try Uint32XDRJsonCodec.fromXdrJsonValue(medThresholdValue, type: "SetOptionsOperationXDR", key: "med_threshold")
    }
    let highThresholdValue = try XdrJson.field(members, key: "high_threshold", type: "SetOptionsOperationXDR")
    let highThreshold: UInt32?
    if highThresholdValue.isNull {
      highThreshold = nil
    } else {
      highThreshold = try Uint32XDRJsonCodec.fromXdrJsonValue(highThresholdValue, type: "SetOptionsOperationXDR", key: "high_threshold")
    }
    let homeDomainValue = try XdrJson.field(members, key: "home_domain", type: "SetOptionsOperationXDR")
    let homeDomain: String?
    if homeDomainValue.isNull {
      homeDomain = nil
    } else {
      homeDomain = try String32XDRJsonCodec.fromXdrJsonValue(homeDomainValue, type: "SetOptionsOperationXDR", key: "home_domain")
    }
    let signerValue = try XdrJson.field(members, key: "signer", type: "SetOptionsOperationXDR")
    let signer: SignerXDR?
    if signerValue.isNull {
      signer = nil
    } else {
      signer = try SignerXDR.fromXdrJsonValue(signerValue)
    }
    return SetOptionsOperationXDR(
      inflationDestination: inflationDestination,
      clearFlags: clearFlags,
      setFlags: setFlags,
      masterWeight: masterWeight,
      lowThreshold: lowThreshold,
      medThreshold: medThreshold,
      highThreshold: highThreshold,
      homeDomain: homeDomain,
      signer: signer
    )
  }
}
