// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SetTrustLineFlagsResultCode: Int32, XDRCodable, Equatable, Sendable {
  case success = 0
  case malformed = -1
  case noTrustLine = -2
  case cantRevoke = -3
  case invalidState = -4
  case lowReserve = -5
}
