// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ShortHashSeedXDR: XDRCodable, Sendable {
  public var seed: Data

  public init(seed: Data) {
    self.seed = seed
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    seed = try container.decode(Data.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(seed)
  }
}
