// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SignedTimeSlicedSurveyStartCollectingMessageXDR: XDRCodable, Sendable {
  public var signature: Data
  public var startCollecting: TimeSlicedSurveyStartCollectingMessageXDR

  public init(signature: Data, startCollecting: TimeSlicedSurveyStartCollectingMessageXDR) {
    self.signature = signature
    self.startCollecting = startCollecting
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    signature = try container.decode(Data.self)
    startCollecting = try container.decode(TimeSlicedSurveyStartCollectingMessageXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(signature)
    try container.encode(startCollecting)
  }
}
