// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SignedTimeSlicedSurveyStopCollectingMessageXDR: XDRCodable, Sendable {
  public var signature: Data
  public var stopCollecting: TimeSlicedSurveyStopCollectingMessageXDR

  public init(signature: Data, stopCollecting: TimeSlicedSurveyStopCollectingMessageXDR) {
    self.signature = signature
    self.stopCollecting = stopCollecting
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    signature = try container.decode(Data.self)
    stopCollecting = try container.decode(TimeSlicedSurveyStopCollectingMessageXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(signature)
    try container.encode(stopCollecting)
  }
}
