// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SignerKeyXDR: XDRCodable, Sendable {
  case ed25519(Uint256XDR)
  case preAuthTx(Uint256XDR)
  case hashX(Uint256XDR)
  case signedPayload(Ed25519SignedPayload)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case SignerKeyType.ed25519.rawValue:
      let val = try container.decode(Uint256XDR.self)
      self = .ed25519(val)
    case SignerKeyType.preAuthTx.rawValue:
      let val = try container.decode(Uint256XDR.self)
      self = .preAuthTx(val)
    case SignerKeyType.hashX.rawValue:
      let val = try container.decode(Uint256XDR.self)
      self = .hashX(val)
    case SignerKeyType.signedPayload.rawValue:
      let val = try container.decode(Ed25519SignedPayload.self)
      self = .signedPayload(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown SignerKeyXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .ed25519: return SignerKeyType.ed25519.rawValue
    case .preAuthTx: return SignerKeyType.preAuthTx.rawValue
    case .hashX: return SignerKeyType.hashX.rawValue
    case .signedPayload: return SignerKeyType.signedPayload.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .ed25519(let val):
      try container.encode(val)
    case .preAuthTx(let val):
      try container.encode(val)
    case .hashX(let val):
      try container.encode(val)
    case .signedPayload(let val):
      try container.encode(val)
    }
  }
}

extension SignerKeyXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    switch self {
    case .ed25519(let val):
      lines.append("\(prefix).type: SIGNER_KEY_TYPE_ED25519")
      lines.append("\(prefix).ed25519: \(TxRepHelper.bytesToHex(val.wrapped))")
    case .preAuthTx(let val):
      lines.append("\(prefix).type: SIGNER_KEY_TYPE_PRE_AUTH_TX")
      lines.append("\(prefix).preAuthTx: \(TxRepHelper.bytesToHex(val.wrapped))")
    case .hashX(let val):
      lines.append("\(prefix).type: SIGNER_KEY_TYPE_HASH_X")
      lines.append("\(prefix).hashX: \(TxRepHelper.bytesToHex(val.wrapped))")
    case .signedPayload(let val):
      lines.append("\(prefix).type: SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD")
      try val.toTxRep(prefix: "\(prefix).ed25519SignedPayload", lines: &lines)
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> SignerKeyXDR {
    let discKey = "\(prefix).type"
    guard let discName = TxRepHelper.getValue(map, discKey) else {
      throw TxRepError.missingValue(key: discKey)
    }
    switch discName {
    case "SIGNER_KEY_TYPE_ED25519":
      let val = try TxRepHelper.requireWrappedData32(map, "\(prefix).ed25519")
      return .ed25519(val)
    case "SIGNER_KEY_TYPE_PRE_AUTH_TX":
      let val = try TxRepHelper.requireWrappedData32(map, "\(prefix).preAuthTx")
      return .preAuthTx(val)
    case "SIGNER_KEY_TYPE_HASH_X":
      let val = try TxRepHelper.requireWrappedData32(map, "\(prefix).hashX")
      return .hashX(val)
    case "SIGNER_KEY_TYPE_ED25519_SIGNED_PAYLOAD":
      let val = try Ed25519SignedPayload.fromTxRep(map, prefix: "\(prefix).ed25519SignedPayload")
      return .signedPayload(val)
    default:
      throw TxRepError.invalidValue(key: discKey)
    }
  }
}

extension SignerKeyXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .ed25519(let key):
      return .string(try XdrJson.strKey(key.wrapped, expectedLength: 32,
                                        type: "SignerKeyXDR", key: "ed25519") { try $0.encodeEd25519PublicKey() })
    case .preAuthTx(let key):
      return .string(try XdrJson.strKey(key.wrapped, expectedLength: 32,
                                        type: "SignerKeyXDR", key: "pre_auth_tx") { try $0.encodePreAuthTx() })
    case .hashX(let key):
      return .string(try XdrJson.strKey(key.wrapped, expectedLength: 32,
                                        type: "SignerKeyXDR", key: "hash_x") { try $0.encodeSha256Hash() })
    case .signedPayload(let payload):
      return try payload.toXdrJsonValue()
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> SignerKeyXDR {
    let text = try XdrJson.string(value, type: "SignerKeyXDR")
    switch text.first {
    case "G":
      return .ed25519(Uint256XDR(try XdrJson.strKeyBytes(text, expectedLength: 32,
                                                         type: "SignerKeyXDR", key: "ed25519") { try $0.decodeEd25519PublicKey() }))
    case "T":
      return .preAuthTx(Uint256XDR(try XdrJson.strKeyBytes(text, expectedLength: 32,
                                                           type: "SignerKeyXDR", key: "pre_auth_tx") { try $0.decodePreAuthTx() }))
    case "X":
      return .hashX(Uint256XDR(try XdrJson.strKeyBytes(text, expectedLength: 32,
                                                       type: "SignerKeyXDR", key: "hash_x") { try $0.decodeSha256Hash() }))
    case "P":
      return .signedPayload(try Ed25519SignedPayload.fromXdrJsonValue(value))
    default:
      throw XdrJsonError.invalidValue(
        type: "SignerKeyXDR", key: nil,
        message: "not an account, pre-authorized transaction, hash or signed payload " +
                 "strkey: \(XdrJson.preview(text))")
    }
  }
}
