// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SorobanDelegateSignatureXDR: XDRCodable, Sendable {
  public var address: SCAddressXDR
  public var signature: SCValXDR
  public var nestedDelegates: [SorobanDelegateSignatureXDR]

  public init(
    address: SCAddressXDR,
    signature: SCValXDR,
    nestedDelegates: [SorobanDelegateSignatureXDR]
  ) {
    self.address = address
    self.signature = signature
    self.nestedDelegates = nestedDelegates
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    address = try container.decode(SCAddressXDR.self)
    signature = try container.decode(SCValXDR.self)
    nestedDelegates = try decodeArray(type: SorobanDelegateSignatureXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(address)
    try container.encode(signature)
    try container.encode(nestedDelegates)
  }
}

extension SorobanDelegateSignatureXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    try self.address.toTxRep(prefix: "\(prefix).address", lines: &lines)
    try self.signature.toTxRep(prefix: "\(prefix).signature", lines: &lines)
    lines.append("\(prefix).nestedDelegates.len: \(self.nestedDelegates.count)")
    for (i, item) in self.nestedDelegates.enumerated() {
      try item.toTxRep(prefix: "\(prefix).nestedDelegates[\(i)]", lines: &lines)
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> SorobanDelegateSignatureXDR {
    let address: SCAddressXDR = try SCAddressXDR.fromTxRep(map, prefix: "\(prefix).address")
    let signature: SCValXDR = try SCValXDR.fromTxRep(map, prefix: "\(prefix).signature")
    let nestedDelegatesLen = try TxRepHelper.parseInt(TxRepHelper.getValue(map, "\(prefix).nestedDelegates.len") ?? "0")
    var nestedDelegates = [SorobanDelegateSignatureXDR]()
    for i in 0..<Int(nestedDelegatesLen) {
      let item: SorobanDelegateSignatureXDR = try SorobanDelegateSignatureXDR.fromTxRep(map, prefix: "\(prefix).nestedDelegates[\(i)]")
      nestedDelegates.append(item)
    }
    return SorobanDelegateSignatureXDR(address: address, signature: signature, nestedDelegates: nestedDelegates)
  }
}
