// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SorobanAuthorizationEntryXDR: XDRCodable, Sendable {
  public var credentials: SorobanCredentialsXDR
  public var rootInvocation: SorobanAuthorizedInvocationXDR

  public init(credentials: SorobanCredentialsXDR, rootInvocation: SorobanAuthorizedInvocationXDR) {
    self.credentials = credentials
    self.rootInvocation = rootInvocation
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    credentials = try container.decode(SorobanCredentialsXDR.self)
    rootInvocation = try container.decode(SorobanAuthorizedInvocationXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(credentials)
    try container.encode(rootInvocation)
  }
}

extension SorobanAuthorizationEntryXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    try self.credentials.toTxRep(prefix: "\(prefix).credentials", lines: &lines)
    try self.rootInvocation.toTxRep(prefix: "\(prefix).rootInvocation", lines: &lines)
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> SorobanAuthorizationEntryXDR {
    let credentials: SorobanCredentialsXDR = try SorobanCredentialsXDR.fromTxRep(map, prefix: "\(prefix).credentials")
    let rootInvocation: SorobanAuthorizedInvocationXDR = try SorobanAuthorizedInvocationXDR.fromTxRep(map, prefix: "\(prefix).rootInvocation")
    return SorobanAuthorizationEntryXDR(credentials: credentials, rootInvocation: rootInvocation)
  }
}
