// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SorobanResourcesExtV0: XDRCodable, Sendable {
  public var archivedSorobanEntries: [UInt32]

  public init(archivedSorobanEntries: [UInt32]) {
    self.archivedSorobanEntries = archivedSorobanEntries
  }

  public init(from decoder: Decoder) throws {
    archivedSorobanEntries = try decodeArray(type: UInt32.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(archivedSorobanEntries)
  }
}

extension SorobanResourcesExtV0 {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).archivedSorobanEntries.len: \(self.archivedSorobanEntries.count)")
    for (i, item) in self.archivedSorobanEntries.enumerated() {
      lines.append("\(prefix).archivedSorobanEntries[\(i)]: \(item)")
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> SorobanResourcesExtV0 {
    let archivedSorobanEntriesLen = try TxRepHelper.parseInt(TxRepHelper.getValue(map, "\(prefix).archivedSorobanEntries.len") ?? "0")
    var archivedSorobanEntries = [UInt32]()
    for i in 0..<Int(archivedSorobanEntriesLen) {
      let item: UInt32 = UInt32(try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).archivedSorobanEntries[\(i)]") ?? "0"))
      archivedSorobanEntries.append(item)
    }
    return SorobanResourcesExtV0(archivedSorobanEntries: archivedSorobanEntries)
  }
}

extension SorobanResourcesExtV0: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "archived_soroban_entries", value: try XdrJson.array(self.archivedSorobanEntries.map { element in try Uint32XDRJsonCodec.toXdrJsonValue(element, type: "SorobanResourcesExtV0", key: "archived_soroban_entries") })))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> SorobanResourcesExtV0 {
    let members = try XdrJson.object(value, type: "SorobanResourcesExtV0", keys: ["archived_soroban_entries"])
    let archivedSorobanEntriesElements = try XdrJson.array(try XdrJson.field(members, key: "archived_soroban_entries", type: "SorobanResourcesExtV0"), type: "SorobanResourcesExtV0", key: "archived_soroban_entries")
    let archivedSorobanEntries: [UInt32] = try archivedSorobanEntriesElements.map { element in try Uint32XDRJsonCodec.fromXdrJsonValue(element, type: "SorobanResourcesExtV0", key: "archived_soroban_entries") }
    return SorobanResourcesExtV0(archivedSorobanEntries: archivedSorobanEntries)
  }
}
