// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SorobanAuthorizedFunctionXDR: XDRCodable, Sendable {
  case contractFn(InvokeContractArgsXDR)
  case createContractHostFn(CreateContractArgsXDR)
  case createContractV2HostFn(CreateContractV2ArgsXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case SorobanAuthorizedFunctionType.contractFn.rawValue:
      let val = try container.decode(InvokeContractArgsXDR.self)
      self = .contractFn(val)
    case SorobanAuthorizedFunctionType.createContractHostFn.rawValue:
      let val = try container.decode(CreateContractArgsXDR.self)
      self = .createContractHostFn(val)
    case SorobanAuthorizedFunctionType.createContractV2HostFn.rawValue:
      let val = try container.decode(CreateContractV2ArgsXDR.self)
      self = .createContractV2HostFn(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown SorobanAuthorizedFunctionXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .contractFn: return SorobanAuthorizedFunctionType.contractFn.rawValue
    case .createContractHostFn: return SorobanAuthorizedFunctionType.createContractHostFn.rawValue
    case .createContractV2HostFn: return SorobanAuthorizedFunctionType.createContractV2HostFn.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .contractFn(let val):
      try container.encode(val)
    case .createContractHostFn(let val):
      try container.encode(val)
    case .createContractV2HostFn(let val):
      try container.encode(val)
    }
  }
}

extension SorobanAuthorizedFunctionXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    switch self {
    case .contractFn(let val):
      lines.append("\(prefix).type: SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN")
      try val.toTxRep(prefix: "\(prefix).contractFn", lines: &lines)
    case .createContractHostFn(let val):
      lines.append("\(prefix).type: SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN")
      try val.toTxRep(prefix: "\(prefix).createContractHostFn", lines: &lines)
    case .createContractV2HostFn(let val):
      lines.append("\(prefix).type: SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN")
      try val.toTxRep(prefix: "\(prefix).createContractV2HostFn", lines: &lines)
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> SorobanAuthorizedFunctionXDR {
    let discKey = "\(prefix).type"
    guard let discName = TxRepHelper.getValue(map, discKey) else {
      throw TxRepError.missingValue(key: discKey)
    }
    switch discName {
    case "SOROBAN_AUTHORIZED_FUNCTION_TYPE_CONTRACT_FN":
      let val = try InvokeContractArgsXDR.fromTxRep(map, prefix: "\(prefix).contractFn")
      return .contractFn(val)
    case "SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_HOST_FN":
      let val = try CreateContractArgsXDR.fromTxRep(map, prefix: "\(prefix).createContractHostFn")
      return .createContractHostFn(val)
    case "SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN":
      let val = try CreateContractV2ArgsXDR.fromTxRep(map, prefix: "\(prefix).createContractV2HostFn")
      return .createContractV2HostFn(val)
    default:
      throw TxRepError.invalidValue(key: discKey)
    }
  }
}

extension SorobanAuthorizedFunctionXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .contractFn(let payload):
      return .object([XdrJsonMember(key: "contract_fn", value: try payload.toXdrJsonValue())])
    case .createContractHostFn(let payload):
      return .object([XdrJsonMember(key: "create_contract_host_fn", value: try payload.toXdrJsonValue())])
    case .createContractV2HostFn(let payload):
      return .object([XdrJsonMember(key: "create_contract_v2_host_fn", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> SorobanAuthorizedFunctionXDR {
    if case .string(let name) = value {
      switch name {
      case "contract_fn":
        throw XdrJsonError.invalidValue(type: "SorobanAuthorizedFunctionXDR", key: "contract_fn",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "create_contract_host_fn":
        throw XdrJsonError.invalidValue(type: "SorobanAuthorizedFunctionXDR", key: "create_contract_host_fn",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "create_contract_v2_host_fn":
        throw XdrJsonError.invalidValue(type: "SorobanAuthorizedFunctionXDR", key: "create_contract_v2_host_fn",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "SorobanAuthorizedFunctionXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "SorobanAuthorizedFunctionXDR")
    switch member.key {
    case "contract_fn":
      let contractFn: InvokeContractArgsXDR = try InvokeContractArgsXDR.fromXdrJsonValue(member.value)
      return .contractFn(contractFn)
    case "create_contract_host_fn":
      let createContractHostFn: CreateContractArgsXDR = try CreateContractArgsXDR.fromXdrJsonValue(member.value)
      return .createContractHostFn(createContractHostFn)
    case "create_contract_v2_host_fn":
      let createContractV2HostFn: CreateContractV2ArgsXDR = try CreateContractV2ArgsXDR.fromXdrJsonValue(member.value)
      return .createContractV2HostFn(createContractV2HostFn)
    default:
      throw XdrJsonError.unknownUnionArm(type: "SorobanAuthorizedFunctionXDR", key: member.key)
    }
  }
}
