// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SorobanTransactionMetaXDR: XDRCodable, Sendable {
  public var ext: SorobanTransactionMetaExt
  public var events: [ContractEventXDR]
  public var returnValue: SCValXDR
  public var diagnosticEvents: [DiagnosticEventXDR]

  public init(
    ext: SorobanTransactionMetaExt,
    events: [ContractEventXDR],
    returnValue: SCValXDR,
    diagnosticEvents: [DiagnosticEventXDR]
  ) {
    self.ext = ext
    self.events = events
    self.returnValue = returnValue
    self.diagnosticEvents = diagnosticEvents
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    ext = try container.decode(SorobanTransactionMetaExt.self)
    events = try decodeArray(type: ContractEventXDR.self, dec: decoder)
    returnValue = try container.decode(SCValXDR.self)
    diagnosticEvents = try decodeArray(type: DiagnosticEventXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(ext)
    try container.encode(events)
    try container.encode(returnValue)
    try container.encode(diagnosticEvents)
  }
}
