// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct SorobanAddressCredentialsWithDelegatesXDR: XDRCodable, Sendable {
  public var addressCredentials: SorobanAddressCredentialsXDR
  public var delegates: [SorobanDelegateSignatureXDR]

  public init(addressCredentials: SorobanAddressCredentialsXDR, delegates: [SorobanDelegateSignatureXDR]) {
    self.addressCredentials = addressCredentials
    self.delegates = delegates
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    addressCredentials = try container.decode(SorobanAddressCredentialsXDR.self)
    delegates = try decodeArray(type: SorobanDelegateSignatureXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(addressCredentials)
    try container.encode(delegates)
  }
}

extension SorobanAddressCredentialsWithDelegatesXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    try self.addressCredentials.toTxRep(prefix: "\(prefix).addressCredentials", lines: &lines)
    lines.append("\(prefix).delegates.len: \(self.delegates.count)")
    for (i, item) in self.delegates.enumerated() {
      try item.toTxRep(prefix: "\(prefix).delegates[\(i)]", lines: &lines)
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> SorobanAddressCredentialsWithDelegatesXDR {
    let addressCredentials: SorobanAddressCredentialsXDR = try SorobanAddressCredentialsXDR.fromTxRep(map, prefix: "\(prefix).addressCredentials")
    let delegatesLen = try TxRepHelper.parseInt(TxRepHelper.getValue(map, "\(prefix).delegates.len") ?? "0")
    var delegates = [SorobanDelegateSignatureXDR]()
    for i in 0..<Int(delegatesLen) {
      let item: SorobanDelegateSignatureXDR = try SorobanDelegateSignatureXDR.fromTxRep(map, prefix: "\(prefix).delegates[\(i)]")
      delegates.append(item)
    }
    return SorobanAddressCredentialsWithDelegatesXDR(addressCredentials: addressCredentials, delegates: delegates)
  }
}
