// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SorobanResourcesExt: XDRCodable, Sendable {
  case void
  case resourceExt(SorobanResourcesExtV0)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case 0:
      self = .void
    case 1:
      let val = try container.decode(SorobanResourcesExtV0.self)
      self = .resourceExt(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown SorobanResourcesExt discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .void: return 0
    case .resourceExt: return 1
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .void:
      break
    case .resourceExt(let val):
      try container.encode(val)
    }
  }
}
