// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct StellarValueXDR: XDRCodable, Sendable {
  public var txSetHash: HashXDR
  public var closeTime: UInt64
  public var upgrades: [UpgradeTypeXDR]
  public var ext: StellarValueXDRExtXDR

  public init(
    txSetHash: HashXDR,
    closeTime: UInt64,
    upgrades: [UpgradeTypeXDR],
    ext: StellarValueXDRExtXDR
  ) {
    self.txSetHash = txSetHash
    self.closeTime = closeTime
    self.upgrades = upgrades
    self.ext = ext
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    txSetHash = try container.decode(HashXDR.self)
    closeTime = try container.decode(UInt64.self)
    upgrades = try decodeArray(type: UpgradeTypeXDR.self, dec: decoder)
    ext = try container.decode(StellarValueXDRExtXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(txSetHash)
    try container.encode(closeTime)
    try container.encode(upgrades)
    try container.encode(ext)
  }
}

extension StellarValueXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "tx_set_hash", value: try HashXDRJsonCodec.toXdrJsonValue(self.txSetHash, type: "StellarValueXDR", key: "tx_set_hash")))
    members.append(XdrJsonMember(key: "close_time", value: try TimePointXDRJsonCodec.toXdrJsonValue(self.closeTime, type: "StellarValueXDR", key: "close_time")))
    members.append(XdrJsonMember(key: "upgrades", value: try XdrJson.array(self.upgrades.map { element in try UpgradeTypeXDRJsonCodec.toXdrJsonValue(element, type: "StellarValueXDR", key: "upgrades") })))
    members.append(XdrJsonMember(key: "ext", value: try self.ext.toXdrJsonValue()))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> StellarValueXDR {
    let members = try XdrJson.object(value, type: "StellarValueXDR", keys: ["tx_set_hash", "close_time", "upgrades", "ext"])
    let txSetHash: HashXDR = try HashXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "tx_set_hash", type: "StellarValueXDR"), type: "StellarValueXDR", key: "tx_set_hash")
    let closeTime: UInt64 = try TimePointXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "close_time", type: "StellarValueXDR"), type: "StellarValueXDR", key: "close_time")
    let upgradesElements = try XdrJson.array(try XdrJson.field(members, key: "upgrades", type: "StellarValueXDR"), type: "StellarValueXDR", key: "upgrades")
    let upgrades: [UpgradeTypeXDR] = try upgradesElements.map { element in try UpgradeTypeXDRJsonCodec.fromXdrJsonValue(element, type: "StellarValueXDR", key: "upgrades") }
    let ext: StellarValueXDRExtXDR = try StellarValueXDRExtXDR.fromXdrJsonValue(try XdrJson.field(members, key: "ext", type: "StellarValueXDR"))
    return StellarValueXDR(
      txSetHash: txSetHash,
      closeTime: closeTime,
      upgrades: upgrades,
      ext: ext
    )
  }
}
