// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct StellarValueXDRProposedMsValueXDR: XDRCodable, Sendable {
  public var closeTimeMs: UInt64
  public var txSetHash: HashXDR
  public var previousLedgerHash: HashXDR
  public var previousLedgerVersion: UInt32
  public var lcValueSignature: LedgerCloseValueSignatureXDR

  public init(
    closeTimeMs: UInt64,
    txSetHash: HashXDR,
    previousLedgerHash: HashXDR,
    previousLedgerVersion: UInt32,
    lcValueSignature: LedgerCloseValueSignatureXDR
  ) {
    self.closeTimeMs = closeTimeMs
    self.txSetHash = txSetHash
    self.previousLedgerHash = previousLedgerHash
    self.previousLedgerVersion = previousLedgerVersion
    self.lcValueSignature = lcValueSignature
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    closeTimeMs = try container.decode(UInt64.self)
    txSetHash = try container.decode(HashXDR.self)
    previousLedgerHash = try container.decode(HashXDR.self)
    previousLedgerVersion = try container.decode(UInt32.self)
    lcValueSignature = try container.decode(LedgerCloseValueSignatureXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(closeTimeMs)
    try container.encode(txSetHash)
    try container.encode(previousLedgerHash)
    try container.encode(previousLedgerVersion)
    try container.encode(lcValueSignature)
  }
}

extension StellarValueXDRProposedMsValueXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "close_time_ms", value: try TimePointMsXDRJsonCodec.toXdrJsonValue(self.closeTimeMs, type: "StellarValueXDRProposedMsValueXDR", key: "close_time_ms")))
    members.append(XdrJsonMember(key: "tx_set_hash", value: try HashXDRJsonCodec.toXdrJsonValue(self.txSetHash, type: "StellarValueXDRProposedMsValueXDR", key: "tx_set_hash")))
    members.append(XdrJsonMember(key: "previous_ledger_hash", value: try HashXDRJsonCodec.toXdrJsonValue(self.previousLedgerHash, type: "StellarValueXDRProposedMsValueXDR", key: "previous_ledger_hash")))
    members.append(XdrJsonMember(key: "previous_ledger_version", value: try Uint32XDRJsonCodec.toXdrJsonValue(self.previousLedgerVersion, type: "StellarValueXDRProposedMsValueXDR", key: "previous_ledger_version")))
    members.append(XdrJsonMember(key: "lc_value_signature", value: try self.lcValueSignature.toXdrJsonValue()))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> StellarValueXDRProposedMsValueXDR {
    let members = try XdrJson.object(value, type: "StellarValueXDRProposedMsValueXDR", keys: ["close_time_ms", "tx_set_hash", "previous_ledger_hash", "previous_ledger_version", "lc_value_signature"])
    let closeTimeMs: UInt64 = try TimePointMsXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "close_time_ms", type: "StellarValueXDRProposedMsValueXDR"), type: "StellarValueXDRProposedMsValueXDR", key: "close_time_ms")
    let txSetHash: HashXDR = try HashXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "tx_set_hash", type: "StellarValueXDRProposedMsValueXDR"), type: "StellarValueXDRProposedMsValueXDR", key: "tx_set_hash")
    let previousLedgerHash: HashXDR = try HashXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "previous_ledger_hash", type: "StellarValueXDRProposedMsValueXDR"), type: "StellarValueXDRProposedMsValueXDR", key: "previous_ledger_hash")
    let previousLedgerVersion: UInt32 = try Uint32XDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "previous_ledger_version", type: "StellarValueXDRProposedMsValueXDR"), type: "StellarValueXDRProposedMsValueXDR", key: "previous_ledger_version")
    let lcValueSignature: LedgerCloseValueSignatureXDR = try LedgerCloseValueSignatureXDR.fromXdrJsonValue(try XdrJson.field(members, key: "lc_value_signature", type: "StellarValueXDRProposedMsValueXDR"))
    return StellarValueXDRProposedMsValueXDR(
      closeTimeMs: closeTimeMs,
      txSetHash: txSetHash,
      previousLedgerHash: previousLedgerHash,
      previousLedgerVersion: previousLedgerVersion,
      lcValueSignature: lcValueSignature
    )
  }
}
