// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum SurveyMessageResponseTypeXDR: Int32, XDRCodable, Equatable, Sendable {
  case surveyTopologyResponseV2 = 2
}
