// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct TimeSlicedPeerDataXDR: XDRCodable, Sendable {
  public var peerStats: PeerStatsXDR
  public var averageLatencyMs: UInt32

  public init(peerStats: PeerStatsXDR, averageLatencyMs: UInt32) {
    self.peerStats = peerStats
    self.averageLatencyMs = averageLatencyMs
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    peerStats = try container.decode(PeerStatsXDR.self)
    averageLatencyMs = try container.decode(UInt32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(peerStats)
    try container.encode(averageLatencyMs)
  }
}
