// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct TimeSlicedNodeDataXDR: XDRCodable, Sendable {
  public var addedAuthenticatedPeers: UInt32
  public var droppedAuthenticatedPeers: UInt32
  public var totalInboundPeerCount: UInt32
  public var totalOutboundPeerCount: UInt32
  public var p75SCPFirstToSelfLatencyMs: UInt32
  public var p75SCPSelfToOtherLatencyMs: UInt32
  public var lostSyncCount: UInt32
  public var isValidator: Bool
  public var maxInboundPeerCount: UInt32
  public var maxOutboundPeerCount: UInt32

  public init(
    addedAuthenticatedPeers: UInt32,
    droppedAuthenticatedPeers: UInt32,
    totalInboundPeerCount: UInt32,
    totalOutboundPeerCount: UInt32,
    p75SCPFirstToSelfLatencyMs: UInt32,
    p75SCPSelfToOtherLatencyMs: UInt32,
    lostSyncCount: UInt32,
    isValidator: Bool,
    maxInboundPeerCount: UInt32,
    maxOutboundPeerCount: UInt32
  ) {
    self.addedAuthenticatedPeers = addedAuthenticatedPeers
    self.droppedAuthenticatedPeers = droppedAuthenticatedPeers
    self.totalInboundPeerCount = totalInboundPeerCount
    self.totalOutboundPeerCount = totalOutboundPeerCount
    self.p75SCPFirstToSelfLatencyMs = p75SCPFirstToSelfLatencyMs
    self.p75SCPSelfToOtherLatencyMs = p75SCPSelfToOtherLatencyMs
    self.lostSyncCount = lostSyncCount
    self.isValidator = isValidator
    self.maxInboundPeerCount = maxInboundPeerCount
    self.maxOutboundPeerCount = maxOutboundPeerCount
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    addedAuthenticatedPeers = try container.decode(UInt32.self)
    droppedAuthenticatedPeers = try container.decode(UInt32.self)
    totalInboundPeerCount = try container.decode(UInt32.self)
    totalOutboundPeerCount = try container.decode(UInt32.self)
    p75SCPFirstToSelfLatencyMs = try container.decode(UInt32.self)
    p75SCPSelfToOtherLatencyMs = try container.decode(UInt32.self)
    lostSyncCount = try container.decode(UInt32.self)
    isValidator = try container.decode(Bool.self)
    maxInboundPeerCount = try container.decode(UInt32.self)
    maxOutboundPeerCount = try container.decode(UInt32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(addedAuthenticatedPeers)
    try container.encode(droppedAuthenticatedPeers)
    try container.encode(totalInboundPeerCount)
    try container.encode(totalOutboundPeerCount)
    try container.encode(p75SCPFirstToSelfLatencyMs)
    try container.encode(p75SCPSelfToOtherLatencyMs)
    try container.encode(lostSyncCount)
    try container.encode(isValidator)
    try container.encode(maxInboundPeerCount)
    try container.encode(maxOutboundPeerCount)
  }
}
