// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct TimeBoundsXDR: XDRCodable, Sendable {
  public let minTime: UInt64
  public let maxTime: UInt64

  public init(minTime: UInt64, maxTime: UInt64) {
    self.minTime = minTime
    self.maxTime = maxTime
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    minTime = try container.decode(UInt64.self)
    maxTime = try container.decode(UInt64.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(minTime)
    try container.encode(maxTime)
  }
}

extension TimeBoundsXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix).minTime: \(self.minTime)")
    lines.append("\(prefix).maxTime: \(self.maxTime)")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> TimeBoundsXDR {
    let minTime: UInt64 = try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).minTime") ?? "0")
    let maxTime: UInt64 = try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).maxTime") ?? "0")
    return TimeBoundsXDR(minTime: minTime, maxTime: maxTime)
  }
}

extension TimeBoundsXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "min_time", value: try TimePointXDRJsonCodec.toXdrJsonValue(self.minTime, type: "TimeBoundsXDR", key: "min_time")))
    members.append(XdrJsonMember(key: "max_time", value: try TimePointXDRJsonCodec.toXdrJsonValue(self.maxTime, type: "TimeBoundsXDR", key: "max_time")))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> TimeBoundsXDR {
    let members = try XdrJson.object(value, type: "TimeBoundsXDR", keys: ["min_time", "max_time"])
    let minTime: UInt64 = try TimePointXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "min_time", type: "TimeBoundsXDR"), type: "TimeBoundsXDR", key: "min_time")
    let maxTime: UInt64 = try TimePointXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "max_time", type: "TimeBoundsXDR"), type: "TimeBoundsXDR", key: "max_time")
    return TimeBoundsXDR(minTime: minTime, maxTime: maxTime)
  }
}
