// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct TransactionSignaturePayload: XDRCodable, Sendable {
  public var networkId: HashXDR
  public var taggedTransaction: TransactionSignaturePayloadTaggedTransactionXDR

  public init(networkId: HashXDR, taggedTransaction: TransactionSignaturePayloadTaggedTransactionXDR) {
    self.networkId = networkId
    self.taggedTransaction = taggedTransaction
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    networkId = try container.decode(HashXDR.self)
    taggedTransaction = try container.decode(TransactionSignaturePayloadTaggedTransactionXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(networkId)
    try container.encode(taggedTransaction)
  }
}
