// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct TransactionResultSetXDR: XDRCodable, Sendable {
  public var results: [TransactionResultPairXDR]

  public init(results: [TransactionResultPairXDR]) {
    self.results = results
  }

  public init(from decoder: Decoder) throws {
    results = try decodeArray(type: TransactionResultPairXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(results)
  }
}
