// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct TransactionMetaV3XDR: XDRCodable, Sendable {
  public var ext: ExtensionPoint
  public var txChangesBefore: LedgerEntryChangesXDR
  public var operations: [OperationMetaXDR]
  public var txChangesAfter: LedgerEntryChangesXDR
  public var sorobanMeta: SorobanTransactionMetaXDR?

  public init(
    ext: ExtensionPoint,
    txChangesBefore: LedgerEntryChangesXDR,
    operations: [OperationMetaXDR],
    txChangesAfter: LedgerEntryChangesXDR,
    sorobanMeta: SorobanTransactionMetaXDR? = nil
  ) {
    self.ext = ext
    self.txChangesBefore = txChangesBefore
    self.operations = operations
    self.txChangesAfter = txChangesAfter
    self.sorobanMeta = sorobanMeta
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    ext = try container.decode(ExtensionPoint.self)
    txChangesBefore = try container.decode(LedgerEntryChangesXDR.self)
    operations = try decodeArray(type: OperationMetaXDR.self, dec: decoder)
    txChangesAfter = try container.decode(LedgerEntryChangesXDR.self)
    let sorobanMetaPresent = try container.decode(Int32.self)
    if sorobanMetaPresent != 0 {
      sorobanMeta = try container.decode(SorobanTransactionMetaXDR.self)
    } else {
      sorobanMeta = nil
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(ext)
    try container.encode(txChangesBefore)
    try container.encode(operations)
    try container.encode(txChangesAfter)
    if let val = sorobanMeta {
      try container.encode(Int32(1))
      try container.encode(val)
    } else {
      try container.encode(Int32(0))
    }
  }
}

extension TransactionMetaV3XDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "ext", value: try self.ext.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "tx_changes_before", value: try self.txChangesBefore.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "operations", value: try XdrJson.array(self.operations.map { element in try element.toXdrJsonValue() })))
    members.append(XdrJsonMember(key: "tx_changes_after", value: try self.txChangesAfter.toXdrJsonValue()))
    members.append(XdrJsonMember(key: "soroban_meta", value: try XdrJson.optional(self.sorobanMeta.map { element in try element.toXdrJsonValue() })))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> TransactionMetaV3XDR {
    let members = try XdrJson.object(value, type: "TransactionMetaV3XDR", keys: ["ext", "tx_changes_before", "operations", "tx_changes_after", "soroban_meta"])
    let ext: ExtensionPoint = try ExtensionPoint.fromXdrJsonValue(try XdrJson.field(members, key: "ext", type: "TransactionMetaV3XDR"))
    let txChangesBefore: LedgerEntryChangesXDR = try LedgerEntryChangesXDR.fromXdrJsonValue(try XdrJson.field(members, key: "tx_changes_before", type: "TransactionMetaV3XDR"))
    let operationsElements = try XdrJson.array(try XdrJson.field(members, key: "operations", type: "TransactionMetaV3XDR"), type: "TransactionMetaV3XDR", key: "operations")
    let operations: [OperationMetaXDR] = try operationsElements.map { element in try OperationMetaXDR.fromXdrJsonValue(element) }
    let txChangesAfter: LedgerEntryChangesXDR = try LedgerEntryChangesXDR.fromXdrJsonValue(try XdrJson.field(members, key: "tx_changes_after", type: "TransactionMetaV3XDR"))
    let sorobanMetaValue = try XdrJson.field(members, key: "soroban_meta", type: "TransactionMetaV3XDR")
    let sorobanMeta: SorobanTransactionMetaXDR?
    if sorobanMetaValue.isNull {
      sorobanMeta = nil
    } else {
      sorobanMeta = try SorobanTransactionMetaXDR.fromXdrJsonValue(sorobanMetaValue)
    }
    return TransactionMetaV3XDR(
      ext: ext,
      txChangesBefore: txChangesBefore,
      operations: operations,
      txChangesAfter: txChangesAfter,
      sorobanMeta: sorobanMeta
    )
  }
}
