// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum TransactionMetaXDR: XDRCodable, Sendable {
  case operations([OperationMetaXDR])
  case transactionMetaV1(TransactionMetaV1XDR)
  case transactionMetaV2(TransactionMetaV2XDR)
  case transactionMetaV3(TransactionMetaV3XDR)
  case transactionMetaV4(TransactionMetaV4XDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case 0:
      let val = try decodeArray(type: OperationMetaXDR.self, dec: decoder)
      self = .operations(val)
    case 1:
      let val = try container.decode(TransactionMetaV1XDR.self)
      self = .transactionMetaV1(val)
    case 2:
      let val = try container.decode(TransactionMetaV2XDR.self)
      self = .transactionMetaV2(val)
    case 3:
      let val = try container.decode(TransactionMetaV3XDR.self)
      self = .transactionMetaV3(val)
    case 4:
      let val = try container.decode(TransactionMetaV4XDR.self)
      self = .transactionMetaV4(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown TransactionMetaXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .operations: return 0
    case .transactionMetaV1: return 1
    case .transactionMetaV2: return 2
    case .transactionMetaV3: return 3
    case .transactionMetaV4: return 4
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .operations(let val):
      try container.encode(val)
    case .transactionMetaV1(let val):
      try container.encode(val)
    case .transactionMetaV2(let val):
      try container.encode(val)
    case .transactionMetaV3(let val):
      try container.encode(val)
    case .transactionMetaV4(let val):
      try container.encode(val)
    }
  }
}

extension TransactionMetaXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .operations(let payload):
      return .object([XdrJsonMember(key: "v0", value: try XdrJson.array(payload.map { element in try element.toXdrJsonValue() }))])
    case .transactionMetaV1(let payload):
      return .object([XdrJsonMember(key: "v1", value: try payload.toXdrJsonValue())])
    case .transactionMetaV2(let payload):
      return .object([XdrJsonMember(key: "v2", value: try payload.toXdrJsonValue())])
    case .transactionMetaV3(let payload):
      return .object([XdrJsonMember(key: "v3", value: try payload.toXdrJsonValue())])
    case .transactionMetaV4(let payload):
      return .object([XdrJsonMember(key: "v4", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> TransactionMetaXDR {
    if case .string(let name) = value {
      switch name {
      case "v0":
        throw XdrJsonError.invalidValue(type: "TransactionMetaXDR", key: "v0",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "v1":
        throw XdrJsonError.invalidValue(type: "TransactionMetaXDR", key: "v1",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "v2":
        throw XdrJsonError.invalidValue(type: "TransactionMetaXDR", key: "v2",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "v3":
        throw XdrJsonError.invalidValue(type: "TransactionMetaXDR", key: "v3",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "v4":
        throw XdrJsonError.invalidValue(type: "TransactionMetaXDR", key: "v4",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "TransactionMetaXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "TransactionMetaXDR")
    switch member.key {
    case "v0":
      let operationsElements = try XdrJson.array(member.value, type: "TransactionMetaXDR", key: "v0")
      let operations: [OperationMetaXDR] = try operationsElements.map { element in try OperationMetaXDR.fromXdrJsonValue(element) }
      return .operations(operations)
    case "v1":
      let transactionMetaV1: TransactionMetaV1XDR = try TransactionMetaV1XDR.fromXdrJsonValue(member.value)
      return .transactionMetaV1(transactionMetaV1)
    case "v2":
      let transactionMetaV2: TransactionMetaV2XDR = try TransactionMetaV2XDR.fromXdrJsonValue(member.value)
      return .transactionMetaV2(transactionMetaV2)
    case "v3":
      let transactionMetaV3: TransactionMetaV3XDR = try TransactionMetaV3XDR.fromXdrJsonValue(member.value)
      return .transactionMetaV3(transactionMetaV3)
    case "v4":
      let transactionMetaV4: TransactionMetaV4XDR = try TransactionMetaV4XDR.fromXdrJsonValue(member.value)
      return .transactionMetaV4(transactionMetaV4)
    default:
      throw XdrJsonError.unknownUnionArm(type: "TransactionMetaXDR", key: member.key)
    }
  }
}
