// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct TransactionSignaturePayload: XDRCodable, Sendable {
  public var networkId: HashXDR
  public var taggedTransaction: TransactionSignaturePayloadTaggedTransactionXDR

  public init(networkId: HashXDR, taggedTransaction: TransactionSignaturePayloadTaggedTransactionXDR) {
    self.networkId = networkId
    self.taggedTransaction = taggedTransaction
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    networkId = try container.decode(HashXDR.self)
    taggedTransaction = try container.decode(TransactionSignaturePayloadTaggedTransactionXDR.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(networkId)
    try container.encode(taggedTransaction)
  }
}

extension TransactionSignaturePayload: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    var members: [XdrJsonMember] = []
    members.append(XdrJsonMember(key: "network_id", value: try HashXDRJsonCodec.toXdrJsonValue(self.networkId, type: "TransactionSignaturePayload", key: "network_id")))
    members.append(XdrJsonMember(key: "tagged_transaction", value: try self.taggedTransaction.toXdrJsonValue()))
    return .object(members)
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> TransactionSignaturePayload {
    let members = try XdrJson.object(value, type: "TransactionSignaturePayload", keys: ["network_id", "tagged_transaction"])
    let networkId: HashXDR = try HashXDRJsonCodec.fromXdrJsonValue(try XdrJson.field(members, key: "network_id", type: "TransactionSignaturePayload"), type: "TransactionSignaturePayload", key: "network_id")
    let taggedTransaction: TransactionSignaturePayloadTaggedTransactionXDR = try TransactionSignaturePayloadTaggedTransactionXDR.fromXdrJsonValue(try XdrJson.field(members, key: "tagged_transaction", type: "TransactionSignaturePayload"))
    return TransactionSignaturePayload(networkId: networkId, taggedTransaction: taggedTransaction)
  }
}
