// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum TrustlineAssetXDR: XDRCodable, Sendable {
  case native
  case alphanum4(Alpha4XDR)
  case alphanum12(Alpha12XDR)
  case poolShare(WrappedData32)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case AssetType.native.rawValue:
      self = .native
    case AssetType.creditAlphanum4.rawValue:
      let val = try container.decode(Alpha4XDR.self)
      self = .alphanum4(val)
    case AssetType.creditAlphanum12.rawValue:
      let val = try container.decode(Alpha12XDR.self)
      self = .alphanum12(val)
    case AssetType.poolShare.rawValue:
      let val = try container.decode(WrappedData32.self)
      self = .poolShare(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown TrustlineAssetXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .native: return AssetType.native.rawValue
    case .alphanum4: return AssetType.creditAlphanum4.rawValue
    case .alphanum12: return AssetType.creditAlphanum12.rawValue
    case .poolShare: return AssetType.poolShare.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .native:
      break
    case .alphanum4(let val):
      try container.encode(val)
    case .alphanum12(let val):
      try container.encode(val)
    case .poolShare(let val):
      try container.encode(val)
    }
  }
}

extension TrustlineAssetXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .native: return .string("native")
    case .alphanum4(let payload):
      return .object([XdrJsonMember(key: "credit_alphanum4", value: try payload.toXdrJsonValue())])
    case .alphanum12(let payload):
      return .object([XdrJsonMember(key: "credit_alphanum12", value: try payload.toXdrJsonValue())])
    case .poolShare(let payload):
      return .object([XdrJsonMember(key: "pool_share", value: try PoolIDXDRJsonCodec.toXdrJsonValue(payload, type: "TrustlineAssetXDR", key: "pool_share"))])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> TrustlineAssetXDR {
    if case .string(let name) = value {
      switch name {
      case "native":
        return .native
      case "credit_alphanum4":
        throw XdrJsonError.invalidValue(type: "TrustlineAssetXDR", key: "credit_alphanum4",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "credit_alphanum12":
        throw XdrJsonError.invalidValue(type: "TrustlineAssetXDR", key: "credit_alphanum12",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "pool_share":
        throw XdrJsonError.invalidValue(type: "TrustlineAssetXDR", key: "pool_share",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "TrustlineAssetXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "TrustlineAssetXDR")
    switch member.key {
    case "native":
      throw XdrJsonError.invalidValue(type: "TrustlineAssetXDR", key: "native",
                                      message: "this arm carries no value, so it is written as a bare string")
    case "credit_alphanum4":
      let alphanum4: Alpha4XDR = try Alpha4XDR.fromXdrJsonValue(member.value)
      return .alphanum4(alphanum4)
    case "credit_alphanum12":
      let alphanum12: Alpha12XDR = try Alpha12XDR.fromXdrJsonValue(member.value)
      return .alphanum12(alphanum12)
    case "pool_share":
      let poolShare: WrappedData32 = try PoolIDXDRJsonCodec.fromXdrJsonValue(member.value, type: "TrustlineAssetXDR", key: "pool_share")
      return .poolShare(poolShare)
    default:
      throw XdrJsonError.unknownUnionArm(type: "TrustlineAssetXDR", key: member.key)
    }
  }
}
