// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum TxSetComponentXDR: XDRCodable, Sendable {
  case txsMaybeDiscountedFee(TxSetComponentXDRTxsMaybeDiscountedFeeXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case TxSetComponentTypeXDR.txsetCompTxsMaybeDiscountedFee.rawValue:
      let val = try container.decode(TxSetComponentXDRTxsMaybeDiscountedFeeXDR.self)
      self = .txsMaybeDiscountedFee(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown TxSetComponentXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .txsMaybeDiscountedFee: return TxSetComponentTypeXDR.txsetCompTxsMaybeDiscountedFee.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .txsMaybeDiscountedFee(let val):
      try container.encode(val)
    }
  }
}
