// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum TxSetComponentXDR: XDRCodable, Sendable {
  case txsMaybeDiscountedFee(TxSetComponentXDRTxsMaybeDiscountedFeeXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case TxSetComponentTypeXDR.txsetCompTxsMaybeDiscountedFee.rawValue:
      let val = try container.decode(TxSetComponentXDRTxsMaybeDiscountedFeeXDR.self)
      self = .txsMaybeDiscountedFee(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown TxSetComponentXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .txsMaybeDiscountedFee: return TxSetComponentTypeXDR.txsetCompTxsMaybeDiscountedFee.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .txsMaybeDiscountedFee(let val):
      try container.encode(val)
    }
  }
}

extension TxSetComponentXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .txsMaybeDiscountedFee(let payload):
      return .object([XdrJsonMember(key: "txset_comp_txs_maybe_discounted_fee", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> TxSetComponentXDR {
    if case .string(let name) = value {
      switch name {
      case "txset_comp_txs_maybe_discounted_fee":
        throw XdrJsonError.invalidValue(type: "TxSetComponentXDR", key: "txset_comp_txs_maybe_discounted_fee",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "TxSetComponentXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "TxSetComponentXDR")
    switch member.key {
    case "txset_comp_txs_maybe_discounted_fee":
      let txsMaybeDiscountedFee: TxSetComponentXDRTxsMaybeDiscountedFeeXDR = try TxSetComponentXDRTxsMaybeDiscountedFeeXDR.fromXdrJsonValue(member.value)
      return .txsMaybeDiscountedFee(txsMaybeDiscountedFee)
    default:
      throw XdrJsonError.unknownUnionArm(type: "TxSetComponentXDR", key: member.key)
    }
  }
}
