//
// This file was generated by stellar_contract_bindings v0.5.0b0
// and stellar_sdk v13.0.0.
//
// This code requires stellar-ios-mac-sdk (Soneso) v3.1.0 or later.
//
// @generated
//


import Foundation
import stellarsdk


/// Generated union OptionShapesContractOptUnion
public enum OptionShapesContractOptUnion: Codable {
    case Nothing
    case Maybe(UInt32?)

    public func toSCVal() throws -> SCValXDR {
        switch self {
        case .Nothing:
            return .vec([.symbol("Nothing")])
        case .Maybe(let value):
            return .vec([
                .symbol("Maybe"),
                (value != nil ? SCValXDR.u32(value!) : SCValXDR.void)
            ])
        }
    }

    /// Converts an SCVal XDR value to a OptionShapesContractOptUnion union
    /// - Parameter val: The SCVal to convert (must be a vec with discriminant as first element)
    /// - Returns: The corresponding OptionShapesContractOptUnion case
    /// - Throws: OptionShapesContractError.conversionFailed if:
    ///   - The SCVal is not a vec
    ///   - The vec is empty or missing the discriminant
    ///   - The discriminant is not a symbol or is unknown
    ///   - The number of elements doesn't match the expected case
    public static func fromSCVal(_ val: SCValXDR) throws -> OptionShapesContractOptUnion {
        guard case .vec(let vec) = val, let vec = vec, vec.count >= 1 else {
            throw OptionShapesContractError.conversionFailed(message: "Invalid union value: expected vec with at least 1 element")
        }

        guard case .symbol(let kind) = vec[0] else {
            throw OptionShapesContractError.conversionFailed(message: "Invalid union discriminant")
        }

        switch kind {
        case "Nothing":
            return .Nothing
        case "Maybe":
            guard vec.count == 2 else {
                throw OptionShapesContractError.conversionFailed(message: "Invalid union value for Maybe: expected 2 elements")
            }
            return .Maybe((vec[1].isVoid ? nil : try vec[1].u32 ?? { throw OptionShapesContractError.conversionFailed(message: "Missing or invalid u32 value") }()))
        default:
            throw OptionShapesContractError.conversionFailed(message: "Unknown union kind: \(kind)")
        }
    }
}

/// Generated struct OptionShapesContractMaybeStruct
public struct OptionShapesContractMaybeStruct: Codable {
    public let flag: UInt32
    public let maybe: UInt32?

    public init(
        flag: UInt32,
        maybe: UInt32?
    ) {
        self.flag = flag
        self.maybe = maybe
    }

    public func toSCVal() throws -> SCValXDR {
        var mapEntries: [SCMapEntryXDR] = []
        mapEntries.append(SCMapEntryXDR(
            key: .symbol("flag"),
            val: SCValXDR.u32(flag)
        ))
        mapEntries.append(SCMapEntryXDR(
            key: .symbol("maybe"),
            val: (maybe != nil ? SCValXDR.u32(maybe!) : SCValXDR.void)
        ))
        return .map(mapEntries)
    }

    /// Converts an SCVal XDR value to a OptionShapesContractMaybeStruct struct
    /// - Parameter val: The SCVal to convert (must be a map)
    /// - Returns: A new OptionShapesContractMaybeStruct instance
    /// - Throws: OptionShapesContractError.conversionFailed if the SCVal is not a map or required fields are missing
    public static func fromSCVal(_ val: SCValXDR) throws -> OptionShapesContractMaybeStruct {
        guard case .map(let mapEntries) = val else {
            throw OptionShapesContractError.conversionFailed(message: "Invalid SCVal type for OptionShapesContractMaybeStruct")
        }

        var map: [String: SCValXDR] = [:]
        for entry in mapEntries ?? [] {
            if case .symbol(let key) = entry.key {
                map[key] = entry.val
            }
        }
        guard let field_0_val = map["flag"] else {
            throw OptionShapesContractError.conversionFailed(message: "Missing required field 'flag' in OptionShapesContractMaybeStruct")
        }
        guard let field_1_val = map["maybe"] else {
            throw OptionShapesContractError.conversionFailed(message: "Missing required field 'maybe' in OptionShapesContractMaybeStruct")
        }

        return OptionShapesContractMaybeStruct(
            flag: try field_0_val.u32 ?? { throw OptionShapesContractError.conversionFailed(message: "Missing or invalid u32 value") }(),
            maybe: (field_1_val.isVoid ? nil : try field_1_val.u32 ?? { throw OptionShapesContractError.conversionFailed(message: "Missing or invalid u32 value") }())
        )
    }
}

/// Generated contract client for OptionShapesContract
public class OptionShapesContract {

    /// The underlying SorobanClient instance
    private let client: SorobanClient

    /// Private constructor that wraps a SorobanClient
    private init(client: SorobanClient) {
        self.client = client
    }

    /// Creates a new OptionShapesContract for the given client options
    /// - Parameter options: Client options for the contract
    /// - Returns: A new OptionShapesContract instance
    public static func forClientOptions(options: ClientOptions) async throws -> OptionShapesContract {
        let client = try await SorobanClient.forClientOptions(options: options)
        return OptionShapesContract(client: client)
    }

    /// Gets the contract ID
    /// - Returns: The contract ID as a string
    public var contractId: String {
        return client.contractId
    }

    /// Gets the spec entries of the contract
    /// - Returns: Array of SCSpecEntryXDR
    public var specEntries: [SCSpecEntryXDR] {
        return client.specEntries
    }

    /// Gets the method names of the contract
    /// - Returns: Array of method names
    public var methodNames: [String] {
        return client.methodNames
    }

    /// Invoke the default method
    ///
    /// - Parameter value: UInt32
    /// - Parameter methodOptions: Options for transaction (optional)
    /// - Parameter force: Force signing and sending even if it's a read call (default: false)
    /// - Returns: UInt32
    public func `default`(
        value: UInt32,
        methodOptions: MethodOptions? = nil,
        force: Bool = false
    ) async throws -> UInt32 {
        let args: [SCValXDR] = [
            SCValXDR.u32(value)
        ]

        let result = try await client.invokeMethod(
            name: "default",
            args: args,
            force: force,
            methodOptions: methodOptions
        )
        return try result.u32 ?? { throw OptionShapesContractError.conversionFailed(message: "Missing or invalid u32 value") }()
    }

    /// Build an AssembledTransaction for the default method.
    /// This is useful if you need to manipulate the transaction before signing and sending.
    ///
    /// - Parameter value: UInt32
    /// - Parameter methodOptions: Options for transaction (optional)
    /// - Returns: AssembledTransaction
    public func buildDefaultTx(
        value: UInt32,
        methodOptions: MethodOptions? = nil
    ) async throws -> AssembledTransaction {
        let args: [SCValXDR] = [
            SCValXDR.u32(value)
        ]

        return try await client.buildInvokeMethodTx(
            name: "default",
            args: args,
            methodOptions: methodOptions
        )
    }

    /// Invoke the opt_map method
    ///
    /// - Parameter map: [UInt32: UInt32?]
    /// - Parameter methodOptions: Options for transaction (optional)
    /// - Parameter force: Force signing and sending even if it's a read call (default: false)
    /// - Returns: [UInt32: UInt32?]
    public func optMap(
        map: [UInt32: UInt32?],
        methodOptions: MethodOptions? = nil,
        force: Bool = false
    ) async throws -> [UInt32: UInt32?] {
        let args: [SCValXDR] = [
            SCValXDR.map(map.sorted(by: { $0.key < $1.key }).map { SCMapEntryXDR(key: SCValXDR.u32($0.key), val: ($0.value != nil ? SCValXDR.u32($0.value!) : SCValXDR.void)) })
        ]

        let result = try await client.invokeMethod(
            name: "opt_map",
            args: args,
            force: force,
            methodOptions: methodOptions
        )
        return try Dictionary(uniqueKeysWithValues: result.map?.compactMap { (try $0.key.u32 ?? { throw OptionShapesContractError.conversionFailed(message: "Missing or invalid u32 value") }(), ($0.val.isVoid ? nil : try $0.val.u32 ?? { throw OptionShapesContractError.conversionFailed(message: "Missing or invalid u32 value") }())) } ?? [])
    }

    /// Build an AssembledTransaction for the opt_map method.
    /// This is useful if you need to manipulate the transaction before signing and sending.
    ///
    /// - Parameter map: [UInt32: UInt32?]
    /// - Parameter methodOptions: Options for transaction (optional)
    /// - Returns: AssembledTransaction
    public func buildOptMapTx(
        map: [UInt32: UInt32?],
        methodOptions: MethodOptions? = nil
    ) async throws -> AssembledTransaction {
        let args: [SCValXDR] = [
            SCValXDR.map(map.sorted(by: { $0.key < $1.key }).map { SCMapEntryXDR(key: SCValXDR.u32($0.key), val: ($0.value != nil ? SCValXDR.u32($0.value!) : SCValXDR.void)) })
        ]

        return try await client.buildInvokeMethodTx(
            name: "opt_map",
            args: args,
            methodOptions: methodOptions
        )
    }

    /// Invoke the opt_tuple method
    ///
    /// - Parameter tuple: (UInt32?, UInt32)
    /// - Parameter methodOptions: Options for transaction (optional)
    /// - Parameter force: Force signing and sending even if it's a read call (default: false)
    /// - Returns: (UInt32?, UInt32)
    public func optTuple(
        tuple: (UInt32?, UInt32),
        methodOptions: MethodOptions? = nil,
        force: Bool = false
    ) async throws -> (UInt32?, UInt32) {
        let args: [SCValXDR] = [
            SCValXDR.vec([(tuple.0 != nil ? SCValXDR.u32(tuple.0!) : SCValXDR.void), SCValXDR.u32(tuple.1)])
        ]

        let result = try await client.invokeMethod(
            name: "opt_tuple",
            args: args,
            force: force,
            methodOptions: methodOptions
        )
        return ((result.vec![0].isVoid ? nil : try result.vec![0].u32 ?? { throw OptionShapesContractError.conversionFailed(message: "Missing or invalid u32 value") }()), try result.vec![1].u32 ?? { throw OptionShapesContractError.conversionFailed(message: "Missing or invalid u32 value") }())
    }

    /// Build an AssembledTransaction for the opt_tuple method.
    /// This is useful if you need to manipulate the transaction before signing and sending.
    ///
    /// - Parameter tuple: (UInt32?, UInt32)
    /// - Parameter methodOptions: Options for transaction (optional)
    /// - Returns: AssembledTransaction
    public func buildOptTupleTx(
        tuple: (UInt32?, UInt32),
        methodOptions: MethodOptions? = nil
    ) async throws -> AssembledTransaction {
        let args: [SCValXDR] = [
            SCValXDR.vec([(tuple.0 != nil ? SCValXDR.u32(tuple.0!) : SCValXDR.void), SCValXDR.u32(tuple.1)])
        ]

        return try await client.buildInvokeMethodTx(
            name: "opt_tuple",
            args: args,
            methodOptions: methodOptions
        )
    }

    /// Invoke the opt_union method
    ///
    /// - Parameter union: OptionShapesContractOptUnion
    /// - Parameter methodOptions: Options for transaction (optional)
    /// - Parameter force: Force signing and sending even if it's a read call (default: false)
    /// - Returns: OptionShapesContractOptUnion
    public func optUnion(
        union: OptionShapesContractOptUnion,
        methodOptions: MethodOptions? = nil,
        force: Bool = false
    ) async throws -> OptionShapesContractOptUnion {
        let args: [SCValXDR] = [
            try union.toSCVal()
        ]

        let result = try await client.invokeMethod(
            name: "opt_union",
            args: args,
            force: force,
            methodOptions: methodOptions
        )
        return try OptionShapesContractOptUnion.fromSCVal(result)
    }

    /// Build an AssembledTransaction for the opt_union method.
    /// This is useful if you need to manipulate the transaction before signing and sending.
    ///
    /// - Parameter union: OptionShapesContractOptUnion
    /// - Parameter methodOptions: Options for transaction (optional)
    /// - Returns: AssembledTransaction
    public func buildOptUnionTx(
        union: OptionShapesContractOptUnion,
        methodOptions: MethodOptions? = nil
    ) async throws -> AssembledTransaction {
        let args: [SCValXDR] = [
            try union.toSCVal()
        ]

        return try await client.buildInvokeMethodTx(
            name: "opt_union",
            args: args,
            methodOptions: methodOptions
        )
    }

    /// Invoke the opt_strukt method
    ///
    /// - Parameter strukt: OptionShapesContractMaybeStruct
    /// - Parameter methodOptions: Options for transaction (optional)
    /// - Parameter force: Force signing and sending even if it's a read call (default: false)
    /// - Returns: OptionShapesContractMaybeStruct
    public func optStrukt(
        strukt: OptionShapesContractMaybeStruct,
        methodOptions: MethodOptions? = nil,
        force: Bool = false
    ) async throws -> OptionShapesContractMaybeStruct {
        let args: [SCValXDR] = [
            try strukt.toSCVal()
        ]

        let result = try await client.invokeMethod(
            name: "opt_strukt",
            args: args,
            force: force,
            methodOptions: methodOptions
        )
        return try OptionShapesContractMaybeStruct.fromSCVal(result)
    }

    /// Build an AssembledTransaction for the opt_strukt method.
    /// This is useful if you need to manipulate the transaction before signing and sending.
    ///
    /// - Parameter strukt: OptionShapesContractMaybeStruct
    /// - Parameter methodOptions: Options for transaction (optional)
    /// - Returns: AssembledTransaction
    public func buildOptStruktTx(
        strukt: OptionShapesContractMaybeStruct,
        methodOptions: MethodOptions? = nil
    ) async throws -> AssembledTransaction {
        let args: [SCValXDR] = [
            try strukt.toSCVal()
        ]

        return try await client.buildInvokeMethodTx(
            name: "opt_strukt",
            args: args,
            methodOptions: methodOptions
        )
    }
}

// MARK: - Error Types

/// Custom errors for OptionShapesContract operations
/// These errors are thrown when:
/// - Converting between Swift types and SCVal XDR types fails
/// - Type validation fails during deserialization
/// - Contract invocation fails
enum OptionShapesContractError: Error {
    /// Thrown when converting from SCVal to Swift types fails.
    /// This typically happens when:
    /// - The SCVal type doesn't match the expected type
    /// - Required fields are missing in structs
    /// - Union discriminants are unknown
    /// - Enum values are out of range
    case conversionFailed(message: String)

    /// Thrown when a contract method invocation fails.
    /// This can happen when:
    /// - The contract returns an error
    /// - The transaction fails to submit
    /// - Network or RPC errors occur
    case invokeFailed(message: String)
}
