"""Hand-authored seeds for the SEP-0051 (XDR-JSON) conformance corpus.

Each seed is a dict:

  type        Reference CLI type name (ScVal), the spelling `stellar-xdr` uses.
  ios_type    SDK type name (SCValXDR). `../sep-51-oracle/type_map.json` is the
              sole authority on the pairing; the two spellings differ in acronym
              case, in the reserved-name escape and in this SDK's XDR suffix, and
              a missing mapping fails the run rather than falling back to a guess.
  json        The value written in the reference's own XDR-JSON form. The corpus
              generator encodes it with the reference CLI, so a document that is
              not valid XDR-JSON for that type fails the build.
  note        One sentence naming the shape the seed pins.
  oracle      Optional. "incomparable" marks a rendering where the SDK follows
              SEP-0051 and the reference does not; such a seed also carries
              spec_form and spec_form_paths. "spec" marks a value the pinned
              reference cannot resolve at all, which the generator admits only
              for a name the oracle's own unresolvable list carries.
  spec_form   Required with "incomparable". Names the transformation the
              generator applies to the reference's output to derive what the SDK
              must emit: "integer_string" or "opaque_hex".
  spec_form_paths
              Required with "incomparable", with no exemption. The JSON paths the
              transformation is expected to rewrite, dotted for object keys and
              [n] for array indices; the empty string names the whole document,
              which is what integer_string rewrites. A union arm key is an
              ordinary object key, so "ip.i_pv4" addresses an arm payload. A seed
              whose transformation rewrites nothing declares the empty list; an
              omitted field is a generation failure, not a default. The generator
              fails when the declared set and the rewritten set differ in either
              direction, because that is where the byte-array heuristic has caught
              an integer array that is not opaque data.
  input_variants
              Optional. Further JSON documents that must decode to the same XDR.
              The corpus records what the SDK emits and the reference emits one
              spelling per key, so an accepted alternative spelling cannot arrive
              through the normal path; a variant is verified by encoding it with
              the reference and requiring the same base64, which keeps it
              oracle-verified. Incomparable seeds may not carry variants.
  non_utf8_paths
              Optional. The JSON paths, in the syntax spec_form_paths uses, whose
              escape-ladder bytes are deliberately not valid UTF-8. Admissible
              only where the field is opaque and therefore byte-exact; see the
              UTF-8 rule below. The generator fails when the declared set and the
              set it finds differ in either direction.

A seed value that lands in an XDR `string<>` field must be valid UTF-8 once the
escape ladder is resolved. This SDK models every `string<>` as a Swift `String`,
which is guaranteed well-formed Unicode, so a lone continuation or lead byte can
be round-tripped by the reference but cannot be constructed, decoded or held
here. Opaque fields are unaffected: they are backed by `Data` or `WrappedDataN`
and are byte-exact, which is why the asset codes may carry a bare `\xc3` and
declare it through non_utf8_paths.

No seed may carry a `$schema` property anywhere. The corpus is built by encoding
each seed with the reference, which rejects that property, so such a seed fails
with an error that reads like an SDK bug rather than a reference limitation.
`$schema` acceptance is pinned by a hand-written test instead.

Seeds cover the renderings that are not mechanical: every arm of the unions
whose JSON form is a strkey or a bare name, the integer types rendered as
strings, the SEP-0051 escape ladder over bytes-typed and string-typed fields,
empty and populated variable-length data, optionals in both states, and the
name rules that a pin bump could disturb. They also cover the overlay, internal
and exporter definitions, which this SDK generates and which carry the address
family enum, the reserved-name type escape and a union with inline opaque arms.

A SignerKeyEd25519SignedPayload with a zero-length payload is deliberately
absent: the reference decodes it to a strkey it then refuses to encode, so it
cannot round-trip through the generator. That input is pinned by a hand-written
negative test instead.

Where several XDR definitions share one Swift type and render differently, the
Swift type is never seeded: only the union arm that selects a definition can
render it, so the pair is seeded through that union. Both sides of every such
pair are present, because a fixture exercising one side cannot see a helper that
emits the other side's names.
"""

# --- Reusable values ---------------------------------------------------------

G1 = "GAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSABOV"
C1 = "CAQCCIRDEQSSMJZIFEVCWLBNFYXTAMJSGM2DKNRXHA4TUOZ4HU7D7V6Z"
M_ZERO_ID = "MAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSAAAAAAAAAAAAAA54K"
M1 = "MAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSAAAAAAAAAAAE2LAOE"
M_MAX_ID = "MAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSB7777777777777NGG"
T1 = "TBAECQSDIRCUMR2IJFFEWTCNJZHVAUKSKNKFKVSXLBMVUW24LVPF7EOJ"
X1 = "XBQGCYTDMRSWMZ3INFVGW3DNNZXXA4LSON2HK5TXPB4XU634PV7H7YJH"
P_SHORT = "PAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSAAAAAACACAQDATYOS"
P_FULL = (
    "PAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSAAAAAAQACAQDAQCQ"
    "MBYIBEFAWDANBYHRAEISCMKBKFQXDAMRUGY4DUPB6IHX7Q"
)
B1 = "BAAACAQDAQCQMBYIBEFAWDANBYHRAEISCMKBKFQXDAMRUGY4DUPB6IHRSE"
L1 = "LCAIDAUDQSCYNB4IRGFIXDENR2HZBEMSSOKJLFUXTCMZVG44TWPJ744M"

HASH1 = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"
HASH_ZERO = "00" * 32

INT64_MIN = "-9223372036854775808"
INT64_MAX = "9223372036854775807"
UINT64_MAX = "18446744073709551615"
INT128_MIN = "-170141183460469231731687303715884105728"
INT128_MAX = "170141183460469231731687303715884105727"
UINT128_MAX = "340282366920938463463374607431768211455"
INT256_MIN = (
    "-578960446186580977117854925043439539266"
    "34992332820282019728792003956564819968"
)
INT256_MAX = (
    "578960446186580977117854925043439539266"
    "34992332820282019728792003956564819967"
)
UINT256_MAX = (
    "115792089237316195423570985008687907853"
    "269984665640564039457584007913129639935"
)

ALPHANUM4 = {"asset_code": "USD", "issuer": G1}
ALPHANUM12 = {"asset_code": "LONGASSET", "issuer": G1}
ASSET_A4 = {"credit_alphanum4": ALPHANUM4}
ASSET_A12 = {"credit_alphanum12": ALPHANUM12}

BYTES_4 = [1, 2, 3, 4]
BYTES_16 = list(range(1, 17))
BYTES_16_ZERO = [0] * 16
BYTES_32 = list(range(1, 33))
BYTES_32_ZERO = [0] * 32

# --- Reusable overlay, SCP and internal values -------------------------------

PEER_STATS = {
    "id": G1, "version_str": "v23.0", "messages_read": "1",
    "messages_written": "2", "bytes_read": "3", "bytes_written": "4",
    "seconds_connected": "5", "unique_flood_bytes_recv": "6",
    "duplicate_flood_bytes_recv": "7", "unique_fetch_bytes_recv": "8",
    "duplicate_fetch_bytes_recv": "9", "unique_flood_message_recv": "10",
    "duplicate_flood_message_recv": "11", "unique_fetch_message_recv": "12",
    "duplicate_fetch_message_recv": "13",
}
NODE_DATA = {
    "added_authenticated_peers": 1, "dropped_authenticated_peers": 2,
    "total_inbound_peer_count": 3, "total_outbound_peer_count": 4,
    "p75_scp_first_to_self_latency_ms": 5, "p75_scp_self_to_other_latency_ms": 6,
    "lost_sync_count": 7, "is_validator": True, "max_inbound_peer_count": 8,
    "max_outbound_peer_count": 9,
}
SURVEY_RESPONSE = {
    "surveyor_peer_id": G1, "surveyed_peer_id": G1, "ledger_num": 7,
    "command_type": "time_sliced_survey_topology", "encrypted_body": "00ff",
}
START_COLLECTING = {"surveyor_id": G1, "nonce": 1, "ledger_num": 2}
STOP_COLLECTING = {"surveyor_id": G1, "nonce": 4294967295, "ledger_num": 0}

SCP_BALLOT = {"counter": 1, "value": "0a0b"}
SCP_NOMINATION = {"quorum_set_hash": HASH1, "votes": [], "accepted": []}
SCP_QUORUM_SET = {"threshold": 1, "validators": [G1], "inner_sets": []}
SCP_STATEMENT = {"node_id": G1, "slot_index": "7",
                 "pledges": {"nominate": SCP_NOMINATION}}
SCP_ENVELOPE = {"statement": SCP_STATEMENT, "signature": "0a0b"}
TX_SET_V0 = {"previous_ledger_hash": HASH1, "txs": []}
TX_ENVELOPE_V0 = {"tx_v0": {"tx": {"source_account_ed25519": HASH1, "fee": 100,
                                   "seq_num": "1", "time_bounds": None,
                                   "memo": "none", "operations": [],
                                   "ext": "v0"},
                            "signatures": []}}

SIMPLE_PAYMENT_RESULT = {"destination": G1, "asset": ASSET_A4, "amount": "5"}


def _seed(type_name, ios_type, json_value, note, oracle=None, spec_form=None,
          spec_form_paths=None, input_variants=None, non_utf8_paths=None,
          xdr=None):
    seed = {
        "type": type_name,
        "ios_type": ios_type,
        "json": json_value,
        "note": note,
    }
    if oracle is not None:
        seed["oracle"] = oracle
    if spec_form is not None:
        seed["spec_form"] = spec_form
    if spec_form_paths is not None:
        seed["spec_form_paths"] = spec_form_paths
    if input_variants is not None:
        seed["input_variants"] = input_variants
    if non_utf8_paths is not None:
        seed["non_utf8_paths"] = non_utf8_paths
    if xdr is not None:
        seed["xdr"] = xdr
    return seed


SEEDS = [
    # --- SCAddress: one strkey prefix per arm -------------------------------
    _seed("ScAddress", "SCAddressXDR", G1,
          "Account arm renders as a G strkey."),
    _seed("ScAddress", "SCAddressXDR", C1,
          "Contract arm renders as a C strkey."),
    _seed("ScAddress", "SCAddressXDR", M1,
          "Muxed account arm renders as an M strkey carrying the id."),
    _seed("ScAddress", "SCAddressXDR", M_ZERO_ID,
          "Muxed account arm with id zero keeps the M form."),
    _seed("ScAddress", "SCAddressXDR", B1,
          "Claimable balance arm renders as a B strkey."),
    _seed("ScAddress", "SCAddressXDR", L1,
          "Liquidity pool arm renders as an L strkey."),

    # --- SignerKey: one strkey prefix per arm -------------------------------
    _seed("SignerKey", "SignerKeyXDR", G1,
          "Ed25519 signer renders as a G strkey."),
    _seed("SignerKey", "SignerKeyXDR", T1,
          "Pre-authorized transaction signer renders as a T strkey."),
    _seed("SignerKey", "SignerKeyXDR", X1,
          "Hash-x signer renders as an X strkey."),
    _seed("SignerKey", "SignerKeyXDR", P_SHORT,
          "Signed payload signer with a four-byte payload renders as a P strkey."),
    _seed("SignerKey", "SignerKeyXDR", P_FULL,
          "Signed payload signer at the 32-byte payload limit renders as a P strkey."),

    # --- MuxedAccount, PublicKey, ClaimableBalanceID ------------------------
    _seed("MuxedAccount", "MuxedAccountXDR", G1,
          "Unmuxed arm renders as a G strkey."),
    _seed("MuxedAccount", "MuxedAccountXDR", M1,
          "Muxed arm folds the id into an M strkey."),
    _seed("MuxedAccount", "MuxedAccountXDR", M_MAX_ID,
          "Muxed arm carries the maximum 64-bit id."),
    _seed("PublicKey", "PublicKey", G1,
          "Sole public key arm renders as a G strkey, not an object."),
    _seed("AccountId", "AccountIDXDR", G1,
          "Account id typedef renders as the wrapped public key."),
    _seed("NodeId", "NodeIDXDR", G1,
          "Node id typedef renders as the wrapped public key."),
    _seed("ClaimableBalanceId", "ClaimableBalanceIDXDR", B1,
          "Sole claimable balance id arm renders as a B strkey."),
    _seed("PoolId", "PoolIDXDR", L1,
          "Pool id typedef renders as an L strkey."),

    # --- AssetCode: the union renders as a bare string ----------------------
    _seed("AssetCode", "AllowTrustOpAssetXDR", "USD",
          "Four-byte arm of the asset code union renders as a bare string."),
    _seed("AssetCode", "AllowTrustOpAssetXDR", "LONGASSET",
          "Twelve-byte arm of the asset code union renders as a bare string."),

    # --- AssetCode4 and AssetCode12: the escape ladder over raw bytes -------
    _seed("AssetCode4", "AssetCode4XDR", "A",
          "One-character asset code drops its three padding bytes."),
    _seed("AssetCode4", "AssetCode4XDR", "ABC",
          "Three-character asset code drops its single padding byte."),
    _seed("AssetCode4", "AssetCode4XDR", "ABCD",
          "Four-character asset code fills the field exactly."),
    _seed("AssetCode4", "AssetCode4XDR", "\\xc3",
          "Asset code holding a non-ASCII byte escapes it as \\xNN.",
          non_utf8_paths=[""]),
    _seed("AssetCode4", "AssetCode4XDR", "a\\\\b",
          "Backslash inside a four-byte asset code doubles."),
    _seed("AssetCode12", "AssetCode12XDR", "ABC",
          "Three-character twelve-byte asset code keeps its short form."),
    _seed("AssetCode12", "AssetCode12XDR", "ABCDE",
          "Five-character asset code sits at the twelve-byte floor."),
    _seed("AssetCode12", "AssetCode12XDR", "ABCDEFGH",
          "Eight-character twelve-byte asset code drops four padding bytes."),
    _seed("AssetCode12", "AssetCode12XDR", "ABCDEFGHIJKL",
          "Twelve-character asset code fills the field exactly."),
    _seed("AssetCode12", "AssetCode12XDR", "\\0\\0\\0\\0\\0",
          "All-NUL twelve-byte asset code renders as five escaped NULs."),
    _seed("AssetCode12", "AssetCode12XDR", "hello\\xc3world",
          "Twelve-byte asset code holding a non-ASCII byte escapes it as \\xNN.",
          non_utf8_paths=[""]),
    _seed("AssetCode12", "AssetCode12XDR", "tab\\there",
          "Tab inside a twelve-byte asset code takes its short escape."),

    # --- Asset, TrustLineAsset, ChangeTrustAsset ----------------------------
    _seed("Asset", "AssetXDR", "native",
          "Native arm renders as a bare name."),
    _seed("Asset", "AssetXDR", ASSET_A4,
          "AlphaNum4 arm nests the code and issuer."),
    _seed("Asset", "AssetXDR", ASSET_A12,
          "AlphaNum12 arm nests the code and issuer."),
    _seed("TrustLineAsset", "TrustlineAssetXDR", "native",
          "Native arm of the trustline asset union renders as a bare name."),
    _seed("TrustLineAsset", "TrustlineAssetXDR", ASSET_A4,
          "AlphaNum4 arm of the trustline asset union."),
    _seed("TrustLineAsset", "TrustlineAssetXDR", ASSET_A12,
          "AlphaNum12 arm of the trustline asset union."),
    _seed("TrustLineAsset", "TrustlineAssetXDR", {"pool_share": L1},
          "Pool share arm of the trustline asset union carries a pool id."),
    _seed("ChangeTrustAsset", "ChangeTrustAssetXDR", "native",
          "Native arm of the change trust asset union renders as a bare name."),
    _seed("ChangeTrustAsset", "ChangeTrustAssetXDR", ASSET_A4,
          "AlphaNum4 arm of the change trust asset union."),
    _seed("ChangeTrustAsset", "ChangeTrustAssetXDR", ASSET_A12,
          "AlphaNum12 arm of the change trust asset union."),
    _seed("ChangeTrustAsset", "ChangeTrustAssetXDR",
          {"pool_share": {"liquidity_pool_constant_product": {
              "asset_a": "native", "asset_b": ASSET_A4, "fee": 30}}},
          "Pool share arm of the change trust asset union carries pool parameters."),
    _seed("LiquidityPoolParameters", "LiquidityPoolParametersXDR",
          {"liquidity_pool_constant_product": {
              "asset_a": "native", "asset_b": ASSET_A12, "fee": 30}},
          "Sole arm of the liquidity pool parameters union."),

    # --- 128- and 256-bit integer parts render as decimal strings ----------
    _seed("Int128Parts", "Int128PartsXDR", "0",
          "Signed 128-bit zero renders as a decimal string, not an object."),
    _seed("Int128Parts", "Int128PartsXDR", "1",
          "Signed 128-bit one renders as a decimal string."),
    _seed("Int128Parts", "Int128PartsXDR", "-1",
          "Signed 128-bit minus one crosses both halves of the struct."),
    _seed("Int128Parts", "Int128PartsXDR", INT128_MIN,
          "Signed 128-bit minimum renders as a decimal string."),
    _seed("Int128Parts", "Int128PartsXDR", INT128_MAX,
          "Signed 128-bit maximum renders as a decimal string."),
    _seed("UInt128Parts", "UInt128PartsXDR", "0",
          "Unsigned 128-bit zero renders as a decimal string."),
    _seed("UInt128Parts", "UInt128PartsXDR", "1",
          "Unsigned 128-bit one renders as a decimal string."),
    _seed("UInt128Parts", "UInt128PartsXDR", UINT128_MAX,
          "Unsigned 128-bit maximum renders as a decimal string."),
    _seed("Int256Parts", "Int256PartsXDR", "0",
          "Signed 256-bit zero renders as a decimal string."),
    _seed("Int256Parts", "Int256PartsXDR", "1",
          "Signed 256-bit one renders as a decimal string."),
    _seed("Int256Parts", "Int256PartsXDR", "-1",
          "Signed 256-bit minus one crosses all four quarters of the struct."),
    _seed("Int256Parts", "Int256PartsXDR", INT256_MIN,
          "Signed 256-bit minimum renders as a decimal string."),
    _seed("Int256Parts", "Int256PartsXDR", INT256_MAX,
          "Signed 256-bit maximum renders as a decimal string."),
    _seed("UInt256Parts", "UInt256PartsXDR", "0",
          "Unsigned 256-bit zero renders as a decimal string."),
    _seed("UInt256Parts", "UInt256PartsXDR", "1",
          "Unsigned 256-bit one renders as a decimal string."),
    _seed("UInt256Parts", "UInt256PartsXDR", UINT256_MAX,
          "Unsigned 256-bit maximum renders as a decimal string."),

    # --- 64-bit values inside structs render as strings ---------------------
    _seed("TimeBounds", "TimeBoundsXDR", {"min_time": "0", "max_time": "0"},
          "Time bounds at zero render both endpoints as strings."),
    _seed("TimeBounds", "TimeBoundsXDR",
          {"min_time": "1", "max_time": UINT64_MAX},
          "Time bounds at the unsigned 64-bit maximum stay strings."),
    _seed("Liabilities", "LiabilitiesXDR", {"buying": "0", "selling": "0"},
          "Liabilities at zero render as strings."),
    _seed("Liabilities", "LiabilitiesXDR",
          {"buying": INT64_MAX, "selling": INT64_MIN},
          "Liabilities at both signed 64-bit extremes stay strings."),
    _seed("SequenceNumber", "SequenceNumberXDR", "0",
          "Sequence number zero renders as a string."),
    _seed("SequenceNumber", "SequenceNumberXDR", INT64_MAX,
          "Sequence number at the signed 64-bit maximum renders as a string."),
    _seed("SequenceNumber", "SequenceNumberXDR", INT64_MIN,
          "Sequence number at the signed 64-bit minimum renders as a string."),
    _seed("TimePoint", "TimePointXDR", "0",
          "Time point zero renders as a string."),
    _seed("TimePoint", "TimePointXDR", UINT64_MAX,
          "Time point at the unsigned 64-bit maximum renders as a string."),
    _seed("Duration", "DurationXDR", "0",
          "Duration zero renders as a string."),
    _seed("Duration", "DurationXDR", UINT64_MAX,
          "Duration at the unsigned 64-bit maximum renders as a string."),

    # --- Fixed and variable opaque -----------------------------------------
    _seed("Hash", "HashXDR", HASH1,
          "Fixed 32-byte hash renders as lowercase hex."),
    _seed("Hash", "HashXDR", HASH_ZERO,
          "All-zero hash renders as 64 hex zeros, never as an empty string."),
    _seed("Uint256", "Uint256XDR", HASH1,
          "Fixed 32-byte unsigned value renders as lowercase hex."),
    _seed("DataValue", "DataValueXDR", "",
          "Empty variable opaque renders as an empty string."),
    _seed("DataValue", "DataValueXDR", "00",
          "Single zero byte of variable opaque renders as two hex digits."),
    _seed("DataValue", "DataValueXDR", "deadbeef",
          "Variable opaque renders as lowercase hex."),
    _seed("DataValue", "DataValueXDR", "ff" * 64,
          "Variable opaque at its declared 64-byte limit."),

    # --- Memo ---------------------------------------------------------------
    _seed("Memo", "MemoXDR", "none",
          "Void memo arm renders as a bare name."),
    _seed("Memo", "MemoXDR", {"text": "hello"},
          "Text memo arm carries an escaped string."),
    _seed("Memo", "MemoXDR", {"text": ""},
          "Empty text memo arm renders as an empty string."),
    _seed("Memo", "MemoXDR", {"text": "tab\\there"},
          "Text memo arm applies the short escape for tab."),
    _seed("Memo", "MemoXDR", {"id": "0"},
          "Id memo arm renders its 64-bit value as a string."),
    _seed("Memo", "MemoXDR", {"id": UINT64_MAX},
          "Id memo arm at the unsigned 64-bit maximum stays a string."),
    _seed("Memo", "MemoXDR", {"hash": HASH1},
          "Hash memo arm renders as lowercase hex."),
    _seed("Memo", "MemoXDR", {"return": HASH1},
          "Return-hash memo arm keys on the reserved word return."),

    # --- ClaimPredicate, including nesting and the optional arm ------------
    _seed("ClaimPredicate", "ClaimPredicateXDR", "unconditional",
          "Unconditional predicate arm renders as a bare name."),
    _seed("ClaimPredicate", "ClaimPredicateXDR", {"and": []},
          "And predicate arm with an empty array."),
    _seed("ClaimPredicate", "ClaimPredicateXDR",
          {"and": ["unconditional", {"before_relative_time": "60"}]},
          "And predicate arm at its two-element limit."),
    _seed("ClaimPredicate", "ClaimPredicateXDR",
          {"or": ["unconditional", "unconditional"]},
          "Or predicate arm at its two-element limit."),
    _seed("ClaimPredicate", "ClaimPredicateXDR", {"not": None},
          "Not predicate arm with the optional unset renders as null."),
    _seed("ClaimPredicate", "ClaimPredicateXDR", {"not": "unconditional"},
          "Not predicate arm with the optional set nests a predicate."),
    _seed("ClaimPredicate", "ClaimPredicateXDR", {"before_absolute_time": "0"},
          "Absolute time predicate renders its 64-bit bound as a string."),
    _seed("ClaimPredicate", "ClaimPredicateXDR",
          {"before_relative_time": INT64_MAX},
          "Relative time predicate at the signed 64-bit maximum."),
    _seed("Claimant", "ClaimantXDR",
          {"claimant_type_v0": {"destination": G1, "predicate": "unconditional"}},
          "Sole claimant arm keys on its enum member name."),

    # --- LedgerKey: every arm ----------------------------------------------
    _seed("LedgerKey", "LedgerKeyXDR", {"account": {"account_id": G1}},
          "Account ledger key arm."),
    _seed("LedgerKey", "LedgerKeyXDR",
          {"trustline": {"account_id": G1, "asset": "native"}},
          "Trustline ledger key arm keys on the stripped member name."),
    _seed("LedgerKey", "LedgerKeyXDR",
          {"trustline": {"account_id": G1, "asset": {"pool_share": L1}}},
          "Trustline ledger key arm holding a pool share asset."),
    _seed("LedgerKey", "LedgerKeyXDR",
          {"offer": {"seller_id": G1, "offer_id": "12"}},
          "Offer ledger key arm renders its offer id as a string."),
    _seed("LedgerKey", "LedgerKeyXDR",
          {"data": {"account_id": G1, "data_name": "config"}},
          "Data ledger key arm carries an escaped string name."),
    _seed("LedgerKey", "LedgerKeyXDR", {"claimable_balance": {"balance_id": B1}},
          "Claimable balance ledger key arm."),
    _seed("LedgerKey", "LedgerKeyXDR", {"liquidity_pool": {"liquidity_pool_id": L1}},
          "Liquidity pool ledger key arm."),
    _seed("LedgerKey", "LedgerKeyXDR",
          {"contract_data": {"contract": C1, "key": "void",
                             "durability": "persistent"}},
          "Contract data ledger key arm with persistent durability."),
    _seed("LedgerKey", "LedgerKeyXDR",
          {"contract_data": {"contract": G1, "key": {"symbol": "k"},
                             "durability": "temporary"}},
          "Contract data ledger key arm with temporary durability."),
    _seed("LedgerKey", "LedgerKeyXDR", {"contract_code": {"hash": HASH1}},
          "Contract code ledger key arm."),
    _seed("LedgerKey", "LedgerKeyXDR",
          {"config_setting": {"config_setting_id": "contract_max_size_bytes"}},
          "Config setting ledger key arm keys on an enum member name."),
    _seed("LedgerKey", "LedgerKeyXDR", {"ttl": {"key_hash": HASH1}},
          "TTL ledger key arm keys on the fully stripped member name."),

    # --- ScVal: every arm ---------------------------------------------------
    _seed("ScVal", "SCValXDR", {"bool": True},
          "Boolean arm renders a JSON boolean."),
    _seed("ScVal", "SCValXDR", {"bool": False},
          "Boolean arm at false."),
    _seed("ScVal", "SCValXDR", "void",
          "Void arm renders as a bare name."),
    _seed("ScVal", "SCValXDR", {"error": {"contract": 7}},
          "Error arm carrying a contract error code."),
    _seed("ScVal", "SCValXDR", {"error": {"wasm_vm": "internal_error"}},
          "Error arm carrying a host error enum member."),
    _seed("ScVal", "SCValXDR", {"u32": 0},
          "Unsigned 32-bit arm renders a JSON number."),
    _seed("ScVal", "SCValXDR", {"u32": 4294967295},
          "Unsigned 32-bit arm at its maximum stays a JSON number."),
    _seed("ScVal", "SCValXDR", {"i32": -2147483648},
          "Signed 32-bit arm at its minimum stays a JSON number."),
    _seed("ScVal", "SCValXDR", {"u64": "0"},
          "Unsigned 64-bit arm renders as a string."),
    _seed("ScVal", "SCValXDR", {"u64": UINT64_MAX},
          "Unsigned 64-bit arm at its maximum renders as a string."),
    _seed("ScVal", "SCValXDR", {"i64": INT64_MIN},
          "Signed 64-bit arm at its minimum renders as a string."),
    _seed("ScVal", "SCValXDR", {"i64": INT64_MAX},
          "Signed 64-bit arm at its maximum renders as a string."),
    _seed("ScVal", "SCValXDR", {"timepoint": "1735689600"},
          "Timepoint arm renders as a string."),
    _seed("ScVal", "SCValXDR", {"duration": "0"},
          "Duration arm renders as a string."),
    _seed("ScVal", "SCValXDR", {"u128": UINT128_MAX},
          "Unsigned 128-bit arm at its maximum."),
    _seed("ScVal", "SCValXDR", {"i128": "-1"},
          "Signed 128-bit arm at minus one."),
    _seed("ScVal", "SCValXDR", {"i128": INT128_MIN},
          "Signed 128-bit arm at its minimum."),
    _seed("ScVal", "SCValXDR", {"u256": UINT256_MAX},
          "Unsigned 256-bit arm at its maximum."),
    _seed("ScVal", "SCValXDR", {"i256": INT256_MIN},
          "Signed 256-bit arm at its minimum."),
    _seed("ScVal", "SCValXDR", {"bytes": "00ff"},
          "Bytes arm renders as lowercase hex."),
    _seed("ScVal", "SCValXDR", {"string": ""},
          "String arm with no content."),
    _seed("ScVal", "SCValXDR", {"string": "a\\\\b"},
          "String arm doubles an embedded backslash."),
    _seed("ScVal", "SCValXDR", {"symbol": "transfer"},
          "Symbol arm renders as an escaped string."),
    _seed("ScVal", "SCValXDR", {"vec": None},
          "Vector arm with the optional unset renders as null."),
    _seed("ScVal", "SCValXDR", {"vec": []},
          "Vector arm with an empty array."),
    _seed("ScVal", "SCValXDR", {"vec": [{"u32": 1}, "void"]},
          "Vector arm nesting two values."),
    _seed("ScVal", "SCValXDR", {"map": None},
          "Map arm with the optional unset renders as null."),
    _seed("ScVal", "SCValXDR", {"map": []},
          "Map arm with an empty array."),
    _seed("ScVal", "SCValXDR",
          {"map": [{"key": {"symbol": "k"}, "val": {"u32": 1}}]},
          "Map arm with one entry."),
    _seed("ScVal", "SCValXDR", {"address": G1},
          "Address arm carrying an account address."),
    _seed("ScVal", "SCValXDR", {"address": C1},
          "Address arm carrying a contract address."),
    _seed("ScVal", "SCValXDR", "ledger_key_contract_instance",
          "Ledger key contract instance arm renders as a bare name."),
    _seed("ScVal", "SCValXDR", {"ledger_key_nonce": {"nonce": "5"}},
          "Ledger key nonce arm renders its nonce as a string."),
    _seed("ScVal", "SCValXDR",
          {"contract_instance": {"executable": "stellar_asset", "storage": None}},
          "Contract instance arm with unset storage."),
    _seed("ScVal", "SCValXDR",
          {"contract_instance": {"executable": {"wasm": HASH1}, "storage": []}},
          "Contract instance arm with empty storage."),
    _seed("ScVal", "SCValXDR", {"executable_tag": "tag"},
          "Executable tag arm renders as an escaped string."),

    # --- Soroban value containers as standalone types ----------------------
    _seed("ScVec", "SCVecXDR", [],
          "Empty vector typedef renders as an empty array."),
    _seed("ScVec", "SCVecXDR", [{"u32": 1}, {"i32": -1}],
          "Populated vector typedef."),
    _seed("ScMap", "SCMapXDR", [],
          "Empty map typedef renders as an empty array."),
    _seed("ScMapEntry", "SCMapEntryXDR",
          {"key": {"symbol": "k"}, "val": {"bool": True}},
          "Map entry keys its two fields in declaration order."),
    _seed("ScBytes", "SCBytesXDR", "",
          "Empty bytes typedef renders as an empty string."),
    _seed("ScBytes", "SCBytesXDR", "0a0b0c",
          "Bytes typedef renders as lowercase hex."),
    _seed("ScString", "SCStringXDR", "hello",
          "String typedef renders as an escaped string."),
    _seed("ScSymbol", "SCSymbolXDR", "sym",
          "Symbol typedef renders as an escaped string."),
    _seed("ScNonceKey", "SCNonceKeyXDR", {"nonce": INT64_MIN},
          "Nonce key renders its 64-bit field as a string."),
    _seed("ScContractInstance", "SCContractInstanceXDR",
          {"executable": "stellar_asset",
           "storage": [{"key": {"symbol": "k"}, "val": "void"}]},
          "Contract instance with populated storage."),

    # --- SCError: every arm -------------------------------------------------
    _seed("ScError", "SCErrorXDR", {"contract": 0},
          "Contract error arm carries a bare 32-bit code."),
    _seed("ScError", "SCErrorXDR", {"contract": 4294967295},
          "Contract error arm at the unsigned 32-bit maximum."),
    _seed("ScError", "SCErrorXDR", {"wasm_vm": "arith_domain"},
          "WASM VM error arm keyed on an error code member."),
    _seed("ScError", "SCErrorXDR", {"context": "index_bounds"},
          "Context error arm."),
    _seed("ScError", "SCErrorXDR", {"storage": "invalid_input"},
          "Storage error arm."),
    _seed("ScError", "SCErrorXDR", {"object": "missing_value"},
          "Object error arm."),
    _seed("ScError", "SCErrorXDR", {"crypto": "existing_value"},
          "Crypto error arm."),
    _seed("ScError", "SCErrorXDR", {"events": "exceeded_limit"},
          "Events error arm."),
    _seed("ScError", "SCErrorXDR", {"budget": "invalid_action"},
          "Budget error arm."),
    _seed("ScError", "SCErrorXDR", {"value": "internal_error"},
          "Value error arm."),
    _seed("ScError", "SCErrorXDR", {"auth": "unexpected_type"},
          "Auth error arm."),

    # --- Operations ---------------------------------------------------------
    _seed("Operation", "OperationXDR",
          {"source_account": None,
           "body": {"create_account": {"destination": G1,
                                       "starting_balance": "100"}}},
          "Operation with the optional source account unset."),
    _seed("Operation", "OperationXDR",
          {"source_account": G1,
           "body": {"payment": {"destination": G1, "asset": "native",
                                "amount": "1"}}},
          "Operation with the optional source account set."),
    _seed("Operation", "OperationXDR",
          {"source_account": M1, "body": "inflation"},
          "Operation whose source account is muxed and whose body is void."),
    _seed("OperationBody", "OperationBodyXDR",
          {"create_account": {"destination": G1, "starting_balance": "1"}},
          "Create account body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"payment": {"destination": M1, "asset": ASSET_A4, "amount": INT64_MAX}},
          "Payment body arm at the signed 64-bit maximum amount."),
    _seed("OperationBody", "OperationBodyXDR",
          {"path_payment_strict_receive": {
              "send_asset": "native", "send_max": "10", "destination": G1,
              "dest_asset": ASSET_A4, "dest_amount": "5", "path": []}},
          "Path payment strict receive body arm with an empty path."),
    _seed("OperationBody", "OperationBodyXDR",
          {"path_payment_strict_send": {
              "send_asset": ASSET_A12, "send_amount": "10", "destination": G1,
              "dest_asset": "native", "dest_min": "5",
              "path": ["native", ASSET_A4]}},
          "Path payment strict send body arm with a two-element path."),
    _seed("OperationBody", "OperationBodyXDR",
          {"manage_sell_offer": {"selling": "native", "buying": ASSET_A4,
                                 "amount": "1", "price": {"n": 1, "d": 2},
                                 "offer_id": "0"}},
          "Manage sell offer body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"manage_buy_offer": {"selling": ASSET_A4, "buying": "native",
                                "buy_amount": "1", "price": {"n": 7, "d": 3},
                                "offer_id": "9"}},
          "Manage buy offer body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"create_passive_sell_offer": {"selling": "native", "buying": ASSET_A4,
                                         "amount": "1", "price": {"n": 1, "d": 1}}},
          "Create passive sell offer body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"set_options": {"inflation_dest": G1, "clear_flags": 1,
                           "set_flags": 2, "master_weight": 255,
                           "low_threshold": 0, "med_threshold": 1,
                           "high_threshold": 2, "home_domain": "example.com",
                           "signer": {"key": X1, "weight": 3}}},
          "Set options body arm with every optional set."),
    _seed("OperationBody", "OperationBodyXDR",
          {"change_trust": {"line": ASSET_A4, "limit": INT64_MAX}},
          "Change trust body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"allow_trust": {"trustor": G1, "asset": "USD", "authorize": 1}},
          "Allow trust body arm carries an asset code union as a string."),
    _seed("OperationBody", "OperationBodyXDR", {"account_merge": M1},
          "Account merge body arm carries a muxed account directly."),
    _seed("OperationBody", "OperationBodyXDR", "inflation",
          "Inflation body arm renders as a bare name."),
    _seed("OperationBody", "OperationBodyXDR",
          {"manage_data": {"data_name": "k", "data_value": None}},
          "Manage data body arm with the optional value unset."),
    _seed("OperationBody", "OperationBodyXDR", {"bump_sequence": {"bump_to": "9"}},
          "Bump sequence body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"create_claimable_balance": {
              "asset": "native", "amount": "1",
              "claimants": [{"claimant_type_v0": {
                  "destination": G1, "predicate": "unconditional"}}]}},
          "Create claimable balance body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"claim_claimable_balance": {"balance_id": B1}},
          "Claim claimable balance body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"begin_sponsoring_future_reserves": {"sponsored_id": G1}},
          "Begin sponsoring future reserves body arm."),
    _seed("OperationBody", "OperationBodyXDR", "end_sponsoring_future_reserves",
          "End sponsoring future reserves body arm renders as a bare name."),
    _seed("OperationBody", "OperationBodyXDR",
          {"revoke_sponsorship": {"ledger_entry": {"account": {"account_id": G1}}}},
          "Revoke sponsorship body arm targeting a ledger entry."),
    _seed("OperationBody", "OperationBodyXDR",
          {"revoke_sponsorship": {"signer": {"account_id": G1, "signer_key": T1}}},
          "Revoke sponsorship body arm targeting a signer."),
    _seed("OperationBody", "OperationBodyXDR",
          {"clawback": {"asset": ASSET_A4, "from": M1, "amount": "1"}},
          "Clawback body arm keys on the reserved word from."),
    _seed("OperationBody", "OperationBodyXDR",
          {"clawback_claimable_balance": {"balance_id": B1}},
          "Clawback claimable balance body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"set_trust_line_flags": {"trustor": G1, "asset": ASSET_A4,
                                    "clear_flags": 1, "set_flags": 2}},
          "Set trustline flags body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"liquidity_pool_deposit": {"liquidity_pool_id": L1, "max_amount_a": "1",
                                      "max_amount_b": "2",
                                      "min_price": {"n": 1, "d": 2},
                                      "max_price": {"n": 3, "d": 1}}},
          "Liquidity pool deposit body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"liquidity_pool_withdraw": {"liquidity_pool_id": L1, "amount": "1",
                                       "min_amount_a": "0", "min_amount_b": "0"}},
          "Liquidity pool withdraw body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"invoke_host_function": {
              "host_function": {"upload_contract_wasm": "0061736d"},
              "auth": []}},
          "Invoke host function body arm with no authorization entries."),
    _seed("OperationBody", "OperationBodyXDR",
          {"extend_footprint_ttl": {"ext": "v0", "extend_to": 100}},
          "Extend footprint TTL body arm."),
    _seed("OperationBody", "OperationBodyXDR",
          {"restore_footprint": {"ext": "v0"}},
          "Restore footprint body arm."),

    # --- Operation payloads that pin the escape ladder ---------------------
    _seed("ManageDataOp", "ManageDataOperationXDR",
          {"data_name": "plain-name_1", "data_value": "0102"},
          "Printable ASCII name survives the escape ladder unchanged."),
    _seed("ManageDataOp", "ManageDataOperationXDR",
          {"data_name": "a\\\\b", "data_value": None},
          "Backslash in a string field doubles."),
    _seed("ManageDataOp", "ManageDataOperationXDR",
          {"data_name": "a\\tb", "data_value": ""},
          "Tab in a string field takes its short escape."),
    _seed("ManageDataOp", "ManageDataOperationXDR",
          {"data_name": "a\\0b", "data_value": None},
          "NUL in a string field takes its short escape."),
    _seed("ManageDataOp", "ManageDataOperationXDR",
          {"data_name": "a\\x7fb", "data_value": None},
          "DEL in a string field escapes as \\x7f."),
    _seed("ManageDataOp", "ManageDataOperationXDR",
          {"data_name": "a\\nb\\rc", "data_value": None},
          "Newline and carriage return take their short escapes."),
    _seed("ManageDataOp", "ManageDataOperationXDR",
          {"data_name": " ~", "data_value": None},
          "Both ends of the printable range survive unescaped."),
    _seed("SetOptionsOp", "SetOptionsOperationXDR",
          {"inflation_dest": None, "clear_flags": None, "set_flags": None,
           "master_weight": None, "low_threshold": None, "med_threshold": None,
           "high_threshold": None, "home_domain": None, "signer": None},
          "Every optional field unset renders as null."),
    _seed("SetOptionsOp", "SetOptionsOperationXDR",
          {"inflation_dest": G1, "clear_flags": 0, "set_flags": 0,
           "master_weight": 0, "low_threshold": 0, "med_threshold": 0,
           "high_threshold": 0, "home_domain": "a\\\\b",
           "signer": {"key": P_SHORT, "weight": 255}},
          "Every optional field set, including an escaped home domain."),

    # --- Transaction envelopes and results ---------------------------------
    _seed("TransactionEnvelope", "TransactionEnvelopeXDR",
          {"tx_v0": {"tx": {"source_account_ed25519": HASH1, "fee": 100,
                            "seq_num": "1", "time_bounds": None, "memo": "none",
                            "operations": [], "ext": "v0"},
                     "signatures": []}},
          "Version 0 transaction envelope arm."),
    _seed("TransactionEnvelope", "TransactionEnvelopeXDR",
          {"tx": {"tx": {"source_account": G1, "fee": 100, "seq_num": "1",
                         "cond": "none", "memo": "none",
                         "operations": [{"source_account": None,
                                         "body": "inflation"}],
                         "ext": "v0"},
                  "signatures": [{"hint": "01020304", "signature": "0a0b"}]}},
          "Version 1 transaction envelope arm with one signature."),
    _seed("TransactionEnvelope", "TransactionEnvelopeXDR",
          {"tx_fee_bump": {"tx": {"fee_source": M1, "fee": "200",
                                  "inner_tx": {"tx": {
                                      "tx": {"source_account": G1, "fee": 100,
                                             "seq_num": "1", "cond": "none",
                                             "memo": "none", "operations": [],
                                             "ext": "v0"},
                                      "signatures": []}},
                                  "ext": "v0"},
                           "signatures": []}},
          "Fee bump transaction envelope arm wrapping a version 1 envelope."),
    _seed("FeeBumpTransactionInnerTx", "FeeBumpTransactionXDRInnerTxXDR",
          {"tx": {"tx": {"source_account": G1, "fee": 100, "seq_num": "1",
                         "cond": "none", "memo": "none", "operations": [],
                         "ext": "v0"},
                  "signatures": []}},
          "Union covering one member of its discriminant enum keys the arm tx, from "
          "the enum's full member list rather than from its own single case."),
    _seed("Preconditions", "PreconditionsXDR", "none",
          "Void preconditions arm renders as a bare name."),
    _seed("Preconditions", "PreconditionsXDR",
          {"time": {"min_time": "0", "max_time": "100"}},
          "Time preconditions arm."),
    _seed("Preconditions", "PreconditionsXDR",
          {"v2": {"time_bounds": None, "ledger_bounds": None, "min_seq_num": None,
                  "min_seq_age": "0", "min_seq_ledger_gap": 0,
                  "extra_signers": []}},
          "Version 2 preconditions arm with every optional unset."),
    _seed("PreconditionsV2", "PreconditionsV2XDR",
          {"time_bounds": {"min_time": "1", "max_time": "2"},
           "ledger_bounds": {"min_ledger": 1, "max_ledger": 2},
           "min_seq_num": "7", "min_seq_age": "3", "min_seq_ledger_gap": 4,
           "extra_signers": [T1, X1]},
          "Version 2 preconditions with every optional set and two extra signers."),
    _seed("LedgerBounds", "LedgerBoundsXDR", {"min_ledger": 0, "max_ledger": 4294967295},
          "Ledger bounds render both 32-bit endpoints as numbers."),
    _seed("TransactionResult", "TransactionResultXDR",
          {"fee_charged": "100",
           "result": {"tx_success": [{"op_inner": {"payment": "success"}}]},
           "ext": "v0"},
          "Successful transaction result nesting an inner operation result."),
    _seed("TransactionResult", "TransactionResultXDR",
          {"fee_charged": "0", "result": {"tx_failed": []}, "ext": "v0"},
          "Failed transaction result with an empty operation result array."),
    _seed("TransactionResult", "TransactionResultXDR",
          {"fee_charged": INT64_MAX,
           "result": {"tx_fee_bump_inner_success": {
               "transaction_hash": HASH1,
               "result": {"fee_charged": "1",
                          "result": {"tx_success": []},
                          "ext": "v0"}}},
           "ext": "v0"},
          "Fee bump inner success result nests a full inner result."),
    _seed("OperationResult", "OperationResultXDR", "op_bad_auth",
          "Operation result arm that carries nothing renders as a bare name."),
    _seed("OperationResult", "OperationResultXDR",
          {"op_inner": {"create_account": "success"}},
          "Inner operation result nests the per-operation union."),
    _seed("OperationResult", "OperationResultXDR",
          {"op_inner": {"payment": "malformed"}},
          "Inner operation result carrying a failure code."),
    _seed("OperationResult", "OperationResultXDR",
          {"op_inner": {"manage_sell_offer": {"success": {
              "offers_claimed": [], "offer": "deleted"}}}},
          "Inner operation result nesting a success payload."),
    _seed("OperationResult", "OperationResultXDR",
          {"op_inner": {"inflation": {"success": []}}},
          "Inner inflation result with an empty payout array."),

    # --- Ledger entries -----------------------------------------------------
    _seed("LedgerEntryData", "LedgerEntryDataXDR",
          {"account": {"account_id": G1, "balance": "10", "seq_num": "1",
                       "num_sub_entries": 0, "inflation_dest": None, "flags": 0,
                       "home_domain": "", "thresholds": "01000000", "signers": [],
                       "ext": "v0"}},
          "Account ledger entry arm with no signers."),
    _seed("LedgerEntryData", "LedgerEntryDataXDR",
          {"account": {"account_id": G1, "balance": "10", "seq_num": "1",
                       "num_sub_entries": 1, "inflation_dest": G1, "flags": 1,
                       "home_domain": "example.com", "thresholds": "01020304",
                       "signers": [{"key": G1, "weight": 1}],
                       "ext": {"v1": {"liabilities": {"buying": "1",
                                                      "selling": "2"},
                                      "ext": "v0"}}}},
          "Account ledger entry arm with an extension and one signer."),
    _seed("LedgerEntryData", "LedgerEntryDataXDR",
          {"trustline": {"account_id": G1, "asset": ASSET_A4, "balance": "5",
                         "limit": INT64_MAX, "flags": 1, "ext": "v0"}},
          "Trustline ledger entry arm."),
    _seed("LedgerEntryData", "LedgerEntryDataXDR",
          {"offer": {"seller_id": G1, "offer_id": "1", "selling": "native",
                     "buying": ASSET_A4, "amount": "1",
                     "price": {"n": 1, "d": 2}, "flags": 0, "ext": "v0"}},
          "Offer ledger entry arm."),
    _seed("LedgerEntryData", "LedgerEntryDataXDR",
          {"data": {"account_id": G1, "data_name": "k", "data_value": "",
                    "ext": "v0"}},
          "Data ledger entry arm with an empty value."),
    _seed("LedgerEntryData", "LedgerEntryDataXDR",
          {"claimable_balance": {"balance_id": B1, "claimants": [], "asset": "native",
                                 "amount": "1", "ext": "v0"}},
          "Claimable balance ledger entry arm."),
    _seed("LedgerEntryData", "LedgerEntryDataXDR",
          {"liquidity_pool": {"liquidity_pool_id": L1, "body": {
              "liquidity_pool_constant_product": {
                  "params": {"asset_a": "native", "asset_b": ASSET_A4, "fee": 30},
                  "reserve_a": "1", "reserve_b": "2", "total_pool_shares": "3",
                  "pool_shares_trust_line_count": "4"}}}},
          "Liquidity pool ledger entry arm."),
    _seed("LedgerEntryData", "LedgerEntryDataXDR",
          {"contract_data": {"ext": "v0", "contract": C1, "key": "void",
                             "durability": "persistent", "val": {"u32": 1}}},
          "Contract data ledger entry arm."),
    _seed("LedgerEntryData", "LedgerEntryDataXDR",
          {"contract_code": {"ext": "v0", "hash": HASH1, "code": "0061736d"}},
          "Contract code ledger entry arm."),
    _seed("LedgerEntryData", "LedgerEntryDataXDR",
          {"config_setting": {"contract_max_size_bytes": 100}},
          "Config setting ledger entry arm."),
    _seed("LedgerEntryData", "LedgerEntryDataXDR",
          {"ttl": {"key_hash": HASH1, "live_until_ledger_seq": 7}},
          "TTL ledger entry arm."),
    _seed("LedgerEntry", "LedgerEntryXDR",
          {"last_modified_ledger_seq": 1,
           "data": {"ttl": {"key_hash": HASH1, "live_until_ledger_seq": 7}},
           "ext": "v0"},
          "Ledger entry wrapping a TTL entry with a void extension."),
    _seed("LedgerEntry", "LedgerEntryXDR",
          {"last_modified_ledger_seq": 4294967295,
           "data": {"ttl": {"key_hash": HASH_ZERO, "live_until_ledger_seq": 0}},
           "ext": {"v1": {"sponsoring_id": G1, "ext": "v0"}}},
          "Ledger entry with a populated extension."),
    _seed("LedgerEntryChange", "LedgerEntryChangeXDR",
          {"created": {"last_modified_ledger_seq": 1,
                       "data": {"ttl": {"key_hash": HASH1,
                                        "live_until_ledger_seq": 7}},
                       "ext": "v0"}},
          "Created ledger entry change arm."),
    _seed("LedgerEntryChange", "LedgerEntryChangeXDR",
          {"updated": {"last_modified_ledger_seq": 2,
                       "data": {"ttl": {"key_hash": HASH1,
                                        "live_until_ledger_seq": 8}},
                       "ext": "v0"}},
          "Updated ledger entry change arm."),
    _seed("LedgerEntryChange", "LedgerEntryChangeXDR",
          {"removed": {"contract_code": {"hash": HASH1}}},
          "Removed ledger entry change arm carries a key, not an entry."),
    _seed("LedgerEntryChange", "LedgerEntryChangeXDR",
          {"state": {"last_modified_ledger_seq": 3,
                     "data": {"ttl": {"key_hash": HASH1,
                                      "live_until_ledger_seq": 9}},
                     "ext": "v0"}},
          "State ledger entry change arm."),
    _seed("LedgerEntryChange", "LedgerEntryChangeXDR",
          {"restored": {"last_modified_ledger_seq": 4,
                        "data": {"ttl": {"key_hash": HASH1,
                                         "live_until_ledger_seq": 10}},
                        "ext": "v0"}},
          "Restored ledger entry change arm."),
    _seed("LedgerFootprint", "LedgerFootprintXDR",
          {"read_only": [], "read_write": []},
          "Footprint with both arrays empty."),
    _seed("LedgerFootprint", "LedgerFootprintXDR",
          {"read_only": [{"contract_code": {"hash": HASH1}}],
           "read_write": [{"ttl": {"key_hash": HASH_ZERO}}]},
          "Footprint with both arrays populated."),
    _seed("LedgerHeader", "LedgerHeaderXDR",
          {"ledger_version": 23, "previous_ledger_hash": HASH1,
           "scp_value": {"tx_set_hash": HASH1, "close_time": "0",
                         "upgrades": [], "ext": "basic"},
           "tx_set_result_hash": HASH1, "bucket_list_hash": HASH1,
           "ledger_seq": 2, "total_coins": "1", "fee_pool": "0", "inflation_seq": 0,
           "id_pool": "0", "base_fee": 100, "base_reserve": 5000000,
           "max_tx_set_size": 100,
           "skip_list": [HASH1, HASH_ZERO, HASH1, HASH_ZERO], "ext": "v0"},
          "Ledger header renders its four-element fixed array of hashes."),

    # --- Soroban authorization ---------------------------------------------
    _seed("SorobanCredentials", "SorobanCredentialsXDR", "source_account",
          "Source account credentials arm renders as a bare name."),
    _seed("SorobanCredentials", "SorobanCredentialsXDR",
          {"address": {"address": C1, "nonce": "1",
                       "signature_expiration_ledger": 100, "signature": "void"}},
          "Address credentials arm."),
    _seed("SorobanAuthorizedInvocation", "SorobanAuthorizedInvocationXDR",
          {"function": {"contract_fn": {"contract_address": C1,
                                        "function_name": "transfer",
                                        "args": [{"u32": 1}]}},
           "sub_invocations": []},
          "Authorized invocation with no sub-invocations."),
    _seed("SorobanAuthorizationEntry", "SorobanAuthorizationEntryXDR",
          {"credentials": "source_account",
           "root_invocation": {
               "function": {"contract_fn": {"contract_address": C1,
                                            "function_name": "hello",
                                            "args": []}},
               "sub_invocations": []}},
          "Authorization entry with source account credentials."),
    _seed("SorobanAuthorizationEntry", "SorobanAuthorizationEntryXDR",
          {"credentials": {"address": {"address": G1, "nonce": INT64_MAX,
                                       "signature_expiration_ledger": 0,
                                       "signature": {"vec": []}}},
           "root_invocation": {
               "function": {"create_contract_host_fn": {
                   "contract_id_preimage": {"asset": "native"},
                   "executable": "stellar_asset"}},
               "sub_invocations": []}},
          "Authorization entry with address credentials and a create-contract root."),
    _seed("SorobanAuthorizationEntry", "SorobanAuthorizationEntryXDR",
          {"credentials": "source_account",
           "root_invocation": {
               "function": {"contract_fn": {"contract_address": C1,
                                            "function_name": "outer",
                                            "args": []}},
               "sub_invocations": [{
                   "function": {"contract_fn": {"contract_address": C1,
                                                "function_name": "inner",
                                                "args": []}},
                   "sub_invocations": []}]}},
          "Authorization entry with one level of sub-invocation nesting."),
    _seed("ContractIdPreimage", "ContractIDPreimageXDR",
          {"address": {"address": C1, "salt": HASH1}},
          "Address contract id preimage arm."),
    _seed("ContractIdPreimage", "ContractIDPreimageXDR", {"asset": ASSET_A4},
          "Asset contract id preimage arm."),
    _seed("ContractExecutable", "ContractExecutableXDR", "stellar_asset",
          "Stellar asset executable arm renders as a bare name."),
    _seed("ContractExecutable", "ContractExecutableXDR", {"wasm": HASH1},
          "WASM executable arm keys on the stripped member name."),
    _seed("ContractExecutable", "ContractExecutableXDR",
          {"external_ref": {"executable_owner": C1, "tag": "ref"}},
          "External reference executable arm."),
    _seed("HostFunction", "HostFunctionXDR",
          {"invoke_contract": {"contract_address": C1, "function_name": "hello",
                               "args": []}},
          "Invoke contract host function arm."),
    _seed("HostFunction", "HostFunctionXDR",
          {"create_contract": {"contract_id_preimage": {"asset": "native"},
                               "executable": "stellar_asset"}},
          "Create contract host function arm."),
    _seed("HostFunction", "HostFunctionXDR", {"upload_contract_wasm": ""},
          "Upload WASM host function arm with empty variable opaque."),
    _seed("HostFunction", "HostFunctionXDR", {"upload_contract_wasm": "0061736d"},
          "Upload WASM host function arm with data."),
    _seed("HostFunction", "HostFunctionXDR",
          {"create_contract_v2": {
              "contract_id_preimage": {"address": {"address": C1, "salt": HASH1}},
              "executable": {"wasm": HASH1},
              "constructor_args": [{"u32": 1}]}},
          "Create contract v2 host function arm with constructor arguments."),
    _seed("InvokeContractArgs", "InvokeContractArgsXDR",
          {"contract_address": C1, "function_name": "f", "args": []},
          "Invoke contract arguments with an empty argument array."),

    # --- Contract events and the six fields named type ---------------------
    _seed("ContractEvent", "ContractEventXDR",
          {"ext": "v0", "contract_id": None, "type": "system",
           "body": {"v0": {"topics": [], "data": "void"}}},
          "Contract event renders its discriminant field under the key type."),
    _seed("ContractEvent", "ContractEventXDR",
          {"ext": "v0", "contract_id": C1, "type": "contract",
           "body": {"v0": {"topics": [{"symbol": "transfer"}],
                           "data": {"u32": 1}}}},
          "Contract event with a contract id and one topic."),
    _seed("DiagnosticEvent", "DiagnosticEventXDR",
          {"in_successful_contract_call": True,
           "event": {"ext": "v0", "contract_id": None, "type": "diagnostic",
                     "body": {"v0": {"topics": [], "data": "void"}}}},
          "Diagnostic event wrapping a contract event."),
    _seed("ScSpecEventParamV0", "SCSpecEventParamV0XDR",
          {"doc": "", "name": "p", "type": "u32",
           "location": "data"},
          "Event parameter renders its type field under the key type."),
    _seed("ScSpecFunctionInputV0", "SCSpecFunctionInputV0XDR",
          {"doc": "d", "name": "arg", "type": {"option": {"value_type": "bool"}}},
          "Function input renders its type field under the key type."),
    _seed("ScSpecUdtStructFieldV0", "SCSpecUDTStructFieldV0XDR",
          {"doc": "", "name": "field", "type": "i64"},
          "Struct field renders its type field under the key type."),
    _seed("ScSpecUdtUnionCaseTupleV0", "SCSpecUDTUnionCaseTupleV0XDR",
          {"doc": "", "name": "case", "type": ["u32", "bool"]},
          "Union case tuple renders its type array under the key type."),
    _seed("SerializedBinaryFuseFilter", "SerializedBinaryFuseFilterXDR",
          {"type": "b8_bit",
           "input_hash_seed": {"seed": BYTES_16},
           "filter_seed": {"seed": BYTES_16},
           "segment_length": 1, "segement_length_mask": 2, "segment_count": 3,
           "segment_count_length": 4, "fingerprint_length": 5,
           "fingerprints": "0102"},
          "Serialized filter renders its type field under the key type.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["filter_seed.seed", "input_hash_seed.seed"]),
    _seed("SerializedBinaryFuseFilter", "SerializedBinaryFuseFilterXDR",
          {"type": "b16_bit",
           "input_hash_seed": {"seed": [0] * 16},
           "filter_seed": {"seed": [255] * 16},
           "segment_length": 0, "segement_length_mask": 0, "segment_count": 0,
           "segment_count_length": 0, "fingerprint_length": 0,
           "fingerprints": ""},
          "Serialized filter with empty fingerprints and extreme seeds.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["filter_seed.seed", "input_hash_seed.seed"]),
    _seed("SerializedBinaryFuseFilter", "SerializedBinaryFuseFilterXDR",
          {"type": "b32_bit",
           "input_hash_seed": {"seed": BYTES_16},
           "filter_seed": {"seed": BYTES_16},
           "segment_length": 4294967295, "segement_length_mask": 4294967295,
           "segment_count": 4294967295, "segment_count_length": 4294967295,
           "fingerprint_length": 4294967295, "fingerprints": "ffff"},
          "Serialized filter at the 32-bit maximum in every counter.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["filter_seed.seed", "input_hash_seed.seed"]),
    _seed("BinaryFuseFilterType", "BinaryFuseFilterTypeXDR", "b8_bit",
          "Digit-leading enum member is prefixed with b."),
    _seed("BinaryFuseFilterType", "BinaryFuseFilterTypeXDR", "b16_bit",
          "Digit-leading enum member is prefixed with b."),
    _seed("BinaryFuseFilterType", "BinaryFuseFilterTypeXDR", "b32_bit",
          "Digit-leading enum member is prefixed with b."),

    # --- Contract specification --------------------------------------------
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR", "val",
          "Val type renders as a bare name."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR", "bool",
          "Bool type renders as a bare name."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR", "u32",
          "Unsigned 32-bit type renders as a bare name."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR", "i128",
          "Signed 128-bit type renders as a bare name."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR", "address",
          "Address type renders as a bare name."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR", "muxed_address",
          "Muxed address type renders as a bare name."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR", {"option": {"value_type": "u32"}},
          "Option type nests its value type."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR",
          {"result": {"ok_type": "u32", "error_type": "error"}},
          "Result type nests both of its types."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR", {"vec": {"element_type": "bool"}},
          "Vec type nests its element type."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR",
          {"map": {"key_type": "symbol", "value_type": "u64"}},
          "Map type nests both of its types."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR", {"tuple": {"value_types": []}},
          "Tuple type with an empty value type array."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR",
          {"tuple": {"value_types": ["u32", "bool"]}},
          "Tuple type with two value types."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR", {"bytes_n": {"n": 32}},
          "Fixed-length bytes type carries its length."),
    _seed("ScSpecTypeDef", "SCSpecTypeDefXDR", {"udt": {"name": "Account"}},
          "User-defined type carries its name."),
    _seed("ScSpecEntry", "SCSpecEntryXDR",
          {"function_v0": {"doc": "", "name": "hello", "inputs": [],
                           "outputs": []}},
          "Function spec entry arm with no inputs or outputs."),
    _seed("ScSpecEntry", "SCSpecEntryXDR",
          {"udt_struct_v0": {"doc": "", "lib": "", "name": "S",
                             "fields": [{"doc": "", "name": "f",
                                         "type": "u32"}]}},
          "Struct spec entry arm with one field."),
    _seed("ScSpecEntry", "SCSpecEntryXDR",
          {"udt_union_v0": {"doc": "", "lib": "", "name": "U",
                            "cases": [{"void_v0": {"doc": "", "name": "A"}},
                                      {"tuple_v0": {"doc": "", "name": "B",
                                                    "type": ["u32"]}}]}},
          "Union spec entry arm with both case shapes."),
    _seed("ScSpecEntry", "SCSpecEntryXDR",
          {"udt_enum_v0": {"doc": "", "lib": "", "name": "E",
                           "cases": [{"doc": "", "name": "A", "value": 1}]}},
          "Enum spec entry arm."),
    _seed("ScSpecEntry", "SCSpecEntryXDR",
          {"udt_error_enum_v0": {"doc": "", "lib": "", "name": "Err",
                                 "cases": [{"doc": "", "name": "Bad",
                                            "value": 2}]}},
          "Error enum spec entry arm."),
    _seed("ScSpecUdtUnionCaseV0", "SCSpecUDTUnionCaseV0XDR",
          {"void_v0": {"doc": "", "name": "A"}},
          "Void union case arm."),
    _seed("ScSpecUdtUnionCaseV0", "SCSpecUDTUnionCaseV0XDR",
          {"tuple_v0": {"doc": "", "name": "B", "type": ["bool"]}},
          "Tuple union case arm."),
    _seed("ScSpecFunctionV0", "SCSpecFunctionV0XDR",
          {"doc": "doc", "name": "f",
           "inputs": [{"doc": "", "name": "a", "type": "u32"}],
           "outputs": ["bool"]},
          "Function spec with one input and one output."),
    _seed("ScEnvMetaEntry", "SCEnvMetaEntryXDR",
          {"sc_env_meta_kind_interface_version": {"protocol": 23,
                                                  "pre_release": 0}},
          "Sole environment meta arm keys on the unstripped member name."),
    _seed("ScMetaEntry", "SCMetaEntryXDR", {"sc_meta_v0": {"key": "k", "val": "v"}},
          "Sole contract meta arm keys on the unstripped member name."),

    # --- Extension unions at v0 and beyond ---------------------------------
    _seed("ExtensionPoint", "ExtensionPoint", "v0",
          "Extension point at its only arm renders as a bare name."),
    _seed("AccountEntryExt", "AccountEntryExtXDR", "v0",
          "Account extension at v0 renders as a bare name."),
    _seed("AccountEntryExt", "AccountEntryExtXDR",
          {"v1": {"liabilities": {"buying": "1", "selling": "2"}, "ext": "v0"}},
          "Account extension at v1 nests liabilities."),
    _seed("AccountEntryExtensionV1Ext", "AccountEntryExtV1XDR", "v0",
          "Account v1 extension at v0."),
    _seed("AccountEntryExtensionV1Ext", "AccountEntryExtV1XDR",
          {"v2": {"num_sponsored": 1, "num_sponsoring": 2,
                  "signer_sponsoring_i_ds": [None, G1], "ext": "v0"}},
          "Account v1 extension at v2 with a mixed optional array."),
    _seed("LedgerEntryExt", "LedgerEntryExtXDR", "v0",
          "Ledger entry extension at v0."),
    _seed("LedgerEntryExt", "LedgerEntryExtXDR",
          {"v1": {"sponsoring_id": None, "ext": "v0"}},
          "Ledger entry extension at v1 with the sponsoring id unset."),
    _seed("TrustLineEntryExt", "TrustlineEntryExtXDR", "v0",
          "Trustline extension at v0."),
    _seed("TrustLineEntryExt", "TrustlineEntryExtXDR",
          {"v1": {"liabilities": {"buying": "0", "selling": "0"}, "ext": "v0"}},
          "Trustline extension at v1."),
    _seed("SorobanTransactionMetaExt", "SorobanTransactionMetaExt", "v0",
          "Soroban transaction meta extension at v0."),
    _seed("SorobanTransactionMetaExt", "SorobanTransactionMetaExt",
          {"v1": {"ext": "v0", "total_non_refundable_resource_fee_charged": "1",
                  "total_refundable_resource_fee_charged": "2",
                  "rent_fee_charged": "3"}},
          "Soroban transaction meta extension at v1."),
    _seed("TransactionPhase", "TransactionPhaseXDR", {"v0": []},
          "Transaction phase at v0 with no components."),
    _seed("TransactionPhase", "TransactionPhaseXDR",
          {"v1": {"base_fee": None, "execution_stages": []}},
          "Transaction phase at its non-zero int-cased arm."),
    _seed("TransactionMeta", "TransactionMetaXDR", {"v0": []},
          "Transaction meta at v0 with no operations."),
    _seed("TransactionMeta", "TransactionMetaXDR",
          {"v1": {"tx_changes": [], "operations": []}},
          "Transaction meta at v1."),
    _seed("LedgerCloseMetaExt", "LedgerCloseMetaExtXDR", "v0",
          "Ledger close meta extension at v0."),
    _seed("LedgerCloseMetaExt", "LedgerCloseMetaExtXDR",
          {"v1": {"ext": "v0", "soroban_fee_write1_kb": "1"}},
          "Ledger close meta extension at v1."),

    # --- Standalone 64-bit integers: SEP-0051 requires a string ------------
    _seed("Int64", "Int64XDR", 0,
          "Standalone signed 64-bit zero must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Int64", "Int64XDR", 1,
          "Standalone signed 64-bit one must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Int64", "Int64XDR", -1,
          "Standalone signed 64-bit minus one must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Int64", "Int64XDR", -9223372036854775808,
          "Standalone signed 64-bit minimum must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Int64", "Int64XDR", 9223372036854775807,
          "Standalone signed 64-bit maximum must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Uint64", "Uint64XDR", 0,
          "Standalone unsigned 64-bit zero must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Uint64", "Uint64XDR", 1,
          "Standalone unsigned 64-bit one must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),
    _seed("Uint64", "Uint64XDR", 18446744073709551615,
          "Standalone unsigned 64-bit maximum must render as a string.",
          oracle="incomparable", spec_form="integer_string",
          spec_form_paths=[""]),

    # --- Inline fixed opaque: SEP-0051 requires lowercase hex --------------
    _seed("Curve25519Secret", "Curve25519SecretXDR", {"key": BYTES_32},
          "Inline fixed opaque must render as lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["key"]),
    _seed("Curve25519Secret", "Curve25519SecretXDR", {"key": BYTES_32_ZERO},
          "All-zero inline fixed opaque must render as 64 hex zeros.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["key"]),
    _seed("Curve25519Public", "Curve25519PublicXDR", {"key": BYTES_32},
          "Inline fixed opaque must render as lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["key"]),
    _seed("HmacSha256Key", "HmacSha256KeyXDR", {"key": BYTES_32},
          "Inline fixed opaque must render as lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["key"]),
    _seed("HmacSha256Mac", "HmacSha256MacXDR", {"mac": [255] * 32},
          "Inline fixed opaque must render as lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["mac"]),
    _seed("ShortHashSeed", "ShortHashSeedXDR", {"seed": BYTES_16},
          "Inline 16-byte fixed opaque must render as lowercase hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["seed"]),

    # --- Misc scalars and small structs ------------------------------------
    _seed("Price", "PriceXDR", {"n": -2147483648, "d": 2147483647},
          "Price at both signed 32-bit extremes."),
    _seed("Int32", "Int32XDR", -2147483648,
          "Standalone signed 32-bit minimum renders as a number."),
    _seed("Uint32", "Uint32XDR", 4294967295,
          "Standalone unsigned 32-bit maximum renders as a number."),
    _seed("DecoratedSignature", "DecoratedSignatureXDR",
          {"hint": "01020304", "signature": ""},
          "Decorated signature with an empty variable opaque signature."),
    _seed("DecoratedSignature", "DecoratedSignatureXDR",
          {"hint": "ffffffff", "signature": "aabb"},
          "Decorated signature with data."),
    _seed("ContractCostParams", "ContractCostParamsXDR", [],
          "Empty variable array typedef renders as an empty array."),
    _seed("ContractCostParams", "ContractCostParamsXDR",
          [{"ext": "v0", "const_term": "1", "linear_term": "2"}],
          "Variable array typedef with one entry."),
    _seed("ConfigSettingEntry", "ConfigSettingEntryXDR",
          {"contract_max_size_bytes": 100},
          "Config setting entry arm carrying a 32-bit value."),
    _seed("ConfigSettingEntry", "ConfigSettingEntryXDR",
          {"contract_compute_v0": {"ledger_max_instructions": "1",
                                   "tx_max_instructions": "2",
                                   "fee_rate_per_instructions_increment": "3",
                                   "tx_memory_limit": 4}},
          "Config setting entry arm carrying a struct."),
    _seed("ThresholdIndexes", "ThresholdIndexesXDR", "master_weight",
          "Threshold index enum member is stripped of its shared prefix."),
    _seed("EnvelopeType", "EnvelopeType", "tx",
          "Envelope type enum member is stripped of its shared prefix."),
    _seed("EnvelopeType", "EnvelopeType", "soroban_authorization",
          "Multi-word envelope type enum member."),
    _seed("ContractCostType", "ContractCostType", "wasm_insn_exec",
          "Contract cost type enum member."),
    _seed("ClaimAtom", "ClaimAtomXDR",
          {"v0": {"seller_ed25519": HASH1, "offer_id": "1",
                  "asset_sold": "native", "amount_sold": "1",
                  "asset_bought": ASSET_A4, "amount_bought": "2"}},
          "Claim atom at its version 0 arm."),
    _seed("ClaimAtom", "ClaimAtomXDR",
          {"liquidity_pool": {"liquidity_pool_id": L1, "asset_sold": "native",
                              "amount_sold": "1", "asset_bought": ASSET_A4,
                              "amount_bought": "2"}},
          "Claim atom at its liquidity pool arm."),
    _seed("RevokeSponsorshipOp", "RevokeSponsorshipOpXDR",
          {"ledger_entry": {"offer": {"seller_id": G1, "offer_id": "3"}}},
          "Revoke sponsorship targeting a ledger entry key."),
    _seed("RevokeSponsorshipOp", "RevokeSponsorshipOpXDR",
          {"signer": {"account_id": G1, "signer_key": P_SHORT}},
          "Revoke sponsorship targeting a signed payload signer."),
    _seed("BucketEntry", "BucketEntryXDR",
          {"metaentry": {"ledger_version": 23, "ext": "v0"}},
          "Bucket metadata entry arm keeps its unsplit member name."),
    _seed("BucketEntry", "BucketEntryXDR",
          {"deadentry": {"contract_code": {"hash": HASH1}}},
          "Bucket dead entry arm carries a ledger key."),
    _seed("HotArchiveBucketEntry", "HotArchiveBucketEntryXDR",
          {"archived": {"last_modified_ledger_seq": 1,
                        "data": {"ttl": {"key_hash": HASH1,
                                         "live_until_ledger_seq": 2}},
                        "ext": "v0"}},
          "Hot archive archived entry arm."),
    _seed("HotArchiveBucketEntry", "HotArchiveBucketEntryXDR",
          {"live": {"contract_code": {"hash": HASH1}}},
          "Hot archive live entry arm carries a ledger key."),
    _seed("TtlEntry", "TTLEntryXDR",
          {"key_hash": HASH1, "live_until_ledger_seq": 0},
          "TTL entry renders its hash as hex and its sequence as a number."),
    _seed("ContractDataEntry", "ContractDataEntryXDR",
          {"ext": "v0", "contract": C1, "key": {"symbol": "k"},
           "durability": "temporary", "val": "void"},
          "Contract data entry keys its fields in declaration order."),

    # --- Overlay enums ------------------------------------------------------
    # Enum members whose derivation is mechanical are pinned by the emitted
    # per-member suite; the corpus carries the ones a pin bump could disturb.
    _seed("IpAddrType", "IPAddrTypeXDR", "i_pv4",
          "Address family member IPv4 splits into two words and renders as i_pv4."),
    _seed("IpAddrType", "IPAddrTypeXDR", "i_pv6",
          "Address family member IPv6 splits into two words and renders as i_pv6."),
    _seed("ErrorCode", "ErrorCodeXDR", "misc",
          "Overlay error code member is stripped of its shared prefix."),
    _seed("ErrorCode", "ErrorCodeXDR", "load",
          "Overlay error code member for overload."),
    _seed("MessageType", "MessageTypeXDR", "error_msg",
          "Overlay message type member at its zero value."),
    _seed("MessageType", "MessageTypeXDR", "dont_have",
          "Overlay message type member spanning two words."),
    _seed("MessageType", "MessageTypeXDR", "generalized_tx_set",
          "Overlay message type member whose numeric value is out of declaration order."),
    _seed("MessageType", "MessageTypeXDR", "get_scp_quorumset",
          "Overlay message type member keeping quorumset as a single word."),
    _seed("MessageType", "MessageTypeXDR", "time_sliced_survey_start_collecting",
          "Longest overlay message type member, five words after the shared prefix."),
    _seed("SurveyMessageCommandType", "SurveyMessageCommandTypeXDR",
          "time_sliced_survey_topology",
          "Single-member survey command enum keeps its full identifier."),
    _seed("SurveyMessageResponseType", "SurveyMessageResponseTypeXDR",
          "survey_topology_response_v2",
          "Single-member survey response enum keeps its full identifier."),

    # --- Overlay: the reserved-name type escape -----------------------------
    _seed("SError", "ErrorXDR", {"code": "misc", "msg": "oops"},
          "Overlay error struct, which the reference addresses under the escaped "
          "name SError."),
    _seed("SError", "ErrorXDR", {"code": "conf", "msg": "a\\tb"},
          "Overlay error message applies the short escape for tab."),
    _seed("SError", "ErrorXDR", {"code": "load", "msg": "caf\\xc3\\xa9"},
          "Overlay error message escapes each byte of a non-ASCII character "
          "separately as \\xNN and leaves the ASCII bytes verbatim."),

    # --- Overlay: the address family union and its container ----------------
    _seed("PeerAddressIp", "PeerAddressXDRIpXDR", {"i_pv4": BYTES_4},
          "IPv4 arm declares its opaque inline, so SEP-0051 requires hex where the "
          "reference emits a byte array.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["i_pv4"]),
    _seed("PeerAddressIp", "PeerAddressXDRIpXDR", {"i_pv6": BYTES_16},
          "IPv6 arm declares its opaque inline, so SEP-0051 requires hex.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["i_pv6"]),
    _seed("PeerAddress", "PeerAddressXDR",
          {"ip": {"i_pv4": BYTES_4}, "port": 4851, "num_failures": 1},
          "Peer address carries the inline opaque inside a union arm; the two 32-bit "
          "counters stay numbers.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["ip.i_pv4"]),
    _seed("PeerAddress", "PeerAddressXDR",
          {"ip": {"i_pv6": BYTES_16_ZERO}, "port": 0, "num_failures": 4294967295},
          "Peer address at the IPv6 arm; an all-zero address renders as 32 hex zeros, "
          "never as an empty string.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["ip.i_pv6"]),

    # --- Overlay: the remaining structs and unions --------------------------
    _seed("Auth", "AuthXDR", {"flags": 200},
          "Auth message carries a bare 32-bit flag word."),
    _seed("SendMore", "SendMoreXDR", {"num_messages": 10},
          "Flow control message renders numMessages as num_messages."),
    _seed("SendMoreExtended", "SendMoreExtendedXDR",
          {"num_messages": 1, "num_bytes": 4294967295},
          "Byte-based flow control message at the unsigned 32-bit maximum."),
    _seed("AuthCert", "AuthCertXDR",
          {"pubkey": {"key": BYTES_32}, "expiration": "1735689600", "sig": "aabb"},
          "Auth certificate nests an inline fixed opaque public key next to a "
          "variable opaque signature.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["pubkey.key"]),
    _seed("DontHave", "DontHaveXDR",
          {"type": "error_msg", "req_hash": HASH1},
          "Don't-have message renders its discriminant field under the key type and "
          "accepts the escaped spelling on input.",
          input_variants=[{"type_": "error_msg", "req_hash": HASH1}]),
    _seed("DontHave", "DontHaveXDR",
          {"type": "tx_set", "req_hash": HASH_ZERO},
          "Don't-have message naming a transaction set, with an all-zero hash.",
          input_variants=[{"type_": "tx_set", "req_hash": HASH_ZERO}]),
    _seed("PeerStats", "PeerStatsXDR", PEER_STATS,
          "Peer statistics render fifteen 64-bit counters as strings around a "
          "strkey and an escaped string."),
    _seed("TimeSlicedNodeData", "TimeSlicedNodeDataXDR", NODE_DATA,
          "Node data renders p75SCPFirstToSelfLatencyMs with its digit and acronym "
          "split apart."),
    _seed("TimeSlicedNodeData", "TimeSlicedNodeDataXDR",
          {"added_authenticated_peers": 0, "dropped_authenticated_peers": 0,
           "total_inbound_peer_count": 0, "total_outbound_peer_count": 0,
           "p75_scp_first_to_self_latency_ms": 4294967295,
           "p75_scp_self_to_other_latency_ms": 4294967295,
           "lost_sync_count": 4294967295, "is_validator": False,
           "max_inbound_peer_count": 0, "max_outbound_peer_count": 0},
          "Node data with the boolean false and the latency counters at their maximum."),
    _seed("TimeSlicedPeerData", "TimeSlicedPeerDataXDR",
          {"peer_stats": PEER_STATS, "average_latency_ms": 42},
          "Peer data wraps the statistics struct."),
    _seed("TimeSlicedPeerDataList", "TimeSlicedPeerDataListXDR", [],
          "Empty bounded array typedef renders as an empty array."),
    _seed("TimeSlicedPeerDataList", "TimeSlicedPeerDataListXDR",
          [{"peer_stats": PEER_STATS, "average_latency_ms": 0}],
          "Bounded array typedef with one entry."),
    _seed("TopologyResponseBodyV2", "TopologyResponseBodyV2XDR",
          {"inbound_peers": [{"peer_stats": PEER_STATS, "average_latency_ms": 1}],
           "outbound_peers": [], "node_data": NODE_DATA},
          "Topology response with one peer list populated and the other empty."),
    _seed("SurveyResponseBody", "SurveyResponseBodyXDR",
          {"survey_topology_response_v2": {"inbound_peers": [], "outbound_peers": [],
                                           "node_data": NODE_DATA}},
          "Sole survey response arm keys on its enum member name."),
    _seed("SurveyRequestMessage", "SurveyRequestMessageXDR",
          {"surveyor_peer_id": G1, "surveyed_peer_id": G1, "ledger_num": 9,
           "encryption_key": {"key": BYTES_32},
           "command_type": "time_sliced_survey_topology"},
          "Survey request carries an inline fixed opaque encryption key.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["encryption_key.key"]),
    _seed("SurveyResponseMessage", "SurveyResponseMessageXDR", SURVEY_RESPONSE,
          "Survey response renders its variable opaque body as hex."),
    _seed("TimeSlicedSurveyResponseMessage", "TimeSlicedSurveyResponseMessageXDR",
          {"response": SURVEY_RESPONSE, "nonce": 3},
          "Time-sliced survey response wraps the response message."),
    _seed("SignedTimeSlicedSurveyResponseMessage",
          "SignedTimeSlicedSurveyResponseMessageXDR",
          {"response_signature": "0a0b",
           "response": {"response": SURVEY_RESPONSE, "nonce": 3}},
          "Signed time-sliced survey response nests two levels of message."),
    _seed("TimeSlicedSurveyStartCollectingMessage",
          "TimeSlicedSurveyStartCollectingMessageXDR", START_COLLECTING,
          "Survey start signal renders surveyorID as surveyor_id."),
    _seed("SignedTimeSlicedSurveyStartCollectingMessage",
          "SignedTimeSlicedSurveyStartCollectingMessageXDR",
          {"signature": "", "start_collecting": START_COLLECTING},
          "Signed survey start signal with an empty variable opaque signature."),
    _seed("TimeSlicedSurveyStopCollectingMessage",
          "TimeSlicedSurveyStopCollectingMessageXDR", STOP_COLLECTING,
          "Survey stop signal at the unsigned 32-bit maximum nonce."),
    _seed("SignedTimeSlicedSurveyStopCollectingMessage",
          "SignedTimeSlicedSurveyStopCollectingMessageXDR",
          {"signature": "ff", "stop_collecting": STOP_COLLECTING},
          "Signed survey stop signal with a one-byte signature."),
    _seed("FloodAdvert", "FloodAdvertXDR", {"tx_hashes": []},
          "Pull-mode advert with an empty hash vector."),
    _seed("FloodDemand", "FloodDemandXDR", {"tx_hashes": [HASH1, HASH_ZERO]},
          "Pull-mode demand with two hashes."),
    _seed("EncryptedBody", "EncryptedBodyXDR", "deadbeef",
          "Variable opaque typedef renders as lowercase hex."),
    _seed("TxAdvertVector", "TxAdvertVectorXDR", [],
          "Empty bounded hash vector typedef renders as an empty array."),
    _seed("TxDemandVector", "TxDemandVectorXDR", [HASH1, HASH_ZERO],
          "Bounded hash vector typedef with two hashes."),
    _seed("AuthenticatedMessageV0", "AuthenticatedMessageXDRV0XDR",
          {"sequence": "1", "message": {"auth": {"flags": 0}},
           "mac": {"mac": BYTES_32}},
          "Authenticated message body carries an inline fixed opaque MAC.",
          oracle="incomparable", spec_form="opaque_hex",
          spec_form_paths=["mac.mac"]),

    # --- Overlay: arms of the message union ---------------------------------
    # The arms carrying an inline fixed opaque below the immediate field -- hello,
    # peers and the survey request -- are seeded through the narrower types that
    # declare that opaque, so the transform is never applied to a whole message.
    _seed("StellarMessage", "StellarMessageXDR",
          {"error_msg": {"code": "misc", "msg": "boom"}},
          "Error arm of the overlay message union."),
    _seed("StellarMessage", "StellarMessageXDR",
          {"dont_have": {"type": "tx_set", "req_hash": HASH1}},
          "Don't-have arm of the overlay message union."),
    _seed("StellarMessage", "StellarMessageXDR", {"get_tx_set": HASH1},
          "Transaction set request arm carries a bare 32-byte hash."),
    _seed("StellarMessage", "StellarMessageXDR",
          {"generalized_tx_set": {"v1": {"previous_ledger_hash": HASH1,
                                         "phases": []}}},
          "Generalized transaction set arm nests an int-cased union."),
    _seed("StellarMessage", "StellarMessageXDR", {"transaction": TX_ENVELOPE_V0},
          "Transaction arm carries a full envelope."),
    _seed("StellarMessage", "StellarMessageXDR", {"scp_message": SCP_ENVELOPE},
          "SCP message arm carries an envelope."),
    _seed("StellarMessage", "StellarMessageXDR", {"get_scp_state": 0},
          "SCP state request arm carries a bare 32-bit number."),
    _seed("StellarMessage", "StellarMessageXDR",
          {"time_sliced_survey_response": {
              "response_signature": "0a",
              "response": {"response": SURVEY_RESPONSE, "nonce": 1}}},
          "Time-sliced survey response arm of the overlay message union."),

    # --- SCP: the types the overlay and internal messages carry -------------
    _seed("ScpStatementType", "SCPStatementTypeXDR", "prepare",
          "SCP statement type member is stripped of its shared prefix."),
    _seed("ScpStatementType", "SCPStatementTypeXDR", "confirm",
          "SCP statement type member for confirm."),
    _seed("ScpStatementType", "SCPStatementTypeXDR", "externalize",
          "SCP statement type member for externalize."),
    _seed("ScpStatementType", "SCPStatementTypeXDR", "nominate",
          "SCP statement type member for nominate."),
    _seed("ScpBallot", "SCPBallotXDR", {"counter": 0, "value": ""},
          "Ballot with an empty variable opaque value."),
    _seed("ScpNomination", "SCPNominationXDR",
          {"quorum_set_hash": HASH_ZERO, "votes": ["00"],
           "accepted": ["ff", "0102"]},
          "Nomination with populated vote arrays of variable opaque values."),
    _seed("ScpQuorumSet", "SCPQuorumSetXDR",
          {"threshold": 2, "validators": [], "inner_sets": [SCP_QUORUM_SET]},
          "Quorum set nesting one inner set."),
    _seed("ScpStatementPledges", "SCPStatementXDRPledgesXDR",
          {"prepare": {"quorum_set_hash": HASH1, "ballot": SCP_BALLOT,
                       "prepared": None, "prepared_prime": None,
                       "n_c": 0, "n_h": 0}},
          "Prepare pledge arm with both optional ballots unset."),
    _seed("ScpStatementPledges", "SCPStatementXDRPledgesXDR",
          {"prepare": {"quorum_set_hash": HASH1, "ballot": SCP_BALLOT,
                       "prepared": SCP_BALLOT, "prepared_prime": SCP_BALLOT,
                       "n_c": 1, "n_h": 2}},
          "Prepare pledge arm with both optional ballots set."),
    _seed("ScpStatementPledges", "SCPStatementXDRPledgesXDR",
          {"confirm": {"ballot": SCP_BALLOT, "n_prepared": 1, "n_commit": 2,
                       "n_h": 3, "quorum_set_hash": HASH1}},
          "Confirm pledge arm keys nPrepared as n_prepared."),
    _seed("ScpStatementPledges", "SCPStatementXDRPledgesXDR",
          {"externalize": {"commit": SCP_BALLOT, "n_h": 4,
                           "commit_quorum_set_hash": HASH1}},
          "Externalize pledge arm of the SCP statement union."),
    _seed("ScpStatement", "SCPStatementXDR",
          {"node_id": G1, "slot_index": UINT64_MAX,
           "pledges": {"nominate": SCP_NOMINATION}},
          "SCP statement at the unsigned 64-bit maximum slot index."),
    _seed("ScpEnvelope", "SCPEnvelopeXDR", SCP_ENVELOPE,
          "SCP envelope pairs a statement with a signature."),
    _seed("TransactionSet", "TransactionSetXDR", TX_SET_V0,
          "Legacy transaction set with no transactions."),
    _seed("TransactionSetV1", "TransactionSetV1XDR",
          {"previous_ledger_hash": HASH1, "phases": []},
          "Version 1 transaction set with no phases."),
    _seed("GeneralizedTransactionSet", "GeneralizedTransactionSetXDR",
          {"v1": {"previous_ledger_hash": HASH1, "phases": [{"v0": []}]}},
          "Generalized transaction set at its sole int-cased arm."),

    # --- Internal: the state Core persists ----------------------------------
    _seed("StoredTransactionSet", "StoredTransactionSetXDR", {"v0": TX_SET_V0},
          "Stored transaction set at its zero-valued int case."),
    _seed("StoredTransactionSet", "StoredTransactionSetXDR",
          {"v1": {"v1": {"previous_ledger_hash": HASH1, "phases": []}}},
          "Stored transaction set at its non-zero int case, nesting a second "
          "int-cased union."),
    _seed("StoredDebugTransactionSet", "StoredDebugTransactionSetXDR",
          {"tx_set": {"v0": TX_SET_V0}, "ledger_seq": 7,
           "scp_value": {"tx_set_hash": HASH1, "close_time": "0",
                         "upgrades": [], "ext": "basic"}},
          "Stored debug transaction set nests a stored set and an SCP value."),
    _seed("PersistedScpStateV0", "PersistedSCPStateV0XDR",
          {"scp_envelopes": [SCP_ENVELOPE], "quorum_sets": [SCP_QUORUM_SET],
           "tx_sets": [{"v0": TX_SET_V0}]},
          "Version 0 persisted SCP state with every array populated."),
    _seed("PersistedScpStateV1", "PersistedSCPStateV1XDR",
          {"scp_envelopes": [], "quorum_sets": []},
          "Version 1 persisted SCP state with both arrays empty."),
    _seed("PersistedScpState", "PersistedSCPStateXDR",
          {"v0": {"scp_envelopes": [], "quorum_sets": [], "tx_sets": []}},
          "Persisted SCP state at its zero-valued int case."),
    _seed("PersistedScpState", "PersistedSCPStateXDR",
          {"v1": {"scp_envelopes": [SCP_ENVELOPE], "quorum_sets": []}},
          "Persisted SCP state at its non-zero int case."),

    # --- Exporter -----------------------------------------------------------
    _seed("LedgerCloseMetaBatch", "LedgerCloseMetaBatchXDR",
          {"start_sequence": 4294967295, "end_sequence": 0,
           "ledger_close_metas": []},
          "Ledger close meta batch at the unsigned 32-bit maximum sequence."),

    # --- Both arms of every pair several XDR definitions render differently -
    # The Swift form of such a pair carries no conversion of its own, so each side
    # is seeded through the union that selects it. A fixture exercising one side
    # cannot see a helper emitting the other side's names.
    _seed("Operation", "OperationXDR",
          {"source_account": None,
           "body": {"path_payment_strict_receive": {
               "send_asset": "native", "send_max": "100", "destination": G1,
               "dest_asset": ASSET_A4, "dest_amount": "50", "path": []}}},
          "Strict receive path payment names its bounds send_max and dest_amount."),
    _seed("Operation", "OperationXDR",
          {"source_account": None,
           "body": {"path_payment_strict_send": {
               "send_asset": "native", "send_amount": "100", "destination": G1,
               "dest_asset": ASSET_A4, "dest_min": "50", "path": []}}},
          "Strict send path payment names the same two positions send_amount and "
          "dest_min."),
    _seed("Operation", "OperationXDR",
          {"source_account": None,
           "body": {"manage_sell_offer": {
               "selling": "native", "buying": ASSET_A4, "amount": "7",
               "price": {"n": 1, "d": 2}, "offer_id": "0"}}},
          "Manage sell offer names its third position amount."),
    _seed("Operation", "OperationXDR",
          {"source_account": None,
           "body": {"manage_buy_offer": {
               "selling": "native", "buying": ASSET_A4, "buy_amount": "7",
               "price": {"n": 1, "d": 2}, "offer_id": "0"}}},
          "Manage buy offer names the same position buy_amount."),
    _seed("OperationResult", "OperationResultXDR",
          {"op_inner": {"path_payment_strict_receive": "over_sendmax"}},
          "Strict receive result code -12 renders as over_sendmax."),
    _seed("OperationResult", "OperationResultXDR",
          {"op_inner": {"path_payment_strict_send": "under_destmin"}},
          "Strict send result code -12 renders as under_destmin."),
    _seed("OperationResult", "OperationResultXDR",
          {"op_inner": {"path_payment_strict_receive": {
              "success": {"offers": [], "last": SIMPLE_PAYMENT_RESULT}}}},
          "Strict receive result at its success arm."),
    _seed("OperationResult", "OperationResultXDR",
          {"op_inner": {"path_payment_strict_send": {
              "success": {"offers": [], "last": SIMPLE_PAYMENT_RESULT}}}},
          "Strict send result at its success arm."),
    _seed("OperationResult", "OperationResultXDR",
          {"op_inner": {"path_payment_strict_receive": {"no_issuer": "native"}}},
          "Strict receive result carrying the offending asset."),
    _seed("OperationResult", "OperationResultXDR",
          {"op_inner": {"path_payment_strict_send": {"no_issuer": ASSET_A4}}},
          "Strict send result carrying the offending asset."),
    _seed("OperationResultTr", "OperationResultXDRTrXDR",
          {"path_payment_strict_receive": "over_sendmax"},
          "The union that selects each path payment result, at the strict receive arm."),
    _seed("OperationResultTr", "OperationResultXDRTrXDR",
          {"path_payment_strict_send": "under_destmin"},
          "The same union at the strict send arm."),
    _seed("OperationResultTr", "OperationResultXDRTrXDR",
          {"manage_sell_offer": {"success": {"offers_claimed": [],
                                             "offer": "deleted"}}},
          "The union that selects each offer result, at the sell arm."),
    _seed("OperationResultTr", "OperationResultXDRTrXDR",
          {"manage_buy_offer": {"success": {"offers_claimed": [],
                                            "offer": "deleted"}}},
          "The same union at the buy arm."),
    _seed("SimplePaymentResult", "SimplePaymentResultXDR", SIMPLE_PAYMENT_RESULT,
          "The payload both path payment success arms carry."),

    # --- The alternative input spelling of a field named type ---------------
    # The reference emits `type` and accepts `type_`, so the escaped spelling
    # cannot arrive through the normal path. Each variant is encoded with the
    # reference and required to produce the entry's own base64.
    _seed("ContractEvent", "ContractEventXDR",
          {"ext": "v0", "contract_id": C1, "type": "diagnostic",
           "body": {"v0": {"topics": [{"symbol": "log"}], "data": {"u32": 7}}}},
          "Contract event accepts the escaped spelling of its type key on input.",
          input_variants=[{"ext": "v0", "contract_id": C1, "type_": "diagnostic",
                           "body": {"v0": {"topics": [{"symbol": "log"}],
                                           "data": {"u32": 7}}}}]),
    _seed("ScSpecUdtStructFieldV0", "SCSpecUDTStructFieldV0XDR",
          {"doc": "d", "name": "amount", "type": "u128"},
          "Struct field spec accepts the escaped spelling of its type key on input.",
          input_variants=[{"doc": "d", "name": "amount", "type_": "u128"}]),
    _seed("ScSpecUdtUnionCaseTupleV0", "SCSpecUDTUnionCaseTupleV0XDR",
          {"doc": "d", "name": "Pair", "type": ["address", "u64"]},
          "Union case tuple spec accepts the escaped spelling of its type key.",
          input_variants=[{"doc": "d", "name": "Pair",
                           "type_": ["address", "u64"]}]),
    _seed("ScSpecFunctionInputV0", "SCSpecFunctionInputV0XDR",
          {"doc": "", "name": "to", "type": "address"},
          "Function input spec accepts the escaped spelling of its type key.",
          input_variants=[{"doc": "", "name": "to", "type_": "address"}]),
    _seed("ScSpecEventParamV0", "SCSpecEventParamV0XDR",
          {"doc": "", "name": "amount", "type": "i128", "location": "topic_list"},
          "Event parameter spec accepts the escaped spelling of its type key.",
          input_variants=[{"doc": "", "name": "amount", "type_": "i128",
                           "location": "topic_list"}]),
]
