//
//  SEP30Responses.swift
//  stellarsdk
//
//  Created by Christian Rogobete on 27.10.23.
//  Copyright © 2023 Soneso. All rights reserved.
//

import Foundation

/// Identity information in recovery service responses.
///
/// Contains the role of an identity and optionally indicates if the current client
/// is authenticated as this identity.
public struct SEP30ResponseIdentity: Decodable {

    /// Role of this identity in relation to the account.
    /// Common values: "owner", "sender", "receiver".
    public var role: String

    /// Indicates if the currently authenticated client matches this identity.
    /// Present and true when the authenticated JWT corresponds to this identity's authentication methods.
    public var authenticated: Bool?

    /// Properties to encode and decode
    private enum CodingKeys: String, CodingKey {
        case role
        case authenticated
    }

    /**
     Initializer - creates a new instance by decoding from the given decoder.

     - Parameter decoder: The decoder containing the data
     */
    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        role = try values.decode(String.self, forKey: .role)
        authenticated = try values.decodeIfPresent(Bool.self, forKey: .authenticated)
    }
}

/// Signer key information provided by the recovery service.
///
/// Contains the public key that the recovery service can use to sign transactions
/// for the associated account.
public struct SEP30ResponseSigner: Decodable {

    /// Public key of the signer that the recovery service generated for this account.
    /// This key should be added as a signer to the Stellar account with appropriate weight.
    public var key: String

    /// Properties to encode and decode
    private enum CodingKeys: String, CodingKey {
        case key
    }

    /**
     Initializer - creates a new instance by decoding from the given decoder.

     - Parameter decoder: The decoder containing the data
     */
    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        key = try values.decode(String.self, forKey: .key)
    }
}

/// Response for account registration, update, retrieval, and deletion operations.
///
/// Contains the account address, configured identities, and signer keys available
/// for account recovery transactions.
public struct Sep30AccountResponse: Decodable {

    /// Stellar account address (public key) for the registered account.
    public var address: String

    /// List of identities configured for this account.
    /// Authentication methods are not included to prevent leaking identity information between users of shared accounts.
    public var identities: [SEP30ResponseIdentity]

    /// Signer public keys available for signing transactions for this account.
    /// Ordered from most recently added to least recently added. Use the first signer as it represents the current key.
    public var signers: [SEP30ResponseSigner]

    /// Properties to encode and decode
    private enum CodingKeys: String, CodingKey {
        case address
        case identities
        case signers
    }

    /**
     Initializer - creates a new instance by decoding from the given decoder.

     - Parameter decoder: The decoder containing the data
     */
    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        address = try values.decode(String.self, forKey: .address)
        identities = try values.decode([SEP30ResponseIdentity].self, forKey: .identities)
        signers = try values.decode([SEP30ResponseSigner].self, forKey: .signers)
    }
}

/// Response for listing accounts accessible by the authenticated client.
///
/// Returns all accounts that the JWT token grants access to, including accounts
/// where the authenticated identity is registered as an authorized identity.
public struct Sep30AccountsResponse: Decodable {

    /// List of accounts accessible by the authenticated client.
    /// Use the after query parameter for cursor-based pagination.
    public var accounts: [Sep30AccountResponse]

    /// Properties to encode and decode
    private enum CodingKeys: String, CodingKey {
        case accounts
    }

    /**
     Initializer - creates a new instance by decoding from the given decoder.

     - Parameter decoder: The decoder containing the data
     */
    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        accounts = try values.decode([Sep30AccountResponse].self, forKey: .accounts)
    }
}

/// Response for transaction signing operations.
///
/// Contains the signature generated by the recovery service and the network passphrase
/// used during signing.
public struct Sep30SignatureResponse: Decodable {

    /// Base64 encoded signature produced by signing the transaction with the recovery service's signing key.
    /// This signature should be added to the transaction's signatures.
    public var signature: String

    /// Network passphrase used when generating the signature.
    /// Verifies that the signature is valid for the intended Stellar network.
    public var networkPassphrase: String

    /// Properties to encode and decode
    private enum CodingKeys: String, CodingKey {
        case signature
        case networkPassphrase = "network_passphrase"
    }

    /**
     Initializer - creates a new instance by decoding from the given decoder.

     - Parameter decoder: The decoder containing the data
     */
    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        signature = try values.decode(String.self, forKey: .signature)
        networkPassphrase = try values.decode(String.self, forKey: .networkPassphrase)
    }
}

