// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum AssetXDR: XDRCodable, Sendable {
  case native
  case alphanum4(Alpha4XDR)
  case alphanum12(Alpha12XDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case AssetType.native.rawValue:
      self = .native
    case AssetType.creditAlphanum4.rawValue:
      let val = try container.decode(Alpha4XDR.self)
      self = .alphanum4(val)
    case AssetType.creditAlphanum12.rawValue:
      let val = try container.decode(Alpha12XDR.self)
      self = .alphanum12(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown AssetXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .native: return AssetType.native.rawValue
    case .alphanum4: return AssetType.creditAlphanum4.rawValue
    case .alphanum12: return AssetType.creditAlphanum12.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .native:
      break
    case .alphanum4(let val):
      try container.encode(val)
    case .alphanum12(let val):
      try container.encode(val)
    }
  }
}

extension AssetXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    switch self {
    case .native:
      lines.append("\(prefix).type: ASSET_TYPE_NATIVE")
    case .alphanum4(let val):
      lines.append("\(prefix).type: ASSET_TYPE_CREDIT_ALPHANUM4")
      try val.toTxRep(prefix: "\(prefix).alphaNum4", lines: &lines)
    case .alphanum12(let val):
      lines.append("\(prefix).type: ASSET_TYPE_CREDIT_ALPHANUM12")
      try val.toTxRep(prefix: "\(prefix).alphaNum12", lines: &lines)
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> AssetXDR {
    let discKey = "\(prefix).type"
    guard let discName = TxRepHelper.getValue(map, discKey) else {
      throw TxRepError.missingValue(key: discKey)
    }
    switch discName {
    case "ASSET_TYPE_NATIVE":
      return .native
    case "ASSET_TYPE_CREDIT_ALPHANUM4":
      let val = try Alpha4XDR.fromTxRep(map, prefix: "\(prefix).alphaNum4")
      return .alphanum4(val)
    case "ASSET_TYPE_CREDIT_ALPHANUM12":
      let val = try Alpha12XDR.fromTxRep(map, prefix: "\(prefix).alphaNum12")
      return .alphanum12(val)
    default:
      throw TxRepError.invalidValue(key: discKey)
    }
  }
}

extension AssetXDR: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .native: return .string("native")
    case .alphanum4(let payload):
      return .object([XdrJsonMember(key: "credit_alphanum4", value: try payload.toXdrJsonValue())])
    case .alphanum12(let payload):
      return .object([XdrJsonMember(key: "credit_alphanum12", value: try payload.toXdrJsonValue())])
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> AssetXDR {
    if case .string(let name) = value {
      switch name {
      case "native":
        return .native
      case "credit_alphanum4":
        throw XdrJsonError.invalidValue(type: "AssetXDR", key: "credit_alphanum4",
                                        message: "this arm carries a value, so it is written as a single-key object")
      case "credit_alphanum12":
        throw XdrJsonError.invalidValue(type: "AssetXDR", key: "credit_alphanum12",
                                        message: "this arm carries a value, so it is written as a single-key object")
      default:
        throw XdrJsonError.unknownUnionArm(type: "AssetXDR", key: name)
      }
    }

    let member = try XdrJson.singleKeyObject(value, type: "AssetXDR")
    switch member.key {
    case "native":
      throw XdrJsonError.invalidValue(type: "AssetXDR", key: "native",
                                      message: "this arm carries no value, so it is written as a bare string")
    case "credit_alphanum4":
      let alphanum4: Alpha4XDR = try Alpha4XDR.fromXdrJsonValue(member.value)
      return .alphanum4(alphanum4)
    case "credit_alphanum12":
      let alphanum12: Alpha12XDR = try Alpha12XDR.fromXdrJsonValue(member.value)
      return .alphanum12(alphanum12)
    default:
      throw XdrJsonError.unknownUnionArm(type: "AssetXDR", key: member.key)
    }
  }
}
