// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public enum OperationType: Int32, XDRCodable, Equatable, Sendable {
  case accountCreated = 0
  case payment = 1
  case pathPayment = 2
  case manageSellOffer = 3
  case createPassiveSellOffer = 4
  case setOptions = 5
  case changeTrust = 6
  case allowTrust = 7
  case accountMerge = 8
  case inflation = 9
  case manageData = 10
  case bumpSequence = 11
  case manageBuyOffer = 12
  case pathPaymentStrictSend = 13
  case createClaimableBalance = 14
  case claimClaimableBalance = 15
  case beginSponsoringFutureReserves = 16
  case endSponsoringFutureReserves = 17
  case revokeSponsorship = 18
  case clawback = 19
  case clawbackClaimableBalance = 20
  case setTrustLineFlags = 21
  case liquidityPoolDeposit = 22
  case liquidityPoolWithdraw = 23
  case invokeHostFunction = 24
  case extendFootprintTTL = 25
  case restoreFootprint = 26
}

extension OperationType {
  public func enumName() -> String {
    switch self {
    case .accountCreated: return "CREATE_ACCOUNT"
    case .payment: return "PAYMENT"
    case .pathPayment: return "PATH_PAYMENT_STRICT_RECEIVE"
    case .manageSellOffer: return "MANAGE_SELL_OFFER"
    case .createPassiveSellOffer: return "CREATE_PASSIVE_SELL_OFFER"
    case .setOptions: return "SET_OPTIONS"
    case .changeTrust: return "CHANGE_TRUST"
    case .allowTrust: return "ALLOW_TRUST"
    case .accountMerge: return "ACCOUNT_MERGE"
    case .inflation: return "INFLATION"
    case .manageData: return "MANAGE_DATA"
    case .bumpSequence: return "BUMP_SEQUENCE"
    case .manageBuyOffer: return "MANAGE_BUY_OFFER"
    case .pathPaymentStrictSend: return "PATH_PAYMENT_STRICT_SEND"
    case .createClaimableBalance: return "CREATE_CLAIMABLE_BALANCE"
    case .claimClaimableBalance: return "CLAIM_CLAIMABLE_BALANCE"
    case .beginSponsoringFutureReserves: return "BEGIN_SPONSORING_FUTURE_RESERVES"
    case .endSponsoringFutureReserves: return "END_SPONSORING_FUTURE_RESERVES"
    case .revokeSponsorship: return "REVOKE_SPONSORSHIP"
    case .clawback: return "CLAWBACK"
    case .clawbackClaimableBalance: return "CLAWBACK_CLAIMABLE_BALANCE"
    case .setTrustLineFlags: return "SET_TRUST_LINE_FLAGS"
    case .liquidityPoolDeposit: return "LIQUIDITY_POOL_DEPOSIT"
    case .liquidityPoolWithdraw: return "LIQUIDITY_POOL_WITHDRAW"
    case .invokeHostFunction: return "INVOKE_HOST_FUNCTION"
    case .extendFootprintTTL: return "EXTEND_FOOTPRINT_TTL"
    case .restoreFootprint: return "RESTORE_FOOTPRINT"
    }
  }

  public static func fromTxRepName(_ name: String) throws -> OperationType {
    switch name {
    case "CREATE_ACCOUNT": return .accountCreated
    case "PAYMENT": return .payment
    case "PATH_PAYMENT_STRICT_RECEIVE": return .pathPayment
    case "MANAGE_SELL_OFFER": return .manageSellOffer
    case "CREATE_PASSIVE_SELL_OFFER": return .createPassiveSellOffer
    case "SET_OPTIONS": return .setOptions
    case "CHANGE_TRUST": return .changeTrust
    case "ALLOW_TRUST": return .allowTrust
    case "ACCOUNT_MERGE": return .accountMerge
    case "INFLATION": return .inflation
    case "MANAGE_DATA": return .manageData
    case "BUMP_SEQUENCE": return .bumpSequence
    case "MANAGE_BUY_OFFER": return .manageBuyOffer
    case "PATH_PAYMENT_STRICT_SEND": return .pathPaymentStrictSend
    case "CREATE_CLAIMABLE_BALANCE": return .createClaimableBalance
    case "CLAIM_CLAIMABLE_BALANCE": return .claimClaimableBalance
    case "BEGIN_SPONSORING_FUTURE_RESERVES": return .beginSponsoringFutureReserves
    case "END_SPONSORING_FUTURE_RESERVES": return .endSponsoringFutureReserves
    case "REVOKE_SPONSORSHIP": return .revokeSponsorship
    case "CLAWBACK": return .clawback
    case "CLAWBACK_CLAIMABLE_BALANCE": return .clawbackClaimableBalance
    case "SET_TRUST_LINE_FLAGS": return .setTrustLineFlags
    case "LIQUIDITY_POOL_DEPOSIT": return .liquidityPoolDeposit
    case "LIQUIDITY_POOL_WITHDRAW": return .liquidityPoolWithdraw
    case "INVOKE_HOST_FUNCTION": return .invokeHostFunction
    case "EXTEND_FOOTPRINT_TTL": return .extendFootprintTTL
    case "RESTORE_FOOTPRINT": return .restoreFootprint
    default:
      let prefix = "OperationType#"
      if name.hasPrefix(prefix), let v = Int32(name.dropFirst(prefix.count)), let parsed = OperationType(rawValue: v) {
        return parsed
      }
      throw TxRepError.invalidValue(key: name)
    }
  }

  public func toTxRep(prefix: String, lines: inout [String]) throws {
    lines.append("\(prefix): \(enumName())")
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> OperationType {
    guard let raw = TxRepHelper.getValue(map, prefix) else {
      throw TxRepError.missingValue(key: prefix)
    }
    return try fromTxRepName(raw)
  }
}

extension OperationType: XdrJsonCodable {
  public func toXdrJsonValue() throws -> XdrJsonValue {
    switch self {
    case .accountCreated: return .string("create_account")
    case .payment: return .string("payment")
    case .pathPayment: return .string("path_payment_strict_receive")
    case .manageSellOffer: return .string("manage_sell_offer")
    case .createPassiveSellOffer: return .string("create_passive_sell_offer")
    case .setOptions: return .string("set_options")
    case .changeTrust: return .string("change_trust")
    case .allowTrust: return .string("allow_trust")
    case .accountMerge: return .string("account_merge")
    case .inflation: return .string("inflation")
    case .manageData: return .string("manage_data")
    case .bumpSequence: return .string("bump_sequence")
    case .manageBuyOffer: return .string("manage_buy_offer")
    case .pathPaymentStrictSend: return .string("path_payment_strict_send")
    case .createClaimableBalance: return .string("create_claimable_balance")
    case .claimClaimableBalance: return .string("claim_claimable_balance")
    case .beginSponsoringFutureReserves: return .string("begin_sponsoring_future_reserves")
    case .endSponsoringFutureReserves: return .string("end_sponsoring_future_reserves")
    case .revokeSponsorship: return .string("revoke_sponsorship")
    case .clawback: return .string("clawback")
    case .clawbackClaimableBalance: return .string("clawback_claimable_balance")
    case .setTrustLineFlags: return .string("set_trust_line_flags")
    case .liquidityPoolDeposit: return .string("liquidity_pool_deposit")
    case .liquidityPoolWithdraw: return .string("liquidity_pool_withdraw")
    case .invokeHostFunction: return .string("invoke_host_function")
    case .extendFootprintTTL: return .string("extend_footprint_ttl")
    case .restoreFootprint: return .string("restore_footprint")
    }
  }

  public static func fromXdrJsonValue(_ value: XdrJsonValue) throws -> OperationType {
    let name = try XdrJson.string(value, type: "OperationType")
    switch name {
    case "create_account": return .accountCreated
    case "payment": return .payment
    case "path_payment_strict_receive": return .pathPayment
    case "manage_sell_offer": return .manageSellOffer
    case "create_passive_sell_offer": return .createPassiveSellOffer
    case "set_options": return .setOptions
    case "change_trust": return .changeTrust
    case "allow_trust": return .allowTrust
    case "account_merge": return .accountMerge
    case "inflation": return .inflation
    case "manage_data": return .manageData
    case "bump_sequence": return .bumpSequence
    case "manage_buy_offer": return .manageBuyOffer
    case "path_payment_strict_send": return .pathPaymentStrictSend
    case "create_claimable_balance": return .createClaimableBalance
    case "claim_claimable_balance": return .claimClaimableBalance
    case "begin_sponsoring_future_reserves": return .beginSponsoringFutureReserves
    case "end_sponsoring_future_reserves": return .endSponsoringFutureReserves
    case "revoke_sponsorship": return .revokeSponsorship
    case "clawback": return .clawback
    case "clawback_claimable_balance": return .clawbackClaimableBalance
    case "set_trust_line_flags": return .setTrustLineFlags
    case "liquidity_pool_deposit": return .liquidityPoolDeposit
    case "liquidity_pool_withdraw": return .liquidityPoolWithdraw
    case "invoke_host_function": return .invokeHostFunction
    case "extend_footprint_ttl": return .extendFootprintTTL
    case "restore_footprint": return .restoreFootprint
    default:
      throw XdrJsonError.unknownEnumValue(type: "OperationType", value: name)
    }
  }
}
