// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public indirect enum SCValXDR: XDRCodable, Sendable {
  case bool(Bool)
  case void
  case error(SCErrorXDR)
  case u32(UInt32)
  case i32(Int32)
  case u64(UInt64)
  case i64(Int64)
  case timepoint(UInt64)
  case duration(UInt64)
  case u128(UInt128PartsXDR)
  case i128(Int128PartsXDR)
  case u256(UInt256PartsXDR)
  case i256(Int256PartsXDR)
  case bytes(SCBytesXDR)
  case string(String)
  case symbol(String)
  case vec([SCValXDR]?)
  case map([SCMapEntryXDR]?)
  case address(SCAddressXDR)
  case contractInstance(SCContractInstanceXDR)
  case ledgerKeyContractInstance
  case ledgerKeyNonce(SCNonceKeyXDR)

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    let discriminant = try container.decode(Int32.self)

    switch discriminant {
    case SCValType.bool.rawValue:
      let val = try container.decode(Bool.self)
      self = .bool(val)
    case SCValType.void.rawValue:
      self = .void
    case SCValType.error.rawValue:
      let val = try container.decode(SCErrorXDR.self)
      self = .error(val)
    case SCValType.u32.rawValue:
      let val = try container.decode(UInt32.self)
      self = .u32(val)
    case SCValType.i32.rawValue:
      let val = try container.decode(Int32.self)
      self = .i32(val)
    case SCValType.u64.rawValue:
      let val = try container.decode(UInt64.self)
      self = .u64(val)
    case SCValType.i64.rawValue:
      let val = try container.decode(Int64.self)
      self = .i64(val)
    case SCValType.timepoint.rawValue:
      let val = try container.decode(UInt64.self)
      self = .timepoint(val)
    case SCValType.duration.rawValue:
      let val = try container.decode(UInt64.self)
      self = .duration(val)
    case SCValType.u128.rawValue:
      let val = try container.decode(UInt128PartsXDR.self)
      self = .u128(val)
    case SCValType.i128.rawValue:
      let val = try container.decode(Int128PartsXDR.self)
      self = .i128(val)
    case SCValType.u256.rawValue:
      let val = try container.decode(UInt256PartsXDR.self)
      self = .u256(val)
    case SCValType.i256.rawValue:
      let val = try container.decode(Int256PartsXDR.self)
      self = .i256(val)
    case SCValType.bytes.rawValue:
      let val = try container.decode(SCBytesXDR.self)
      self = .bytes(val)
    case SCValType.string.rawValue:
      let val = try container.decode(String.self)
      self = .string(val)
    case SCValType.symbol.rawValue:
      let val = try container.decode(String.self)
      self = .symbol(val)
    case SCValType.vec.rawValue:
      let vecPresent = try container.decode(Int32.self)
      if vecPresent != 0 {
        self = .vec(try container.decode([SCValXDR].self))
      } else {
        self = .vec(nil)
      }
    case SCValType.map.rawValue:
      let mapPresent = try container.decode(Int32.self)
      if mapPresent != 0 {
        self = .map(try container.decode([SCMapEntryXDR].self))
      } else {
        self = .map(nil)
      }
    case SCValType.address.rawValue:
      let val = try container.decode(SCAddressXDR.self)
      self = .address(val)
    case SCValType.contractInstance.rawValue:
      let val = try container.decode(SCContractInstanceXDR.self)
      self = .contractInstance(val)
    case SCValType.ledgerKeyContractInstance.rawValue:
      self = .ledgerKeyContractInstance
    case SCValType.ledgerKeyNonce.rawValue:
      let val = try container.decode(SCNonceKeyXDR.self)
      self = .ledgerKeyNonce(val)
    default:
      throw StellarSDKError.xdrDecodingError(message: "Unknown SCValXDR discriminant: \(discriminant)")
    }
  }

  public func type() -> Int32 {
    switch self {
    case .bool: return SCValType.bool.rawValue
    case .void: return SCValType.void.rawValue
    case .error: return SCValType.error.rawValue
    case .u32: return SCValType.u32.rawValue
    case .i32: return SCValType.i32.rawValue
    case .u64: return SCValType.u64.rawValue
    case .i64: return SCValType.i64.rawValue
    case .timepoint: return SCValType.timepoint.rawValue
    case .duration: return SCValType.duration.rawValue
    case .u128: return SCValType.u128.rawValue
    case .i128: return SCValType.i128.rawValue
    case .u256: return SCValType.u256.rawValue
    case .i256: return SCValType.i256.rawValue
    case .bytes: return SCValType.bytes.rawValue
    case .string: return SCValType.string.rawValue
    case .symbol: return SCValType.symbol.rawValue
    case .vec: return SCValType.vec.rawValue
    case .map: return SCValType.map.rawValue
    case .address: return SCValType.address.rawValue
    case .contractInstance: return SCValType.contractInstance.rawValue
    case .ledgerKeyContractInstance: return SCValType.ledgerKeyContractInstance.rawValue
    case .ledgerKeyNonce: return SCValType.ledgerKeyNonce.rawValue
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(type())

    switch self {
    case .bool(let val):
      try container.encode(val)
    case .void:
      break
    case .error(let val):
      try container.encode(val)
    case .u32(let val):
      try container.encode(val)
    case .i32(let val):
      try container.encode(val)
    case .u64(let val):
      try container.encode(val)
    case .i64(let val):
      try container.encode(val)
    case .timepoint(let val):
      try container.encode(val)
    case .duration(let val):
      try container.encode(val)
    case .u128(let val):
      try container.encode(val)
    case .i128(let val):
      try container.encode(val)
    case .u256(let val):
      try container.encode(val)
    case .i256(let val):
      try container.encode(val)
    case .bytes(let val):
      try container.encode(val)
    case .string(let val):
      try container.encode(val)
    case .symbol(let val):
      try container.encode(val)
    case .vec(let val):
      if let val = val {
        try container.encode(Int32(1))
        try container.encode(val)
      } else {
        try container.encode(Int32(0))
      }
    case .map(let val):
      if let val = val {
        try container.encode(Int32(1))
        try container.encode(val)
      } else {
        try container.encode(Int32(0))
      }
    case .address(let val):
      try container.encode(val)
    case .contractInstance(let val):
      try container.encode(val)
    case .ledgerKeyContractInstance:
      break
    case .ledgerKeyNonce(let val):
      try container.encode(val)
    }
  }
}

extension SCValXDR {
  public func toTxRep(prefix: String, lines: inout [String]) throws {
    switch self {
    case .bool(let val):
      lines.append("\(prefix).type: SCV_BOOL")
      lines.append("\(prefix).b: \(val)")
    case .void:
      lines.append("\(prefix).type: SCV_VOID")
    case .error(let val):
      lines.append("\(prefix).type: SCV_ERROR")
      try val.toTxRep(prefix: "\(prefix).error", lines: &lines)
    case .u32(let val):
      lines.append("\(prefix).type: SCV_U32")
      lines.append("\(prefix).u32: \(val)")
    case .i32(let val):
      lines.append("\(prefix).type: SCV_I32")
      lines.append("\(prefix).i32: \(val)")
    case .u64(let val):
      lines.append("\(prefix).type: SCV_U64")
      lines.append("\(prefix).u64: \(val)")
    case .i64(let val):
      lines.append("\(prefix).type: SCV_I64")
      lines.append("\(prefix).i64: \(val)")
    case .timepoint(let val):
      lines.append("\(prefix).type: SCV_TIMEPOINT")
      lines.append("\(prefix).timepoint: \(val)")
    case .duration(let val):
      lines.append("\(prefix).type: SCV_DURATION")
      lines.append("\(prefix).duration: \(val)")
    case .u128(let val):
      lines.append("\(prefix).type: SCV_U128")
      try val.toTxRep(prefix: "\(prefix).u128", lines: &lines)
    case .i128(let val):
      lines.append("\(prefix).type: SCV_I128")
      try val.toTxRep(prefix: "\(prefix).i128", lines: &lines)
    case .u256(let val):
      lines.append("\(prefix).type: SCV_U256")
      try val.toTxRep(prefix: "\(prefix).u256", lines: &lines)
    case .i256(let val):
      lines.append("\(prefix).type: SCV_I256")
      try val.toTxRep(prefix: "\(prefix).i256", lines: &lines)
    case .bytes(let val):
      lines.append("\(prefix).type: SCV_BYTES")
      lines.append("\(prefix).bytes: \(TxRepHelper.bytesToHex(val))")
    case .string(let val):
      lines.append("\(prefix).type: SCV_STRING")
      lines.append("\(prefix).str: \(TxRepHelper.escapeString(val))")
    case .symbol(let val):
      lines.append("\(prefix).type: SCV_SYMBOL")
      lines.append("\(prefix).sym: \(TxRepHelper.escapeString(val))")
    case .vec(let val):
      lines.append("\(prefix).type: SCV_VEC")
      if let inner = val {
        lines.append("\(prefix).vec._present: true")
        lines.append("\(prefix).vec.len: \(inner.count)")
        for (i, item) in inner.enumerated() {
          try item.toTxRep(prefix: "\(prefix).vec[\(i)]", lines: &lines)
        }
      } else {
        lines.append("\(prefix).vec._present: false")
      }
    case .map(let val):
      lines.append("\(prefix).type: SCV_MAP")
      if let inner = val {
        lines.append("\(prefix).map._present: true")
        lines.append("\(prefix).map.len: \(inner.count)")
        for (i, item) in inner.enumerated() {
          try item.toTxRep(prefix: "\(prefix).map[\(i)]", lines: &lines)
        }
      } else {
        lines.append("\(prefix).map._present: false")
      }
    case .address(let val):
      lines.append("\(prefix).type: SCV_ADDRESS")
      try val.toTxRep(prefix: "\(prefix).address", lines: &lines)
    case .contractInstance(let val):
      lines.append("\(prefix).type: SCV_CONTRACT_INSTANCE")
      try val.toTxRep(prefix: "\(prefix).instance", lines: &lines)
    case .ledgerKeyContractInstance:
      lines.append("\(prefix).type: SCV_LEDGER_KEY_CONTRACT_INSTANCE")
    case .ledgerKeyNonce(let val):
      lines.append("\(prefix).type: SCV_LEDGER_KEY_NONCE")
      try val.toTxRep(prefix: "\(prefix).nonce_key", lines: &lines)
    }
  }

  public static func fromTxRep(_ map: [String: String], prefix: String) throws -> SCValXDR {
    let discKey = "\(prefix).type"
    guard let discName = TxRepHelper.getValue(map, discKey) else {
      throw TxRepError.missingValue(key: discKey)
    }
    switch discName {
    case "SCV_BOOL":
      let val = (TxRepHelper.getValue(map, "\(prefix).b") ?? "false") == "true"
      return .bool(val)
    case "SCV_VOID":
      return .void
    case "SCV_ERROR":
      let val = try SCErrorXDR.fromTxRep(map, prefix: "\(prefix).error")
      return .error(val)
    case "SCV_U32":
      let val = UInt32(try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).u32") ?? "0"))
      return .u32(val)
    case "SCV_I32":
      let val = try TxRepHelper.parseInt(TxRepHelper.getValue(map, "\(prefix).i32") ?? "0")
      return .i32(val)
    case "SCV_U64":
      let val = try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).u64") ?? "0")
      return .u64(val)
    case "SCV_I64":
      let val = try TxRepHelper.parseInt64(TxRepHelper.getValue(map, "\(prefix).i64") ?? "0")
      return .i64(val)
    case "SCV_TIMEPOINT":
      let val = try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).timepoint") ?? "0")
      return .timepoint(val)
    case "SCV_DURATION":
      let val = try TxRepHelper.parseUInt64(TxRepHelper.getValue(map, "\(prefix).duration") ?? "0")
      return .duration(val)
    case "SCV_U128":
      let val = try UInt128PartsXDR.fromTxRep(map, prefix: "\(prefix).u128")
      return .u128(val)
    case "SCV_I128":
      let val = try Int128PartsXDR.fromTxRep(map, prefix: "\(prefix).i128")
      return .i128(val)
    case "SCV_U256":
      let val = try UInt256PartsXDR.fromTxRep(map, prefix: "\(prefix).u256")
      return .u256(val)
    case "SCV_I256":
      let val = try Int256PartsXDR.fromTxRep(map, prefix: "\(prefix).i256")
      return .i256(val)
    case "SCV_BYTES":
      let val = try TxRepHelper.requireHex(map, "\(prefix).bytes")
      return .bytes(val)
    case "SCV_STRING":
      let val = try TxRepHelper.requireString(map, "\(prefix).str")
      return .string(val)
    case "SCV_SYMBOL":
      let val = try TxRepHelper.requireString(map, "\(prefix).sym")
      return .symbol(val)
    case "SCV_VEC":
      if TxRepHelper.getValue(map, "\(prefix).vec._present") == "true" {
        let valLen = try TxRepHelper.parseInt(TxRepHelper.getValue(map, "\(prefix).vec.len") ?? "0")
        var val = [SCValXDR]()
        for i in 0..<Int(valLen) {
          let item: SCValXDR = try SCValXDR.fromTxRep(map, prefix: "\(prefix).vec[\(i)]")
          val.append(item)
        }
        return .vec(val)
      } else {
        return .vec(nil)
      }
    case "SCV_MAP":
      if TxRepHelper.getValue(map, "\(prefix).map._present") == "true" {
        let valLen = try TxRepHelper.parseInt(TxRepHelper.getValue(map, "\(prefix).map.len") ?? "0")
        var val = [SCMapEntryXDR]()
        for i in 0..<Int(valLen) {
          let item: SCMapEntryXDR = try SCMapEntryXDR.fromTxRep(map, prefix: "\(prefix).map[\(i)]")
          val.append(item)
        }
        return .map(val)
      } else {
        return .map(nil)
      }
    case "SCV_ADDRESS":
      let val = try SCAddressXDR.fromTxRep(map, prefix: "\(prefix).address")
      return .address(val)
    case "SCV_CONTRACT_INSTANCE":
      let val = try SCContractInstanceXDR.fromTxRep(map, prefix: "\(prefix).instance")
      return .contractInstance(val)
    case "SCV_LEDGER_KEY_CONTRACT_INSTANCE":
      return .ledgerKeyContractInstance
    case "SCV_LEDGER_KEY_NONCE":
      let val = try SCNonceKeyXDR.fromTxRep(map, prefix: "\(prefix).nonce_key")
      return .ledgerKeyNonce(val)
    default:
      throw TxRepError.invalidValue(key: discKey)
    }
  }
}
