// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct ContractCostParamsXDR: XDRCodable, Sendable {
  public var entries: [ContractCostParamEntryXDR]

  public init(entries: [ContractCostParamEntryXDR]) {
    self.entries = entries
  }

  public init(from decoder: Decoder) throws {
    entries = try decodeArray(type: ContractCostParamEntryXDR.self, dec: decoder)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(entries)
  }
}
