// This file was automatically generated by xdrgen.
// DO NOT EDIT or your changes may be overwritten.

import Foundation

public struct PriceXDR: XDRCodable, Sendable {
  public let n: Int32
  public let d: Int32

  public init(n: Int32, d: Int32) {
    self.n = n
    self.d = d
  }

  public init(from decoder: Decoder) throws {
    var container = try decoder.unkeyedContainer()
    n = try container.decode(Int32.self)
    d = try container.decode(Int32.self)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.unkeyedContainer()
    try container.encode(n)
    try container.encode(d)
  }
}
