//
//  MethodOptions.swift
//  stellarsdk
//
//  Created by Christian Rogobete on 06.05.25.
//  Copyright © 2025 Soneso. All rights reserved.
//

import Foundation

public class MethodOptions {

    /// The fee to pay for the transaction in Stoops. Default 100.
    public var fee:UInt32
    
    /// The timebounds which should be set for transactions generated by the contract client. Default 300 seconds (5 minutes)
    public let timeoutInSeconds:UInt64
    
    /// Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default true.
    public let simulate:Bool
    
    /// If true, will automatically attempt to restore the transaction if there are archived entries that need renewal. Default false.
    public let restore:Bool

    /// Constructor
    ///
    /// - Parameters:
    ///   - fee: The fee to pay for the transaction in Stoops. Default 100.
    ///   - timeoutInSeconds: The timebounds which should be set for transactions generated by the contract client. Default 300 seconds (5 minutes)
    ///   - simulate: Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default true.
    ///   - restore: If true, will automatically attempt to restore the transaction if there are archived entries that need renewal. Default false.
    ///
    public init(fee: UInt32 = Transaction.minBaseFee, timeoutInSeconds: UInt64 = NetworkConstants.DEFAULT_TIMEOUT_SECONDS, simulate: Bool = true, restore: Bool = false) {
        self.fee = fee
        self.timeoutInSeconds = timeoutInSeconds
        self.simulate = simulate
        self.restore = restore
    }
}
