//
//  MethodOptions.swift
//  stellarsdk
//
//  Created by Christian Rogobete on 06.05.25.
//  Copyright © 2025 Soneso. All rights reserved.
//

import Foundation

/// Transaction configuration options for contract method invocations.
///
/// MethodOptions allows fine-tuning of transaction behavior when invoking
/// contract methods through SorobanClient or AssembledTransaction.
///
/// Configuration parameters:
/// - Fee: Base fee in stroops (default: 100)
/// - Timeout: Transaction validity window (default: 300 seconds)
/// - Simulate: Auto-simulate before submission (default: true)
/// - Restore: Auto-restore archived entries if needed (default: false)
///
/// Example:
/// ```swift
/// // Custom method options for a high-priority transaction
/// let methodOptions = MethodOptions(
///     fee: 10000,           // Higher fee for faster inclusion
///     timeoutInSeconds: 60,  // Shorter validity window
///     simulate: true,        // Auto-simulate
///     restore: true          // Auto-restore if needed
/// )
///
/// let result = try await client.invokeMethod(
///     name: "transfer",
///     args: [from, to, amount],
///     methodOptions: methodOptions
/// )
/// ```
///
/// See also:
/// - [SorobanClient.invokeMethod] for using method options
/// - [AssembledTransaction] for transaction construction
/// - [ClientOptions] for client-level configuration
public final class MethodOptions: Sendable {

    /// The fee to pay for the transaction in stroops. Default 100.
    public let fee:UInt32
    
    /// The timebounds which should be set for transactions generated by the contract client. Default 300 seconds (5 minutes)
    public let timeoutInSeconds:UInt64
    
    /// Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default true.
    public let simulate:Bool
    
    /// If true, will automatically attempt to restore the transaction if there are archived entries that need renewal. Default false.
    public let restore:Bool

    /// Constructor
    ///
    /// - Parameters:
    ///   - fee: The fee to pay for the transaction in stroops. Default 100.
    ///   - timeoutInSeconds: The timebounds which should be set for transactions generated by the contract client. Default 300 seconds (5 minutes)
    ///   - simulate: Whether to automatically simulate the transaction when constructing the AssembledTransaction. Default true.
    ///   - restore: If true, will automatically attempt to restore the transaction if there are archived entries that need renewal. Default false.
    ///
    public init(fee: UInt32 = Transaction.minBaseFee, timeoutInSeconds: UInt64 = NetworkConstants.DEFAULT_TIMEOUT_SECONDS, simulate: Bool = true, restore: Bool = false) {
        self.fee = fee
        self.timeoutInSeconds = timeoutInSeconds
        self.simulate = simulate
        self.restore = restore
    }
}
