name: Submit SBOM to PG Atlas
on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: sbom-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sbom:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Fetch and submit SBOM
        uses: SCF-Public-Goods-Maintenance/pg-atlas-sbom-action@b876c74c601e8e6b5fdad7e4b9161be86b35dfcf
